"use client";

import { ArrowLeftRight, Play, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { format as formatSql } from "sql-formatter";
import { CodeEditor } from "@/components/editor/code-editor";
import { ActionBar, ClearButton, CopyButton, DownloadButton, EmptyOutput, ExampleButton, PanelLabel, WorkspaceFrame } from "@/components/tools/tool-controls";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { decodeBase64, encodeBase64, formatBytes } from "@/lib/tools/encoding";
import { FILE_LIMIT_BYTES, byteSize } from "@/lib/tools/limits";

type SqlDialect = "sql" | "mysql" | "postgresql" | "mariadb" | "sqlite" | "transactsql";
export function SqlFormatterTool() {
  const [input,setInput]=useState(""); const [output,setOutput]=useState(""); const [dialect,setDialect]=useState<SqlDialect>("sql"); const [keywordCase,setKeywordCase]=useState<"upper"|"lower"|"preserve">("upper"); const [error,setError]=useState("");
  const run = () => { if(!input.trim()){setError("กรุณาวาง SQL หรือกดตัวอย่าง");return;} try { setOutput(formatSql(input,{language:dialect,keywordCase,tabWidth:2,linesBetweenQueries:2})); setError(""); toast.success("จัดรูป SQL แล้ว"); } catch(caught){setError(caught instanceof Error?caught.message:"SQL ไม่ถูกต้อง");setOutput("");} };
  return <WorkspaceFrame><div className="mb-4 flex flex-wrap gap-3"><ActionBar><Button onClick={run} aria-label="จัดรูป SQL"><WandSparkles className="size-4"/>จัดรูป</Button><ExampleButton onExample={()=>setInput("select u.id,u.name from users u where u.active=1 order by u.name;")}/><ClearButton onClear={()=>{setInput("");setOutput("");setError("");}}/><CopyButton value={output}/></ActionBar><div className="ml-auto flex gap-2"><Select value={dialect} onValueChange={(value)=>setDialect(value as SqlDialect)}><SelectTrigger className="w-36" aria-label="SQL dialect"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sql">Standard SQL</SelectItem><SelectItem value="transactsql">SQL Server</SelectItem><SelectItem value="mysql">MySQL</SelectItem><SelectItem value="mariadb">MariaDB</SelectItem><SelectItem value="postgresql">PostgreSQL</SelectItem><SelectItem value="sqlite">SQLite</SelectItem></SelectContent></Select><Select value={keywordCase} onValueChange={(value)=>setKeywordCase(value as typeof keywordCase)}><SelectTrigger className="w-36" aria-label="รูปแบบ keyword"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="upper">UPPERCASE</SelectItem><SelectItem value="lower">lowercase</SelectItem><SelectItem value="preserve">คงเดิม</SelectItem></SelectContent></Select></div></div>{error?<p role="alert" className="mb-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="grid gap-4 lg:grid-cols-2"><div><PanelLabel>SQL Input</PanelLabel><CodeEditor value={input} onChange={setInput} language={dialect === "transactsql" ? "mssql" : dialect === "sql" || dialect === "mariadb" ? "sql" : dialect} label="SQL input"/></div><div><PanelLabel>Formatted SQL</PanelLabel>{output?<CodeEditor value={output} language={dialect === "transactsql" ? "mssql" : dialect === "sql" || dialect === "mariadb" ? "sql" : dialect} readOnly label="Formatted SQL output"/>:<EmptyOutput/>}</div></div><p className="mt-3 text-xs text-muted-foreground">เครื่องมือนี้จัดรูปข้อความเท่านั้น ไม่มีการเชื่อมต่อหรือ execute ฐานข้อมูล</p></WorkspaceFrame>;
}

type Base64Mode = "encode-text"|"decode-text"|"file-to-base64"|"base64-to-file";
export function Base64Tool(){
  const [mode,setMode]=useState<Base64Mode>("encode-text"); const [input,setInput]=useState(""); const [output,setOutput]=useState(""); const [file,setFile]=useState<File|null>(null); const [error,setError]=useState("");
  const process = async()=>{try{setError("");if(mode==="encode-text")setOutput(encodeBase64(input));else if(mode==="decode-text")setOutput(decodeBase64(input));else if(mode==="file-to-base64"){if(!file)throw new Error("กรุณาเลือกไฟล์");if(file.size>FILE_LIMIT_BYTES)throw new Error("ไฟล์ใหญ่เกิน 5 MB");const buffer=new Uint8Array(await file.arrayBuffer());let binary="";buffer.forEach((byte)=>{binary+=String.fromCharCode(byte);});setOutput(btoa(binary));}else{const normalized=input.replace(/\s/g,"");const binary=atob(normalized);const bytes=Uint8Array.from(binary,(character)=>character.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes]));const anchor=document.createElement("a");anchor.href=url;anchor.download="decoded-file.bin";anchor.click();URL.revokeObjectURL(url);setOutput(`พร้อมดาวน์โหลด ${formatBytes(bytes.byteLength)}`);}toast.success("ประมวลผล Base64 แล้ว");}catch(caught){setError(caught instanceof Error?caught.message:"ไม่สามารถประมวลผล Base64 ได้");setOutput("");}};
  const clear=()=>{setInput("");setOutput("");setFile(null);setError("");};
  return <WorkspaceFrame><div className="flex flex-wrap items-end gap-3"><div><Label htmlFor="base64-mode">โหมด</Label><Select value={mode} onValueChange={(value)=>{setMode(value as Base64Mode);clear();}}><SelectTrigger id="base64-mode" className="mt-1 w-52"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="encode-text">Text → Base64</SelectItem><SelectItem value="decode-text">Base64 → Text</SelectItem><SelectItem value="file-to-base64">File → Base64</SelectItem><SelectItem value="base64-to-file">Base64 → File</SelectItem></SelectContent></Select></div><ActionBar><Button onClick={()=>void process()} aria-label="ประมวลผล Base64"><Play className="size-4"/>ประมวลผล</Button><ExampleButton onExample={()=>setInput(mode.includes("decode")?"4LiU4Li14Lin4LmE4LiX4LiiIFRvb2xz":"สวัสดี Meaw Tools")}/><ClearButton onClear={clear}/><CopyButton value={output}/>{output&&mode!=="base64-to-file"?<DownloadButton value={output} filename={mode==="decode-text"?"decoded.txt":"base64.txt"}/>:null}</ActionBar></div>{mode==="file-to-base64"?<div className="mt-4"><Label htmlFor="base64-file">เลือกไฟล์ (สูงสุด 5 MB)</Label><Input id="base64-file" type="file" className="mt-1" onChange={(event)=>setFile(event.target.files?.[0]??null)}/></div>:null}{error?<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="mt-4 grid gap-4 lg:grid-cols-2"><div><PanelLabel meta={formatBytes(mode==="file-to-base64"?(file?.size??0):byteSize(input))}>Input</PanelLabel>{mode==="file-to-base64"?<div className="grid min-h-72 place-items-center rounded-lg border border-dashed bg-muted/20 text-sm text-muted-foreground">{file?`${file.name} · ${formatBytes(file.size)}`:"ยังไม่ได้เลือกไฟล์"}</div>:<Textarea value={input} onChange={(event)=>setInput(event.target.value)} className="min-h-72 font-mono" placeholder="วางข้อความหรือ Base64 ที่นี่" aria-label="Base64 input"/>}</div><div><PanelLabel meta={formatBytes(byteSize(output))}>Output</PanelLabel>{output?<Textarea value={output} readOnly className="min-h-72 font-mono" aria-label="Base64 output"/>:<EmptyOutput/>}</div></div></WorkspaceFrame>;
}

type UrlMode="encode-uri"|"decode-uri"|"encode-component"|"decode-component";
export function UrlEncoderTool(){const [mode,setMode]=useState<UrlMode>("encode-component");const [input,setInput]=useState("");const [output,setOutput]=useState("");const [error,setError]=useState("");const run=()=>{try{if(!input)throw new Error("กรุณากรอก URL หรือข้อความ");const result=mode==="encode-uri"?encodeURI(input):mode==="decode-uri"?decodeURI(input):mode==="encode-component"?encodeURIComponent(input):decodeURIComponent(input);setOutput(result);setError("");toast.success("แปลง URL แล้ว");}catch(caught){setError(caught instanceof Error?caught.message:"URL encoding ไม่ถูกต้อง");setOutput("");}};return <WorkspaceFrame><div className="flex flex-wrap gap-3"><Select value={mode} onValueChange={(value)=>setMode(value as UrlMode)}><SelectTrigger className="w-56" aria-label="โหมด URL"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="encode-uri">Encode URI</SelectItem><SelectItem value="decode-uri">Decode URI</SelectItem><SelectItem value="encode-component">Encode URI Component</SelectItem><SelectItem value="decode-component">Decode URI Component</SelectItem></SelectContent></Select><ActionBar><Button onClick={run}><ArrowLeftRight className="size-4"/>แปลง</Button><ExampleButton onExample={()=>setInput("https://example.com/search?q=ภาษาไทย&sort=new")}/><ClearButton onClear={()=>{setInput("");setOutput("");setError("");}}/><CopyButton value={output}/></ActionBar></div>{error?<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="mt-4 grid gap-4 lg:grid-cols-2"><div><PanelLabel>Input</PanelLabel><Textarea value={input} onChange={(event)=>setInput(event.target.value)} className="min-h-72 font-mono" aria-label="URL input"/></div><div><PanelLabel>Output</PanelLabel>{output?<Textarea value={output} readOnly className="min-h-72 font-mono" aria-label="URL output"/>:<EmptyOutput/>}</div></div></WorkspaceFrame>}
