"use client";

import { Clock, FileKey, Play, RefreshCw } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { CodeEditor } from "@/components/editor/code-editor";
import { ActionBar, ClearButton, CopyButton, DownloadButton, EmptyOutput, ExampleButton, PanelLabel, WorkspaceFrame } from "@/components/tools/tool-controls";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { decodeJwtLocally, type JwtResult } from "@/lib/tools/jwt";
import { FILE_LIMIT_BYTES } from "@/lib/tools/limits";

export function JwtDecoderTool(){const [token,setToken]=useState("");const [result,setResult]=useState<JwtResult|null>(null);const [error,setError]=useState("");const run=()=>{try{const next=decodeJwtLocally(token);setResult(next);setError("");toast.success("Decode JWT แล้ว (ยังไม่ได้ verify signature)");}catch(caught){setError(caught instanceof Error?caught.message:"JWT ไม่ถูกต้อง");setResult(null);}};return <WorkspaceFrame><Alert className="mb-4 border-amber-500/30 bg-amber-500/5"><FileKey className="text-amber-600"/><AlertTitle>คำเตือนด้านความปลอดภัย</AlertTitle><AlertDescription>อย่าวาง Token ที่ยังใช้งานได้บนอุปกรณ์สาธารณะ ผลลัพธ์นี้ Decode เท่านั้นและไม่ได้ Verify Signature</AlertDescription></Alert><ActionBar><Button onClick={run}><Play className="size-4"/>Decode</Button><ExampleButton onExample={()=>setToken("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJuYW1lIjoiRGV2VGhhaSIsImlhdCI6MTcwNDA2NzIwMH0.signature")}/><ClearButton onClear={()=>{setToken("");setResult(null);setError("");}}/></ActionBar>{error?<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="mt-4"><Label htmlFor="jwt-input">JWT</Label><Textarea id="jwt-input" value={token} onChange={(event)=>setToken(event.target.value)} className="mt-1 min-h-28 break-all font-mono" placeholder="header.payload.signature"/></div>{result?<div className="mt-4 grid gap-4 lg:grid-cols-2"><div><div className="mb-2 flex items-center justify-between"><PanelLabel>Header</PanelLabel><CopyButton value={JSON.stringify(result.header,null,2)} label="คัดลอก Header"/></div><CodeEditor value={JSON.stringify(result.header,null,2)} readOnly language="json" label="JWT header" minHeight="12rem"/></div><div><div className="mb-2 flex items-center justify-between"><PanelLabel>Payload</PanelLabel><CopyButton value={JSON.stringify(result.payload,null,2)} label="คัดลอก Payload"/></div><CodeEditor value={JSON.stringify(result.payload,null,2)} readOnly language="json" label="JWT payload" minHeight="12rem"/></div><div className="lg:col-span-2 grid gap-3 rounded-lg border bg-muted/20 p-4 text-sm sm:grid-cols-3"><p>ออกเมื่อ: <strong>{result.issuedAt?.toLocaleString("th-TH")??"ไม่ระบุ"}</strong></p><p>หมดอายุ: <strong>{result.expiresAt?.toLocaleString("th-TH")??"ไม่ระบุ"}</strong></p><p>สถานะ: <strong className={result.expired?"text-destructive":"text-green-600"}>{result.expired===undefined?"ไม่ระบุ exp":result.expired?"หมดอายุแล้ว":"ยังไม่หมดอายุ"}</strong></p><p className="break-all sm:col-span-3">Signature: {result.signature}</p></div></div>:null}</WorkspaceFrame>}

export function UuidGeneratorTool(){const [count,setCount]=useState(5);const [uppercase,setUppercase]=useState(false);const [hyphens,setHyphens]=useState(true);const [values,setValues]=useState<string[]>([]);const generate=()=>{const safe=Math.max(1,Math.min(100,count));const next=Array.from({length:safe},()=>{let value=crypto.randomUUID();if(!hyphens)value=value.replaceAll("-","");return uppercase?value.toUpperCase():value.toLowerCase();});setValues(next);toast.success(`สร้าง UUID ${safe} รายการแล้ว`);};const output=values.join("\n");return <WorkspaceFrame><div className="grid gap-4 sm:grid-cols-3"><div><Label htmlFor="uuid-count">จำนวน (1–100)</Label><Input id="uuid-count" type="number" min={1} max={100} value={count} onChange={(event)=>setCount(Number(event.target.value))}/></div><label className="flex items-center justify-between rounded-lg border p-3 text-sm">ตัวพิมพ์ใหญ่ <Switch checked={uppercase} onCheckedChange={setUppercase} aria-label="ใช้ UUID ตัวพิมพ์ใหญ่"/></label><label className="flex items-center justify-between rounded-lg border p-3 text-sm">มี Hyphen <Switch checked={hyphens} onCheckedChange={setHyphens} aria-label="แสดง hyphen ใน UUID"/></label></div><div className="mt-4"><ActionBar><Button onClick={generate}><RefreshCw className="size-4"/>สร้าง UUID</Button><CopyButton value={output} label="คัดลอกทั้งหมด"/><DownloadButton value={output} filename="uuid.txt"/><ClearButton onClear={()=>setValues([])}/></ActionBar></div><div className="mt-4">{values.length?<Textarea value={output} readOnly className="min-h-80 font-mono" aria-label="UUID ที่สร้างแล้ว"/>:<EmptyOutput text="กำหนดรูปแบบแล้วกด “สร้าง UUID”"/>}</div></WorkspaceFrame>}

function timestampResult(date:Date){const unixMs=date.getTime();return [{label:"Local Time",value:date.toLocaleString("th-TH")},{label:"UTC",value:date.toUTCString()},{label:"ISO 8601",value:date.toISOString()},{label:"Unix Seconds",value:String(Math.floor(unixMs/1000))},{label:"Unix Milliseconds",value:String(unixMs)},{label:"วันที่ไทย (พ.ศ.)",value:new Intl.DateTimeFormat("th-TH",{dateStyle:"full",timeStyle:"long"}).format(date)}];}
export function TimestampTool(){const [input,setInput]=useState("");const [unit,setUnit]=useState<"seconds"|"milliseconds"|"date">("seconds");const [date,setDate]=useState<Date|null>(null);const [error,setError]=useState("");const convert=()=>{const parsed=unit==="date"?new Date(input):new Date(Number(input)*(unit==="seconds"?1000:1));if(!input||Number.isNaN(parsed.getTime())){setError("วันที่หรือ Timestamp ไม่ถูกต้อง");setDate(null);return;}setDate(parsed);setError("");toast.success("แปลง Timestamp แล้ว");};const results=useMemo(()=>date?timestampResult(date):[],[date]);return <WorkspaceFrame><div className="flex flex-wrap items-end gap-3"><div className="min-w-56 flex-1"><Label htmlFor="timestamp-input">Timestamp หรือวันที่</Label><Input id="timestamp-input" value={input} onChange={(event)=>setInput(event.target.value)} placeholder={unit==="date"?"2026-08-02T15:30:00":"1704067200"}/></div><Select value={unit} onValueChange={(value)=>setUnit(value as typeof unit)}><SelectTrigger className="w-44" aria-label="หน่วย timestamp"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="seconds">Unix Seconds</SelectItem><SelectItem value="milliseconds">Unix Milliseconds</SelectItem><SelectItem value="date">Date / ISO</SelectItem></SelectContent></Select><ActionBar><Button onClick={convert}><Clock className="size-4"/>แปลง</Button><Button variant="secondary" onClick={()=>{const now=new Date();setDate(now);setInput(String(Math.floor(now.getTime()/1000)));setUnit("seconds");}}>เวลาปัจจุบัน</Button><ClearButton onClear={()=>{setInput("");setDate(null);setError("");}}/></ActionBar></div>{error?<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="mt-4">{results.length?<div className="grid gap-3 sm:grid-cols-2">{results.map((item)=><div key={item.label} className="rounded-lg border bg-muted/20 p-4"><div className="flex justify-between gap-3"><div><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-1 break-all font-mono text-sm">{item.value}</p></div><CopyButton value={item.value} label="คัดลอก"/></div></div>)}</div>:<EmptyOutput size="compact" text="ผลลัพธ์หลายรูปแบบจะแสดงที่นี่"/>}</div></WorkspaceFrame>}

type HashAlgorithm="SHA-1"|"SHA-256"|"SHA-384"|"SHA-512";
async function digest(data:ArrayBuffer,algorithm:HashAlgorithm){const hash=await crypto.subtle.digest(algorithm,data);return Array.from(new Uint8Array(hash),(byte)=>byte.toString(16).padStart(2,"0")).join("");}
export function HashTool(){const [algorithm,setAlgorithm]=useState<HashAlgorithm>("SHA-256");const [text,setText]=useState("");const [file,setFile]=useState<File|null>(null);const [hash,setHash]=useState("");const [compare,setCompare]=useState("");const [uppercase,setUppercase]=useState(false);const [error,setError]=useState("");const run=async()=>{try{if(file&&file.size>FILE_LIMIT_BYTES)throw new Error("ไฟล์ใหญ่เกิน 5 MB");if(!file&&!text)throw new Error("กรุณากรอกข้อความหรือเลือกไฟล์");const buffer=file?await file.arrayBuffer():new TextEncoder().encode(text).buffer;setHash(await digest(buffer,algorithm));setError("");toast.success("สร้าง Hash แล้ว");}catch(caught){setError(caught instanceof Error?caught.message:"สร้าง Hash ไม่สำเร็จ");}};const output=uppercase?hash.toUpperCase():hash.toLowerCase();const matches=compare.trim()?compare.trim().toLowerCase()===hash.toLowerCase():undefined;return <WorkspaceFrame><div className="grid gap-4 lg:grid-cols-2"><div><Label htmlFor="hash-text">ข้อความ</Label><Textarea id="hash-text" value={text} onChange={(event)=>{setText(event.target.value);setFile(null);}} className="mt-1 min-h-40 font-mono"/></div><div><Label htmlFor="hash-file">หรือเลือกไฟล์ (สูงสุด 5 MB)</Label><Input id="hash-file" type="file" className="mt-1" onChange={(event)=>{setFile(event.target.files?.[0]??null);setText("");}}/><div className="mt-4 flex gap-3"><Select value={algorithm} onValueChange={(value)=>setAlgorithm(value as HashAlgorithm)}><SelectTrigger aria-label="Hash algorithm"><SelectValue/></SelectTrigger><SelectContent>{["SHA-1","SHA-256","SHA-384","SHA-512"].map((value)=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><label className="flex items-center gap-2 rounded-lg border px-3 text-sm">Uppercase <Switch checked={uppercase} onCheckedChange={setUppercase}/></label></div></div></div><div className="mt-4"><ActionBar><Button onClick={()=>void run()}><Play className="size-4"/>สร้าง Hash</Button><CopyButton value={output}/><ClearButton onClear={()=>{setText("");setFile(null);setHash("");setCompare("");setError("");}}/></ActionBar></div>{error?<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}<div className="mt-4"><PanelLabel>Hash Result</PanelLabel>{output?<Textarea value={output} readOnly className="min-h-24 break-all font-mono"/>:<EmptyOutput size="compact" text="Hash จะแสดงที่นี่"/>}</div><div className="mt-4"><Label htmlFor="compare-hash">เปรียบเทียบ Hash (ไม่บังคับ)</Label><Input id="compare-hash" value={compare} onChange={(event)=>setCompare(event.target.value)} className="mt-1 font-mono"/>{matches!==undefined?<p className={`mt-2 text-sm font-medium ${matches?"text-green-600":"text-destructive"}`}>{matches?"Hash ตรงกัน":"Hash ไม่ตรงกัน"}</p>:null}</div></WorkspaceFrame>}
