"use client";

import dynamic from "next/dynamic";

const loading = () => <div role="status" aria-live="polite" className="h-96 animate-pulse rounded-2xl border bg-muted/50" aria-label="กำลังโหลดเครื่องมือ" />;
const components = {
  "json-formatter": dynamic(() => import("@/features/tools/json-tools").then((module) => module.JsonFormatterTool), { loading, ssr: false }),
  "json-validator": dynamic(() => import("@/features/tools/json-tools").then((module) => module.JsonValidatorTool), { loading, ssr: false }),
  "sql-formatter": dynamic(() => import("@/features/tools/text-tools").then((module) => module.SqlFormatterTool), { loading, ssr: false }),
  "base64": dynamic(() => import("@/features/tools/text-tools").then((module) => module.Base64Tool), { loading, ssr: false }),
  "url-encoder": dynamic(() => import("@/features/tools/text-tools").then((module) => module.UrlEncoderTool), { loading, ssr: false }),
  "utm-builder": dynamic(() => import("@/features/tools/utm-builder-tool").then((module) => module.UtmBuilderTool), { loading, ssr: false }),
  "jwt-decoder": dynamic(() => import("@/features/tools/utility-tools").then((module) => module.JwtDecoderTool), { loading, ssr: false }),
  "uuid-generator": dynamic(() => import("@/features/tools/utility-tools").then((module) => module.UuidGeneratorTool), { loading, ssr: false }),
  "timestamp-converter": dynamic(() => import("@/features/tools/utility-tools").then((module) => module.TimestampTool), { loading, ssr: false }),
  "buddhist-year-converter": dynamic(() => import("@/features/tools/everyday-tools").then((module) => module.BuddhistYearConverterTool), { loading, ssr: false }),
  "hash-generator": dynamic(() => import("@/features/tools/utility-tools").then((module) => module.HashTool), { loading, ssr: false }),
  "regex-tester": dynamic(() => import("@/features/tools/advanced-tools").then((module) => module.RegexTool), { loading, ssr: false }),
  "diff-checker": dynamic(() => import("@/features/tools/advanced-tools").then((module) => module.DiffTool), { loading, ssr: false }),
  "cron-generator": dynamic(() => import("@/features/tools/advanced-tools").then((module) => module.CronTool), { loading, ssr: false }),
  "markdown-table-generator": dynamic(() => import("@/features/tools/markdown-table-tool").then((module) => module.MarkdownTableTool), { loading, ssr: false }),
  "html-table-generator": dynamic(() => import("@/features/tools/html-table-tool").then((module) => module.HtmlTableTool), { loading, ssr: false }),
  "word-counter": dynamic(() => import("@/features/tools/work-tools").then((module) => module.WordCounterTool), { loading, ssr: false }),
  "word-cloud-generator": dynamic(() => import("@/features/tools/word-cloud-generator-tool").then((module) => module.WordCloudGeneratorTool), { loading, ssr: false }),
  "text-cleaner": dynamic(() => import("@/features/tools/work-tools").then((module) => module.TextCleanerTool), { loading, ssr: false }),
  "csv-to-excel": dynamic(() => import("@/features/tools/csv-to-excel-tool").then((module) => module.CsvToExcelTool), { loading, ssr: false }),
  "excel-to-csv": dynamic(() => import("@/features/tools/excel-to-csv-tool").then((module) => module.ExcelToCsvTool), { loading, ssr: false }),
  "csv-cleaner": dynamic(() => import("@/features/tools/csv-cleaner-tool").then((module) => module.CsvCleanerTool), { loading, ssr: false }),
  "resume-builder": dynamic(() => import("@/features/tools/resume-builder-tool").then((module) => module.ResumeBuilderTool), { loading, ssr: false }),
  "typing-test": dynamic(() => import("@/features/tools/typing-test-tool").then((module) => module.TypingTestTool), { loading, ssr: false }),
  "special-characters": dynamic(() => import("@/features/tools/special-characters-tool").then((module) => module.SpecialCharactersTool), { loading, ssr: false }),
  "text-to-speech": dynamic(() => import("@/features/tools/text-to-speech-tool").then((module) => module.TextToSpeechTool), { loading, ssr: false }),
  "grade-calculator": dynamic(() => import("@/features/tools/grade-calculator-tool").then((module) => module.GradeCalculatorTool), { loading, ssr: false }),
  "percentage-calculator": dynamic(() => import("@/features/tools/work-tools").then((module) => module.PercentageCalculatorTool), { loading, ssr: false }),
  "vat-calculator": dynamic(() => import("@/features/tools/vat-calculator-tool").then((module) => module.VatCalculatorTool), { loading, ssr: false }),
  "fuel-cost-calculator": dynamic(() => import("@/features/tools/fuel-cost-calculator-tool").then((module) => module.FuelCostCalculatorTool), { loading, ssr: false }),
  "unit-converter": dynamic(() => import("@/features/tools/work-tools").then((module) => module.UnitConverterTool), { loading, ssr: false }),
  "date-calculator": dynamic(() => import("@/features/tools/work-tools").then((module) => module.DateCalculatorTool), { loading, ssr: false }),
  "business-days-calculator": dynamic(() => import("@/features/tools/business-days-calculator-tool").then((module) => module.BusinessDaysCalculatorTool), { loading, ssr: false }),
  "working-hours-calculator": dynamic(() => import("@/features/tools/working-hours-calculator-tool").then((module) => module.WorkingHoursCalculatorTool), { loading, ssr: false }),
  "shift-pattern-calculator": dynamic(() => import("@/features/tools/shift-pattern-calculator-tool").then((module) => module.ShiftPatternCalculatorTool), { loading, ssr: false }),
  "hourly-rate-calculator": dynamic(() => import("@/features/tools/hourly-rate-calculator-tool").then((module) => module.HourlyRateCalculatorTool), { loading, ssr: false }),
  "meeting-cost-calculator": dynamic(() => import("@/features/tools/meeting-cost-calculator-tool").then((module) => module.MeetingCostCalculatorTool), { loading, ssr: false }),
  "billable-hours-calculator": dynamic(() => import("@/features/tools/billable-hours-calculator-tool").then((module) => module.BillableHoursCalculatorTool), { loading, ssr: false }),
  "project-cost-calculator": dynamic(() => import("@/features/tools/project-cost-calculator-tool").then((module) => module.ProjectCostCalculatorTool), { loading, ssr: false }),
  "team-capacity-calculator": dynamic(() => import("@/features/tools/team-capacity-calculator-tool").then((module) => module.TeamCapacityCalculatorTool), { loading, ssr: false }),
  "labor-cost-calculator": dynamic(() => import("@/features/tools/labor-cost-calculator-tool").then((module) => module.LaborCostCalculatorTool), { loading, ssr: false }),
  "sales-commission-calculator": dynamic(() => import("@/features/tools/sales-commission-calculator-tool").then((module) => module.SalesCommissionCalculatorTool), { loading, ssr: false }),
  "safety-stock-calculator": dynamic(() => import("@/features/tools/safety-stock-calculator-tool").then((module) => module.SafetyStockCalculatorTool), { loading, ssr: false }),
  "inventory-turnover-calculator": dynamic(() => import("@/features/tools/inventory-turnover-calculator-tool").then((module) => module.InventoryTurnoverCalculatorTool), { loading, ssr: false }),
  "cost-of-goods-sold-calculator": dynamic(() => import("@/features/tools/cost-of-goods-sold-calculator-tool").then((module) => module.CostOfGoodsSoldCalculatorTool), { loading, ssr: false }),
  "food-cost-calculator": dynamic(() => import("@/features/tools/food-cost-calculator-tool").then((module) => module.FoodCostCalculatorTool), { loading, ssr: false }),
  "drink-cost-calculator": dynamic(() => import("@/features/tools/drink-cost-calculator-tool").then((module) => module.DrinkCostCalculatorTool), { loading, ssr: false }),
  "coffee-cost-calculator": dynamic(() => import("@/features/tools/coffee-cost-calculator-tool").then((module) => module.CoffeeCostCalculatorTool), { loading, ssr: false }),
  "coffee-roasting-calculator": dynamic(() => import("@/features/tools/coffee-roasting-calculator-tool").then((module) => module.CoffeeRoastingCalculatorTool), { loading, ssr: false }),
  "jpg-to-pdf": dynamic(() => import("@/features/tools/jpg-to-pdf-tool").then((module) => module.JpgToPdfTool), { loading, ssr: false }),
  "qr-code-generator": dynamic(() => import("@/features/tools/qr-code-tool").then((module) => module.QrCodeTool), { loading, ssr: false }),
  "barcode-generator": dynamic(() => import("@/features/tools/barcode-generator-tool").then((module) => module.BarcodeGeneratorTool), { loading, ssr: false }),
  "qr-code-scanner": dynamic(() => import("@/features/tools/qr-scanner-tool").then((module) => module.QrScannerTool), { loading, ssr: false }),
  "image-to-text": dynamic(() => import("@/features/tools/image-to-text-tool").then((module) => module.ImageToTextTool), { loading, ssr: false }),
  "age-calculator": dynamic(() => import("@/features/tools/age-calculator-tool").then((module) => module.AgeCalculatorTool), { loading, ssr: false }),
  "loan-calculator": dynamic(() => import("@/features/tools/finance-calculator-tools").then((module) => module.LoanCalculatorTool), { loading, ssr: false }),
  "thai-income-tax-calculator": dynamic(() => import("@/features/tools/thai-income-tax-tool").then((module) => module.ThaiIncomeTaxTool), { loading, ssr: false }),
  "salary-calculator": dynamic(() => import("@/features/tools/salary-calculator-tool").then((module) => module.SalaryCalculatorTool), { loading, ssr: false }),
  "overtime-calculator-thailand": dynamic(() => import("@/features/tools/overtime-calculator-tool").then((module) => module.OvertimeCalculatorTool), { loading, ssr: false }),
  "social-security-pension-calculator": dynamic(() => import("@/features/tools/social-security-pension-tool").then((module) => module.SocialSecurityPensionTool), { loading, ssr: false }),
  "thai-id-validator": dynamic(() => import("@/features/tools/thai-id-validator-tool").then((module) => module.ThaiIdValidatorTool), { loading, ssr: false }),
  "bmi-calculator": dynamic(() => import("@/features/tools/bmi-calculator-tool").then((module) => module.BmiCalculatorTool), { loading, ssr: false }),
  "profit-margin-calculator": dynamic(() => import("@/features/tools/finance-calculator-tools").then((module) => module.ProfitMarginCalculatorTool), { loading, ssr: false }),
  "quotation-generator": dynamic(() => import("@/features/tools/quotation-generator-tool").then((module) => module.QuotationGeneratorTool), { loading, ssr: false }),
  "heic-to-jpg": dynamic(() => import("@/features/tools/heic-to-jpg-tool").then((module) => module.HeicToJpgTool), { loading, ssr: false }),
  "jpg-to-png": dynamic(() => import("@/features/tools/image-format-batch-tool").then((module) => module.ImageFormatBatchTool), { loading, ssr: false }),
  "png-to-jpg": dynamic(() => import("@/features/tools/image-processing-tools").then((module) => module.PngToJpgTool), { loading, ssr: false }),
  "background-remover": dynamic(() => import("@/features/tools/background-remover-tool").then((module) => module.BackgroundRemoverTool), { loading, ssr: false }),
  "image-compressor": dynamic(() => import("@/features/tools/image-processing-tools").then((module) => module.ImageCompressorTool), { loading, ssr: false }),
  "image-cropper": dynamic(() => import("@/features/tools/image-cropper-tool").then((module) => module.ImageCropperTool), { loading, ssr: false }),
  "favicon-generator": dynamic(() => import("@/features/tools/favicon-generator-tool").then((module) => module.FaviconGeneratorTool), { loading, ssr: false }),
  "color-picker": dynamic(() => import("@/features/tools/color-picker-tool").then((module) => module.ColorPickerTool), { loading, ssr: false }),
  "password-generator": dynamic(() => import("@/features/tools/popular-generator-tools").then((module) => module.PasswordGeneratorTool), { loading, ssr: false }),
  "random-number-generator": dynamic(() => import("@/features/tools/popular-generator-tools").then((module) => module.RandomNumberGeneratorTool), { loading, ssr: false }),
  "random-wheel": dynamic(() => import("@/features/tools/everyday-tools").then((module) => module.RandomWheelTool), { loading, ssr: false }),
  "pdf-to-jpg": dynamic(() => import("@/features/tools/pdf-to-jpg-tool").then((module) => module.PdfToJpgTool), { loading, ssr: false }),
  "merge-pdf": dynamic(() => import("@/features/tools/pdf-organizer-tools").then((module) => module.MergePdfTool), { loading, ssr: false }),
  "split-pdf": dynamic(() => import("@/features/tools/pdf-organizer-tools").then((module) => module.SplitPdfTool), { loading, ssr: false }),
  "pdf-organizer": dynamic(() => import("@/features/tools/pdf-organizer-tool").then((module) => module.PdfOrganizerTool), { loading, ssr: false }),
  "sign-pdf": dynamic(() => import("@/features/tools/sign-pdf-tool").then((module) => module.SignPdfTool), { loading, ssr: false }),
} satisfies Record<string, React.ComponentType>;

export function ToolRenderer({ slug }: { slug: string }) { const Component = components[slug as keyof typeof components]; return Component ? <Component /> : null; }
