import type { ToolCategory, ToolCategoryConfig, ToolConfig } from "@/types/tool";

export const categoryConfigs: ToolCategoryConfig[] = [
  { value: "data", label: "ข้อมูล", description: "จัดรูป ตรวจสอบ และแปลงข้อมูลที่ใช้ในการพัฒนาและวิเคราะห์ระบบ", icon: "Database" },
  { value: "encoding", label: "เข้ารหัส", description: "เข้ารหัสและถอดรหัสข้อมูลสำหรับ URL, Base64 และงานแลกเปลี่ยนข้อมูล", icon: "Binary" },
  { value: "security", label: "ความปลอดภัย", description: "ตรวจสอบ token และสร้าง hash โดยประมวลผลข้อมูลภายใน Browser", icon: "ShieldCheck" },
  { value: "text", label: "ข้อความ", description: "ค้นหา เปรียบเทียบ และจัดการข้อความสำหรับงานเขียนและงานเทคนิค", icon: "TextCursorInput" },
  { value: "date-time", label: "วันที่และเวลา", description: "แปลงและทำความเข้าใจวันที่ เวลา Timestamp และเขตเวลา", icon: "Clock3" },
  { value: "developer", label: "เครื่องมือนักพัฒนา", description: "เครื่องมือประจำวันสำหรับเขียนโค้ด ทดสอบ และดูแลระบบ", icon: "Code2" },
  { value: "productivity", label: "งานเอกสาร", description: "ลดงานซ้ำจากข้อความ เอกสาร และข้อมูลที่ใช้ในการทำงานทั่วไป", icon: "BriefcaseBusiness" },
  { value: "business", label: "ธุรกิจและการเงิน", description: "สร้างเอกสารธุรกิจ คำนวณกำไร อัตราส่วน และประมาณการทางการเงินด้วยสูตรที่ตรวจสอบได้", icon: "CircleDollarSign" },
  { value: "calculator", label: "เครื่องคำนวณ", description: "คำนวณตัวเลข อายุ วันที่ และหน่วยด้วยสูตรที่อ่านและตรวจสอบได้", icon: "Calculator" },
  { value: "media", label: "รูปภาพและ PDF", description: "สร้างและแปลงรูปภาพ QR Code และเอกสาร PDF ภายในอุปกรณ์", icon: "Images" },
];

export const toolCategories: Array<{ value: ToolCategory | "all"; label: string }> = [
  { value: "all", label: "ทั้งหมด" },
  ...categoryConfigs.map(({ value, label }) => ({ value, label })),
];

const commonFaq = [
  {
    question: "ข้อมูลถูกส่งขึ้น Server หรือไม่?",
    answer:
      "ไม่ ข้อมูลที่กรอกถูกประมวลผลภายใน Browser และ Meaw Tools ไม่บันทึกเนื้อหาเครื่องมือ",
  },
  {
    question: "ใช้งานฟรีหรือไม่?",
    answer: "ใช้งานฟรี ไม่ต้องสมัครสมาชิก และไม่มีข้อจำกัดจากบัญชีผู้ใช้",
  },
];

export const tools: ToolConfig[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    thaiName: "จัดรูป JSON ออนไลน์",
    shortDescription: "จัดรูป ย่อ และตรวจสอบ JSON ให้อ่านง่าย",
    description:
      "จัดรูป JSON ด้วย indent 2 หรือ 4 ช่อง ตรวจสอบ syntax คัดลอก และดาวน์โหลดผลลัพธ์ได้ทันที",
    category: "data",
    icon: "Braces",
    keywords: ["json", "formatter", "จัดรูป json", "minify", "pretty print"],
    isPopular: true,
    isNew: false,
    relatedTools: ["json-validator", "base64", "diff-checker"],
    howTo: ["วาง JSON ในช่องข้อมูล", "เลือก indent แล้วกดจัดรูปหรือย่อ", "คัดลอกหรือดาวน์โหลดผลลัพธ์"],
    example: '{"name":"Benz","skills":["PHP","Next.js","SQL"]}',
    caution: "ข้อมูลขนาดใหญ่มากอาจใช้หน่วยความจำของ Browser สูง",
    faq: commonFaq,
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    thaiName: "ตรวจสอบ JSON ออนไลน์",
    shortDescription: "ตรวจ syntax พร้อมตำแหน่งบรรทัดและสถิติ",
    description: "ตรวจสอบความถูกต้องของ JSON พร้อมบรรทัด คอลัมน์ และจำนวน object, array และ key",
    category: "data",
    icon: "BadgeCheck",
    keywords: ["json", "validator", "ตรวจ json", "syntax"],
    isPopular: false,
    isNew: false,
    relatedTools: ["json-formatter", "diff-checker", "base64"],
    howTo: ["วาง JSON ที่ต้องการตรวจ", "กดตรวจสอบ", "แก้ไขตามตำแหน่ง error ที่แสดง"],
    example: '{"valid":true,"items":[1,2,3]}',
    caution: "เครื่องมือตรวจ syntax เท่านั้น ไม่ตรวจ business schema",
    faq: commonFaq,
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    thaiName: "จัดรูป SQL ออนไลน์",
    shortDescription: "จัดรูป SQL หลาย dialect โดยไม่ execute query",
    description: "จัดรูป SQL Server, MySQL, PostgreSQL, MariaDB, SQLite และ Standard SQL ภายใน Browser",
    category: "data",
    icon: "Database",
    keywords: ["sql", "formatter", "mysql", "postgresql", "sql server", "จัดรูป sql"],
    isPopular: true,
    isNew: false,
    relatedTools: ["json-formatter", "diff-checker", "regex-tester"],
    howTo: ["วาง SQL", "เลือก dialect และรูปแบบ keyword", "กดจัดรูปและคัดลอกผลลัพธ์"],
    example: "select u.id,u.name from users u where u.active=1 order by u.name;",
    caution: "เครื่องมือนี้ไม่เชื่อมต่อฐานข้อมูลและไม่ execute SQL",
    faq: commonFaq,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    thaiName: "อ่าน JWT ออนไลน์",
    shortDescription: "ถอด Header และ Payload โดยไม่ verify signature",
    description: "อ่านส่วนประกอบ JWT พร้อมเวลาออก token และวันหมดอายุ โดยไม่ส่ง token ออกจาก Browser",
    category: "security",
    icon: "KeyRound",
    keywords: ["jwt", "decoder", "token", "decode jwt", "อ่าน jwt"],
    isPopular: true,
    isNew: false,
    relatedTools: ["base64", "timestamp-converter", "json-formatter"],
    howTo: ["วาง JWT ที่มี 3 ส่วน", "กด Decode", "ตรวจ Header, Payload และสถานะหมดอายุ"],
    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJuYW1lIjoiRGV2VGhhaSIsImlhdCI6MTcwNDA2NzIwMH0.signature",
    caution: "อย่าวาง token ที่ยังใช้งานได้บนเครื่องสาธารณะ และผล Decode ไม่ได้ยืนยันลายเซ็น",
    faq: commonFaq,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    thaiName: "สร้าง UUID v4",
    shortDescription: "สร้าง UUID v4 ครั้งละ 1–100 รายการ",
    description: "สร้าง UUID v4 ด้วย Browser Crypto API เลือกตัวพิมพ์และเครื่องหมายขีดได้",
    category: "developer",
    icon: "Fingerprint",
    keywords: ["uuid", "guid", "uuid v4", "สร้าง uuid"],
    isPopular: true,
    isNew: false,
    relatedTools: ["hash-generator", "timestamp-converter", "json-formatter"],
    howTo: ["กำหนดจำนวน 1–100", "เลือกรูปแบบ", "กดสร้างแล้วคัดลอกหรือดาวน์โหลด"],
    example: "จำนวน 5 รายการ แบบ lowercase พร้อม hyphen",
    caution: "UUID ใช้เป็น identifier ได้ แต่ไม่ควรใช้แทน secret",
    faq: commonFaq,
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    thaiName: "แปลง Timestamp",
    shortDescription: "แปลง Unix, ISO, UTC, เวลาท้องถิ่น และ พ.ศ.",
    description: "แปลง Unix seconds หรือ milliseconds และวันเวลาเป็นรูปแบบที่นักพัฒนาใช้บ่อย",
    category: "date-time",
    icon: "Clock3",
    keywords: ["timestamp", "unix", "เวลา", "utc", "iso 8601", "พ.ศ."],
    isPopular: true,
    isNew: false,
    relatedTools: ["buddhist-year-converter", "cron-generator", "jwt-decoder"],
    howTo: ["กรอก timestamp หรือเลือกวันที่", "เลือกหน่วย", "ดูและคัดลอกผลลัพธ์หลายรูปแบบ"],
    example: "1704067200",
    caution: "เวลาท้องถิ่นขึ้นกับ timezone ของอุปกรณ์ที่ใช้งาน",
    faq: commonFaq,
  },
  {
    slug: "buddhist-year-converter",
    name: "Buddhist Year Converter",
    thaiName: "แปลงปี พ.ศ. ค.ศ.",
    shortDescription: "แปลงปี พ.ศ. และ ค.ศ. ทีละปีหรือหลายรายการ",
    description: "แปลงปีพุทธศักราชและคริสต์ศักราชได้สูงสุด 100 รายการ พร้อมสลับทิศทาง คัดลอกผลลัพธ์ และสูตรสำหรับ Excel หรือ Google Sheets",
    category: "date-time",
    icon: "CalendarDays",
    keywords: ["พ.ศ. ค.ศ.", "แปลง พ.ศ. เป็น ค.ศ.", "แปลง ค.ศ. เป็น พ.ศ.", "ปีนี้ ค.ศ. อะไร", "พศ คศ", "buddhist year converter", "excel พ.ศ. ค.ศ."],
    isPopular: true,
    isNew: true,
    relatedTools: ["timestamp-converter", "date-calculator", "age-calculator"],
    howTo: ["เลือกทิศทาง พ.ศ. → ค.ศ. หรือ ค.ศ. → พ.ศ.", "กรอกปีหนึ่งรายการหรือหลายรายการ โดยคั่นด้วยบรรทัด เว้นวรรค หรือ comma", "กดแปลงปี แล้วคัดลอกผลลัพธ์หรือสูตร Excel"],
    example: "พ.ศ. 2569 → ค.ศ. 2026",
    caution: "ใช้หลักบวกหรือลบ 543 สำหรับเลขปีทั่วไป วันที่ทางประวัติศาสตร์ก่อน พ.ศ. 2484 อาจต้องพิจารณาวันขึ้นปีใหม่ของไทยในขณะนั้นเพิ่มเติม",
    faq: [...commonFaq, { question: "ทำไม พ.ศ. กับ ค.ศ. ต่างกัน 543 ปี?", answer: "การแปลงเลขปีที่ใช้ทั่วไปในไทยใช้ พ.ศ. = ค.ศ. + 543 หรือ ค.ศ. = พ.ศ. - 543 เครื่องมือนี้จึงใช้สูตรดังกล่าวกับทุกรายการ" }],
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    thaiName: "เข้ารหัสและถอด Base64",
    shortDescription: "แปลงข้อความ UTF-8 และไฟล์เป็น Base64",
    description: "เข้ารหัสและถอด Base64 รองรับภาษาไทย พร้อมตรวจรูปแบบและจำกัดขนาดไฟล์",
    category: "encoding",
    icon: "Binary",
    keywords: ["base64", "encode", "decode", "เข้ารหัส", "ถอดรหัส"],
    isPopular: false,
    isNew: false,
    relatedTools: ["url-encoder", "jwt-decoder", "hash-generator"],
    howTo: ["เลือกโหมดเข้ารหัสหรือถอดรหัส", "วางข้อความหรือเลือกไฟล์", "กดประมวลผลแล้วคัดลอก"],
    example: "สวัสดี Meaw",
    caution: "Base64 ไม่ใช่การเข้ารหัสเพื่อความปลอดภัย และไฟล์จำกัด 5 MB",
    faq: commonFaq,
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    thaiName: "เข้ารหัสและถอด URL",
    shortDescription: "Encode หรือ Decode URI และ URI Component",
    description: "แปลง URL และ query parameter อย่างถูกต้องด้วยมาตรฐาน Browser",
    category: "encoding",
    icon: "Link2",
    keywords: ["url", "uri", "encodeURIComponent", "decode url", "เปอร์เซ็นต์"],
    isPopular: false,
    isNew: false,
    relatedTools: ["base64", "regex-tester", "json-formatter"],
    howTo: ["เลือก URI หรือ URI Component", "เลือก Encode หรือ Decode", "วางข้อความแล้วประมวลผล"],
    example: "https://example.com/search?q=ภาษาไทย&sort=new",
    caution: "ใช้ URI Component สำหรับค่ารายตัวใน query string",
    faq: commonFaq,
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    thaiName: "ทดสอบ Regular Expression",
    shortDescription: "ค้นหา match, group และทดลอง replace",
    description: "ทดสอบ Regular Expression พร้อม flags, match index, capture group และ replace preview",
    category: "text",
    icon: "Regex",
    keywords: ["regex", "regexp", "regular expression", "ทดสอบ regex"],
    isPopular: true,
    isNew: false,
    relatedTools: ["diff-checker", "json-validator", "url-encoder"],
    howTo: ["กรอก pattern และ flags", "วางข้อความทดสอบ", "กดทดสอบและดู match หรือ replace preview"],
    example: "Pattern: \\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b",
    caution: "ระบบจำกัดขนาดและปฏิเสธ pattern เสี่ยงสูงเพื่อลด ReDoS ใน Browser",
    faq: commonFaq,
  },
  {
    slug: "diff-checker",
    name: "Text Diff Checker",
    thaiName: "เปรียบเทียบข้อความ",
    shortDescription: "ดูข้อความที่เพิ่ม ลบ และเปลี่ยนแปลง",
    description: "เปรียบเทียบข้อความแบบ inline หรือ side-by-side พร้อมตัวเลือก ignore case และ whitespace",
    category: "text",
    icon: "GitCompareArrows",
    keywords: ["diff", "compare", "text", "เปรียบเทียบข้อความ"],
    isPopular: false,
    isNew: false,
    relatedTools: ["regex-tester", "json-formatter", "sql-formatter"],
    howTo: ["วางข้อความต้นฉบับและข้อความใหม่", "เลือกตัวเลือกที่ต้องการละเว้น", "กดเปรียบเทียบ"],
    example: "เดิม: Meaw Tools\nใหม่: Meaw Tools ใช้งานฟรี",
    caution: "ข้อความแต่ละฝั่งจำกัด 1 MB เพื่อป้องกัน Browser ค้าง",
    faq: commonFaq,
  },
  {
    slug: "cron-generator",
    name: "Cron Generator",
    thaiName: "สร้าง Cron Expression",
    shortDescription: "สร้าง Cron 5 ช่อง พร้อมคำอธิบายและรอบถัดไป",
    description: "สร้าง Cron จากแบบฟอร์ม อธิบายภาษาไทย และแสดงเวลาทำงานถัดไป",
    category: "developer",
    icon: "CalendarClock",
    keywords: ["cron", "crontab", "scheduler", "สร้าง cron", "ตั้งเวลา"],
    isPopular: false,
    isNew: false,
    relatedTools: ["timestamp-converter", "uuid-generator", "regex-tester"],
    howTo: ["กำหนดนาที ชั่วโมง วัน เดือน และวันในสัปดาห์", "ตรวจ expression", "คัดลอกไปใช้กับ platform ของคุณ"],
    example: "0 8 * * 1-5",
    caution: "Cron syntax และ timezone อาจแตกต่างกันตาม Linux, GitHub Actions, Vercel หรือ cloud provider",
    faq: commonFaq,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    thaiName: "สร้าง Hash ออนไลน์",
    shortDescription: "สร้าง SHA-1, SHA-256, SHA-384 และ SHA-512",
    description: "คำนวณ hash ของข้อความหรือไฟล์ด้วย Web Crypto API และเปรียบเทียบค่าได้",
    category: "security",
    icon: "Hash",
    keywords: ["hash", "sha256", "sha512", "checksum", "สร้าง hash"],
    isPopular: false,
    isNew: false,
    relatedTools: ["base64", "uuid-generator", "jwt-decoder"],
    howTo: ["เลือก algorithm", "กรอกข้อความหรือเลือกไฟล์", "กดสร้างและเปรียบเทียบ hash หากต้องการ"],
    example: "Meaw Tools",
    caution: "Hash ไม่ใช่ encryption และ SHA ธรรมดาไม่เหมาะสำหรับเก็บรหัสผ่าน",
    faq: commonFaq,
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    thaiName: "นับคำและตัวอักษร",
    shortDescription: "นับคำไทย ตัวอักษร ประโยค บรรทัด และเวลาอ่าน",
    description: "วิเคราะห์ข้อความภาษาไทยและภาษาอังกฤษแบบทันที พร้อมจำนวนคำ ตัวอักษร ประโยค ย่อหน้า และเวลาอ่านโดยประมาณ",
    category: "productivity",
    icon: "TextCursorInput",
    keywords: ["นับคำ", "นับตัวอักษร", "word count", "นักเขียน", "คอนเทนต์", "seo"],
    isPopular: true,
    isNew: true,
    relatedTools: ["text-cleaner", "diff-checker", "regex-tester"],
    howTo: ["พิมพ์หรือวางข้อความในช่อง", "ดูสถิติที่อัปเดตทันที", "คัดลอกหรือล้างข้อความเมื่อต้องการ"],
    example: "Meaw Tools ช่วยนับคำภาษาไทยได้โดยไม่ต้องส่งข้อมูลออกจาก Browser",
    caution: "จำนวนคำใช้กฎการแบ่งคำของ Browser ซึ่งอาจต่างจากข้อกำหนดเฉพาะของสำนักพิมพ์บางแห่ง",
    faq: commonFaq,
  },
  {
    slug: "text-cleaner",
    name: "Text Cleaner",
    thaiName: "จัดระเบียบข้อความ",
    shortDescription: "ล้างช่องว่าง บรรทัดว่าง และรายการซ้ำ",
    description: "จัดระเบียบข้อความจากเอกสาร แชต หรือสเปรดชีต ด้วยตัวเลือกตัดช่องว่าง ยุบช่องว่าง ลบบรรทัดว่าง และลบบรรทัดซ้ำ",
    category: "productivity",
    icon: "ListFilter",
    keywords: ["จัดข้อความ", "ลบช่องว่าง", "ลบบรรทัดซ้ำ", "clean text", "งานเอกสาร"],
    isPopular: false,
    isNew: true,
    relatedTools: ["word-counter", "diff-checker", "regex-tester"],
    howTo: ["วางข้อความต้นฉบับ", "เลือกกฎการจัดระเบียบ", "กดจัดระเบียบแล้วคัดลอกผลลัพธ์"],
    example: "  สินค้า A   100 บาท  \n\nสินค้า A   100 บาท",
    caution: "การลบบรรทัดซ้ำจะเก็บเฉพาะบรรทัดแรก และพิจารณาตัวพิมพ์เล็ก-ใหญ่ตามจริง",
    faq: commonFaq,
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    thaiName: "คำนวณเปอร์เซ็นต์",
    shortDescription: "หาเปอร์เซ็นต์ สัดส่วน และอัตราการเปลี่ยนแปลง",
    description: "คำนวณ X% ของจำนวน เปลี่ยนจำนวนเป็นเปอร์เซ็นต์ และหาเปอร์เซ็นต์เพิ่มหรือลด เหมาะกับงานขาย บัญชี และการวิเคราะห์ทั่วไป",
    category: "calculator",
    icon: "Percent",
    keywords: ["เปอร์เซ็นต์", "ส่วนลด", "percentage", "ยอดขาย", "เพิ่มขึ้น", "ลดลง"],
    isPopular: true,
    isNew: true,
    relatedTools: ["unit-converter", "date-calculator", "word-counter"],
    howTo: ["เลือกรูปแบบการคำนวณ", "กรอกตัวเลขสองช่อง", "กดคำนวณและตรวจสูตรใต้ผลลัพธ์"],
    example: "15% ของ 200 = 30",
    caution: "ผลลัพธ์อัตราเปลี่ยนแปลงใช้ค่าสัมบูรณ์ของค่าเริ่มต้นเป็นฐาน และไม่รองรับค่าเริ่มต้นเป็นศูนย์",
    faq: commonFaq,
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    thaiName: "แปลงหน่วย",
    shortDescription: "แปลงความยาว น้ำหนัก อุณหภูมิ พื้นที่ และข้อมูล",
    description: "แปลงหน่วยที่ใช้ในชีวิตประจำวันและการทำงาน รวมหน่วยพื้นที่ไทยอย่างไร่ งาน และตารางวา พร้อมหน่วยดิจิทัลฐาน 10 และฐาน 2",
    category: "calculator",
    icon: "Ruler",
    keywords: ["แปลงหน่วย", "ไร่", "ตารางวา", "กิโลกรัม", "เมตร", "unit converter"],
    isPopular: true,
    isNew: true,
    relatedTools: ["percentage-calculator", "date-calculator", "timestamp-converter"],
    howTo: ["เลือกประเภทหน่วย", "กรอกค่าและเลือกหน่วยต้นทาง", "เลือกหน่วยปลายทางเพื่อดูผลลัพธ์ทันที"],
    example: "10 เมตร = 32.8083989501 ฟุต",
    caution: "ค่าที่แสดงถูกปัดเพื่อให้อ่านง่าย ไม่ควรใช้แทนเครื่องมือสอบเทียบในงานที่ต้องการความเที่ยงตรงสูง",
    faq: commonFaq,
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    thaiName: "คำนวณวันและระยะเวลา",
    shortDescription: "หาระยะห่าง บวกหรือลบวัน และนับวันทำงาน",
    description: "คำนวณจำนวนวันระหว่างสองวันที่ หรือบวกและลบวันจากวันที่ตั้งต้น พร้อมตัวเลือกนับเฉพาะวันจันทร์ถึงศุกร์",
    category: "calculator",
    icon: "CalendarDays",
    keywords: ["คำนวณวัน", "วันทำงาน", "date calculator", "ระยะเวลา", "กำหนดส่ง", "hr"],
    isPopular: true,
    isNew: true,
    relatedTools: ["timestamp-converter", "percentage-calculator", "unit-converter"],
    howTo: ["เลือกหาระยะห่างหรือบวก/ลบวัน", "กรอกวันที่และจำนวนวันที่เกี่ยวข้อง", "อ่านผลลัพธ์และหมายเหตุการนับวันทำงาน"],
    example: "2026-08-02 + 30 วัน = 2026-09-01",
    caution: "โหมดวันทำงานไม่นับเสาร์-อาทิตย์ แต่ยังไม่หักวันหยุดนักขัตฤกษ์ของแต่ละประเทศหรือองค์กร",
    faq: commonFaq,
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF Converter",
    thaiName: "แปลง JPG เป็น PDF",
    shortDescription: "รวมรูป JPG และ PNG หลายไฟล์เป็น PDF",
    description: "เรียงและรวมรูป JPG หรือ PNG เป็นไฟล์ PDF พร้อมเลือกขนาดหน้าและระยะขอบ โดยไฟล์ไม่ถูกอัปโหลดออกจากอุปกรณ์",
    category: "media",
    icon: "FileImage",
    keywords: ["แปลง jpg เป็น pdf", "jpg to pdf", "รูปเป็น pdf", "รวมรูป pdf", "png to pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["pdf-to-jpg", "merge-pdf", "image-compressor"],
    howTo: ["เลือกรูป JPG หรือ PNG ได้สูงสุด 20 ไฟล์", "จัดลำดับรูปและเลือกรูปแบบหน้ากระดาษ", "กดสร้าง PDF แล้วดาวน์โหลดไฟล์"],
    example: "photo-01.jpg + photo-02.png → meaw-images.pdf",
    caution: "รองรับไฟล์ละไม่เกิน 10 MB และรวมไม่เกิน 50 MB ควรตรวจทิศทางรูปจากกล้องก่อนสร้าง PDF",
    faq: commonFaq,
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    thaiName: "สร้าง QR Code ฟรี",
    shortDescription: "สร้าง QR Code จากลิงก์หรือข้อความพร้อมดาวน์โหลด",
    description: "สร้าง QR Code จาก URL หรือข้อความ เลือกขนาด สี และระดับการแก้ไขข้อผิดพลาด พร้อมดาวน์โหลด PNG หรือ SVG",
    category: "media",
    icon: "QrCode",
    keywords: ["สร้าง qr code", "qr code generator", "คิวอาร์โค้ด", "qr ฟรี", "ดาวน์โหลด qr"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-pdf", "image-compressor", "url-encoder"],
    howTo: ["วางลิงก์หรือข้อความที่ต้องการ", "เลือกขนาด สี และระดับการแก้ไขข้อผิดพลาด", "กดสร้างแล้วดาวน์โหลดเป็น PNG หรือ SVG"],
    example: "https://meaw-tools.vercel.app",
    caution: "ควรสแกนทดสอบก่อนนำไปพิมพ์จริง และใช้สีพื้นกับสีจุดที่มีความต่างกันชัดเจน",
    faq: commonFaq,
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    thaiName: "คำนวณอายุ",
    shortDescription: "คำนวณอายุเป็นปี เดือน วัน และวันเกิดครั้งถัดไป",
    description: "คำนวณอายุจากวันเกิดถึงวันที่กำหนด แสดงปี เดือน วัน จำนวนวันทั้งหมด และระยะเวลาถึงวันเกิดครั้งถัดไป",
    category: "calculator",
    icon: "CakeSlice",
    keywords: ["คำนวณอายุ", "age calculator", "อายุกี่ปี", "วันเกิด", "นับอายุ"],
    isPopular: true,
    isNew: true,
    relatedTools: ["date-calculator", "timestamp-converter", "percentage-calculator"],
    howTo: ["เลือกวันเดือนปีเกิด", "เลือกวันที่ที่ต้องการใช้อ้างอิงหรือกดวันนี้", "กดคำนวณเพื่อดูอายุและวันเกิดครั้งถัดไป"],
    example: "เกิด 15 มกราคม 2000 — คำนวณ ณ 2 สิงหาคม 2026",
    caution: "ผลลัพธ์ใช้วันที่ปฏิทินบนอุปกรณ์และคำนวณเพื่อข้อมูลทั่วไป ไม่ใช่การรับรองอายุตามข้อกฎหมาย",
    faq: commonFaq,
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    thaiName: "คำนวณดอกเบี้ยเงินกู้",
    shortDescription: "ประมาณค่างวด ดอกเบี้ยรวม และตารางลดต้นลดดอก",
    description: "คำนวณค่างวดเงินกู้แบบลดต้นลดดอกด้วยอัตราคงที่ แสดงดอกเบี้ยรวม ยอดชำระรวม และรายละเอียดเงินต้นกับดอกเบี้ยแต่ละงวด",
    category: "business",
    icon: "Landmark",
    keywords: ["คำนวณดอกเบี้ย", "คำนวณเงินกู้", "loan calculator", "ค่างวด", "ลดต้นลดดอก", "ผ่อนบ้าน"],
    isPopular: true,
    isNew: true,
    relatedTools: ["profit-margin-calculator", "percentage-calculator", "unit-converter"],
    howTo: ["กรอกวงเงินกู้และอัตราดอกเบี้ยต่อปี", "กำหนดระยะเวลาผ่อนเป็นปีหรือเดือน", "กดคำนวณเพื่อดูค่างวดและตารางลดต้นลดดอก"],
    example: "วงเงิน 1,000,000 บาท · ดอกเบี้ย 6% ต่อปี · 20 ปี",
    caution: "ผลลัพธ์เป็นประมาณการจากอัตราคงที่และการชำระตรงเวลาทุกงวด ไม่รวมค่าธรรมเนียม ประกัน ภาษี หรืออัตราที่เปลี่ยนแปลงตามสัญญาจริง",
    faq: [...commonFaq, { question: "ใช้สูตรแบบใด?", answer: "ใช้หลักลดต้นลดดอกแบบชำระเท่ากันทุกเดือน โดยดอกเบี้ยแต่ละงวดคิดจากเงินต้นคงเหลือ" }],
  },
  {
    slug: "thai-income-tax-calculator",
    name: "Thai Income Tax Calculator",
    thaiName: "คำนวณภาษีเงินได้บุคคลธรรมดา",
    shortDescription: "ประมาณภาษีแบบขั้นบันไดจากเงินเดือนหรือเงินได้สุทธิ",
    description: "ประมาณภาษีเงินได้บุคคลธรรมดาไทยจากเงินเดือน หรือกรอกเงินได้สุทธิโดยตรง พร้อมแจกแจงค่าใช้จ่าย ค่าลดหย่อน ภาษีแต่ละขั้น และยอดเทียบภาษีหัก ณ ที่จ่าย",
    category: "business",
    icon: "BadgeDollarSign",
    keywords: ["คำนวณภาษี", "คำนวณภาษีเงินได้บุคคลธรรมดา", "คำนวณภาษีเงินเดือน", "ภาษี 2569", "ภงด 90", "ภงด 91", "tax calculator thailand"],
    isPopular: true,
    isNew: true,
    relatedTools: ["salary-calculator", "loan-calculator", "profit-margin-calculator"],
    howTo: ["เลือกคำนวณจากเงินเดือน หรือกรอกเงินได้สุทธิที่คำนวณมาแล้ว", "กรอกรายได้ ค่าลดหย่อนที่ใช้สิทธิได้ และภาษีหัก ณ ที่จ่าย", "กดคำนวณ แล้วตรวจที่มาของเงินได้สุทธิ ภาษีแต่ละขั้น และยอดคงเหลือ"],
    example: "เงินเดือน 50,000/เดือน · ประกันสังคม 9,000/ปี",
    caution: "เป็นการประมาณการเบื้องต้นสำหรับการวางแผน ไม่ใช่คำแนะนำทางภาษีหรือผลยื่นแบบจริง ไม่ครอบคลุมเงินได้และสิทธิทุกประเภท และผู้ใช้ต้องตรวจสอบกฎหมายกับหลักฐานของปีภาษีจริง",
    faq: [...commonFaq,
      { question: "คิดภาษีแบบขั้นบันไดอย่างไร?", answer: "เงินได้สุทธิแต่ละส่วนถูกคิดตามอัตราของช่วงนั้น ไม่ได้นำเงินได้ทั้งหมดคูณด้วยอัตราสูงสุดที่เข้าเกณฑ์" },
      { question: "ทำไมไม่ใส่ประกันสังคมให้อัตโนมัติ?", answer: "จำนวนที่ใช้สิทธิขึ้นกับยอดที่จ่ายจริงและกติกาของปีภาษี เครื่องมือจึงให้กรอกตามหลักฐานเพื่อลดความเสี่ยงจากข้อมูลที่เปลี่ยนแปลง" },
    ],
  },
  {
    slug: "salary-calculator",
    name: "Salary & Payslip Calculator",
    thaiName: "คำนวณเงินเดือนสุทธิและตรวจสลิป",
    shortDescription: "รวมรายรับ รายการหัก และตรวจยอดรับสุทธิรายเดือน",
    description: "คำนวณเงินเดือนสุทธิจากเงินเดือน OT รายได้อื่น ประกันสังคม กองทุน ภาษี และรายการหัก พร้อม breakdown สำหรับเทียบสลิปจริง โดยไม่สร้างเอกสารรับรองรายได้",
    category: "business",
    icon: "CircleDollarSign",
    keywords: ["คำนวณเงินเดือน", "คำนวณเงินเดือนสุทธิ", "ตรวจสลิปเงินเดือน", "อ่านสลิปเงินเดือน", "คำนวณประกันสังคม", "เงินเดือนสุทธิ", "salary calculator thailand", "net pay calculator"],
    isPopular: true,
    isNew: true,
    relatedTools: ["thai-income-tax-calculator", "loan-calculator", "profit-margin-calculator"],
    howTo: ["กรอกเงินเดือน OT ค่าตำแหน่ง โบนัส หรือรายรับที่จ่ายในเดือนเดียวกัน", "เลือกคำนวณประกันสังคมอัตโนมัติ หรือกรอกยอดหักจริงจากสลิป", "กรอกกองทุน ภาษี และรายการหักอื่น แล้วตรวจรายรับรวม รายการหักรวม และยอดสุทธิ"],
    example: "เงินเดือน 30,000 · OT 2,000 · รายได้อื่น 1,500 · รับสุทธิ 30,925 บาท",
    caution: "ผลลัพธ์ใช้ช่วยตรวจยอดรายเดือน ไม่ใช่สลิปเงินเดือน หนังสือรับรองรายได้ หรือคำวินิจฉัยสิทธิ ประกันสังคมอัตโนมัติอ้างอิงมาตรา 33 ปี 2569–2571 และควรใช้ยอดจริงจากสลิปเมื่อมีความแตกต่าง",
    faq: [...commonFaq,
      { question: "เครื่องมือนี้สร้างสลิปเงินเดือนได้หรือไม่?", answer: "ไม่ เครื่องมือแสดง breakdown สำหรับตรวจยอดเท่านั้น และไม่สร้างเอกสารที่อาจถูกเข้าใจว่าออกโดยนายจ้าง" },
      { question: "ภาษีหัก ณ ที่จ่ายคำนวณให้อัตโนมัติหรือไม่?", answer: "ไม่ เพราะภาษีรายเดือนขึ้นกับรายได้และสิทธิทั้งปี ควรกรอกยอดจากสลิป หรือใช้เครื่องมือภาษีเงินได้บุคคลธรรมดาเพื่อประมาณทั้งปี" },
    ],
  },
  {
    slug: "social-security-pension-calculator",
    name: "Social Security Pension Calculator",
    thaiName: "คำนวณบำนาญประกันสังคม",
    shortDescription: "ประมาณบำนาญ ม.33/ม.39 และตรวจเงื่อนไขเกิดสิทธิ",
    description: "คำนวณประมาณบำนาญชราภาพประกันสังคม มาตรา 33 และมาตรา 39 ด้วยสูตร FAE ปัจจุบัน พร้อมแสดงอัตรา จำนวนเดือนที่ยังขาด และตรวจอายุหรือสถานะเบื้องต้น",
    category: "business",
    icon: "Landmark",
    keywords: ["คำนวณบำนาญ", "คำนวณบำนาญประกันสังคม", "บำนาญชราภาพ", "ประกันสังคม มาตรา 33", "ประกันสังคม มาตรา 39", "เงินชราภาพ", "pension calculator thailand"],
    isPopular: true,
    isNew: true,
    relatedTools: ["salary-calculator", "thai-income-tax-calculator", "loan-calculator"],
    howTo: ["กรอกค่าจ้างเฉลี่ย 60 เดือนสุดท้ายที่ใช้เป็นฐานส่งเงินสมทบ", "กรอกจำนวนเดือนที่ส่งเงินสมทบ อายุ และสถานะความเป็นผู้ประกันตน", "กดคำนวณเพื่อตรวจประมาณบำนาญ สูตร และเงื่อนไขเกิดสิทธิ"],
    example: "ฐานค่าจ้างเฉลี่ย 15,000 บาท · ส่ง 250 เดือน · อัตรา 27.5% · ประมาณ 4,125 บาท/เดือน",
    caution: "เป็นประมาณการสูตร FAE ปัจจุบันสำหรับ ม.33/ม.39 ไม่ใช่การรับรองสิทธิ ไม่คำนวณบำเหน็จหรือ ม.40 และยังไม่ใช้สูตร CARE ซึ่ง ณ วันที่ตรวจทาน 3 สิงหาคม 2569 ยังเป็นร่างที่รอมีผลตามกฎหมาย",
    faq: [...commonFaq,
      { question: "สูตร CARE ใช้คำนวณแล้วหรือยัง?", answer: "ยังไม่ใช้ในเครื่องมือนี้ ร่าง CARE ได้รับความเห็นชอบจาก ครม. เมื่อ 14 กรกฎาคม 2569 แต่กำหนดให้มีผลหลังประกาศในราชกิจจานุเบกษาแล้ว 180 วัน จึงยังใช้สูตร FAE ปัจจุบันตามสถานะที่ตรวจทาน 3 สิงหาคม 2569" },
      { question: "ค่าจ้างเฉลี่ย 60 เดือนคือเงินเดือนล่าสุดหรือไม่?", answer: "ไม่ใช่ ให้นำฐานค่าจ้างที่ใช้ส่งเงินสมทบ 60 เดือนสุดท้ายก่อนสิ้นสุดความเป็นผู้ประกันตนมาเฉลี่ย โดยเฉพาะผู้ที่เคยสลับระหว่างมาตรา 33 และมาตรา 39 ควรตรวจประวัติจริงกับสำนักงานประกันสังคม" },
      { question: "ส่งเงินสมทบไม่ครบ 180 เดือนจะได้อะไร?", answer: "อาจเข้าเกณฑ์เงินบำเหน็จชราภาพแทนบำนาญรายเดือน ยอดขึ้นกับเงินสมทบและผลประโยชน์ตอบแทน เครื่องมือนี้จึงไม่เดายอดบำเหน็จและแนะนำให้ตรวจสิทธิกับสำนักงานประกันสังคม" },
      { question: "ใช้กับผู้ประกันตนมาตรา 40 ได้หรือไม่?", answer: "ไม่ได้ สูตรและสิทธิของมาตรา 40 แตกต่างจากมาตรา 33 และมาตรา 39" },
    ],
  },
  {
    slug: "thai-id-validator",
    name: "Thai ID Checksum Validator",
    thaiName: "ตรวจ checksum เลขบัตรประชาชน",
    shortDescription: "ตรวจโครงสร้าง 13 หลักและเลขตรวจสอบโดยไม่ส่งข้อมูล",
    description: "ตรวจรูปแบบ ประเภทหลักแรก และ checksum ของเลขประจำตัวประชาชนไทยภายใน Browser โดยซ่อนค่าที่กรอกเป็นค่าเริ่มต้น ไม่บันทึกข้อมูล และไม่อ้างว่าเป็นการยืนยันตัวตนกับฐานข้อมูลรัฐ",
    category: "security",
    icon: "BadgeCheck",
    keywords: ["เช็คเลขบัตรประชาชน", "ตรวจสอบเลขบัตรประชาชน", "ตรวจเลขบัตรประชาชน", "เลขบัตรประชาชน", "checksum", "thai id validator"],
    isPopular: true,
    isNew: true,
    relatedTools: ["password-generator", "hash-generator", "jwt-decoder"],
    howTo: ["กรอกเลขประจำตัวประชาชน 13 หลัก โดยใส่ขีดหรือช่องว่างได้", "กดตรวจ checksum เพื่อดูผลรูปแบบ ประเภทหลักแรก และเลขตรวจสอบ", "หากต้องยืนยันบุคคลหรือสถานะบัตร ให้ใช้บริการทางการที่มีสิทธิ์เชื่อมฐานทะเบียน"],
    example: "X-XXXX-XXXXX-XX-X (ซ่อนค่าเริ่มต้น)",
    caution: "ผลผ่านหมายถึงตัวเลขสอดคล้องตามสูตรเท่านั้น ไม่ยืนยันว่าบุคคลมีอยู่จริง บัตรยังใช้งานได้ หรือผู้กรอกเป็นเจ้าของเลข และไม่ควรกรอกบนอุปกรณ์สาธารณะ",
    faq: [...commonFaq,
      { question: "ผลผ่าน checksum ยืนยันตัวตนได้หรือไม่?", answer: "ไม่ได้ checksum ตรวจเพียงความสอดคล้องทางคณิตศาสตร์ การยืนยันตัวตนจริงต้องตรวจข้อมูลเพิ่มเติมและเชื่อมกับระบบทางการที่ได้รับสิทธิ์" },
      { question: "Meaw Tools เก็บเลขที่กรอกไว้หรือไม่?", answer: "ไม่ เครื่องมือประมวลผลใน Browser ไม่ส่งไป Server ไม่บันทึกใน LocalStorage และไม่ใส่เลขลง URL" },
      { question: "ทำไมไม่มีปุ่มสร้างเลขตัวอย่าง?", answer: "เลขประจำตัวประชาชนเป็นข้อมูลส่วนบุคคลสำคัญ เครื่องมือนี้จึงไม่สร้างหรือแสดงเลขเต็มที่ผ่าน checksum เพื่อจำกัดการนำไปใช้ผิดวัตถุประสงค์" },
    ],
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    thaiName: "คำนวณ BMI",
    shortDescription: "คำนวณดัชนีมวลกายและช่วงน้ำหนักสำหรับผู้ใหญ่",
    description: "คำนวณ BMI จากน้ำหนักและส่วนสูง พร้อมแสดงกลุ่มตามเกณฑ์ผู้ใหญ่ขององค์การอนามัยโลกและช่วงน้ำหนักอ้างอิง",
    category: "calculator",
    icon: "Activity",
    keywords: ["คำนวณ bmi", "ค่า bmi", "bmi calculator", "ดัชนีมวลกาย", "น้ำหนักปกติ"],
    isPopular: true,
    isNew: true,
    relatedTools: ["age-calculator", "unit-converter", "date-calculator"],
    howTo: ["กรอกน้ำหนักเป็นกิโลกรัม", "กรอกส่วนสูงเป็นเซนติเมตร", "กดคำนวณและอ่านผลพร้อมข้อจำกัดของ BMI"],
    example: "น้ำหนัก 70 กก. · ส่วนสูง 175 ซม. · BMI ≈ 22.9",
    caution: "เกณฑ์นี้ใช้กับผู้ใหญ่อายุมากกว่า 20 ปีและเป็นเพียงการคัดกรอง ไม่ใช่การวินิจฉัยหรือคำแนะนำทางการแพทย์",
    faq: [...commonFaq, { question: "เด็กและวัยรุ่นใช้ผลนี้ได้หรือไม่?", answer: "ไม่ควรใช้เกณฑ์ผู้ใหญ่โดยตรง เพราะ BMI ของผู้มีอายุ 0–19 ปีต้องพิจารณาอายุและเพศด้วยกราฟการเจริญเติบโต" }],
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit & Margin Calculator",
    thaiName: "คำนวณกำไรและ Margin",
    shortDescription: "หากำไร ขาดทุน Margin และ Markup จากต้นทุน",
    description: "คำนวณยอดขาย ต้นทุน กำไรหรือขาดทุน พร้อมแยก Margin และ Markup อย่างชัดเจนสำหรับร้านค้าและเจ้าของธุรกิจ",
    category: "business",
    icon: "BadgeDollarSign",
    keywords: ["คำนวณกำไร", "margin calculator", "markup", "กำไรขั้นต้น", "ราคาขาย", "ต้นทุน"],
    isPopular: true,
    isNew: true,
    relatedTools: ["percentage-calculator", "loan-calculator", "unit-converter"],
    howTo: ["กรอกต้นทุนและราคาขายต่อชิ้น", "กำหนดจำนวนสินค้าที่ต้องการคำนวณ", "ดูยอดขาย กำไร Margin และ Markup"],
    example: "ต้นทุน 60 บาท · ราคาขาย 100 บาท · Margin 40% · Markup 66.67%",
    caution: "ผลลัพธ์ยังไม่รวม VAT ค่าขนส่ง ค่าธรรมเนียมแพลตฟอร์ม ค่าแรง และต้นทุนแฝง เว้นแต่รวมไว้ในต้นทุนต่อชิ้นแล้ว",
    faq: [...commonFaq, { question: "Margin ต่างจาก Markup อย่างไร?", answer: "Margin เปรียบเทียบกำไรกับราคาขาย ส่วน Markup เปรียบเทียบกำไรกับต้นทุน จึงได้เปอร์เซ็นต์ต่างกัน" }],
  },
  {
    slug: "quotation-generator",
    name: "Quotation Generator",
    thaiName: "สร้างใบเสนอราคา PDF",
    shortDescription: "สร้างใบเสนอราคาภาษาไทยพร้อม VAT และดาวน์โหลด PDF ฟรี",
    description: "สร้างใบเสนอราคาสำหรับร้านค้า ฟรีแลนซ์ และธุรกิจรายย่อย พร้อมข้อมูลผู้ขาย ลูกค้า รายการสินค้า ส่วนลด VAT ยอดเป็นตัวอักษรไทย และ PDF A4 โดยประมวลผลใน Browser",
    category: "business",
    icon: "ReceiptText",
    keywords: ["ใบเสนอราคา", "ตัวอย่างใบเสนอราคา", "แบบฟอร์มใบเสนอราคา", "สร้างใบเสนอราคา", "ใบเสนอราคา pdf", "quotation generator", "quotation template", "โปรแกรมใบเสนอราคา"],
    isPopular: true,
    isNew: true,
    relatedTools: ["profit-margin-calculator", "thai-income-tax-calculator", "jpg-to-pdf"],
    howTo: ["กรอกข้อมูลผู้เสนอราคา ลูกค้า เลขที่เอกสาร และวันที่", "เพิ่มสินค้าและบริการ กำหนดส่วนลด รูปแบบ VAT และเงื่อนไข", "ตรวจตัวอย่างแล้วกดสร้างและดาวน์โหลด PDF ภาษาไทย"],
    example: "เว็บไซต์ 25,000 บาท + ถ่ายภาพ 7,000 บาท + ดูแลระบบ 7,500 บาท - ส่วนลด 1,000 บาท + VAT 7%",
    caution: "ใบเสนอราคาไม่ใช่ใบเสร็จ ใบกำกับภาษี หลักฐานรับเงิน หรือลายเซ็นดิจิทัล ควรตรวจข้อมูลและอัตราภาษีกับผู้ทำบัญชีก่อนใช้งานจริง",
    faq: [...commonFaq,
      { question: "PDF รองรับภาษาไทยหรือไม่?", answer: "รองรับ เครื่องมือฝังฟอนต์ Sarabun ลงใน PDF และโหลดฟอนต์เฉพาะเมื่อกดสร้างไฟล์ แต่อักขระ Emoji บางชนิดอาจไม่แสดง" },
      { question: "VAT แบบรวมแล้วกับบวกเพิ่มต่างกันอย่างไร?", answer: "แบบบวกเพิ่มจะคำนวณ VAT เพิ่มจากยอดหลังส่วนลด ส่วนแบบรวมแล้วจะแยกยอด VAT ออกจากราคารวมโดยไม่เพิ่มยอดสุทธิ" },
      { question: "ใช้แทนใบกำกับภาษีได้หรือไม่?", answer: "ไม่ได้ เครื่องมือนี้สร้างเฉพาะใบเสนอราคาและไม่ได้ตรวจเงื่อนไขเอกสารภาษีตามกิจการของคุณ" },
    ],
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    thaiName: "แปลง HEIC เป็น JPG ออนไลน์",
    shortDescription: "แปลงรูป HEIC/HEIF จาก iPhone เป็น JPG หลายไฟล์ภายใน Browser",
    description: "แปลง HEIC และ HEIF เป็น JPG โดยใช้ WebAssembly ภายใน Browser เลือกคุณภาพและขนาดภาพ รองรับหลายไฟล์ พร้อมดาวน์โหลดเป็น ZIP โดยไม่อัปโหลดรูปขึ้น Server",
    category: "media",
    icon: "Images",
    keywords: ["heic to jpg", "แปลง heic เป็น jpg", "convert heic to jpg", "heic converter", "heif to jpg", "รูป iphone เป็น jpg"],
    isPopular: true,
    isNew: true,
    relatedTools: ["png-to-jpg", "image-compressor", "jpg-to-pdf"],
    howTo: ["เลือกไฟล์ HEIC หรือ HEIF จาก iPhone ได้สูงสุด 10 ไฟล์", "เลือกขนาดด้านยาวและคุณภาพ JPG แล้วกดแปลง", "ตรวจภาพตัวอย่างและดาวน์โหลด JPG หรือ ZIP"],
    example: "IMG_1001.HEIC · 4032 × 3024 px → IMG_1001.jpg · สูงสุด 4096 px · คุณภาพ 90%",
    caution: "JPG ใหม่ไม่เก็บ EXIF, GPS หรือ metadata เดิม และใช้เฉพาะภาพหลักของ Live Photo/Burst วิดีโอ เสียง depth map และการแก้ไขใน Photos จะไม่ถูกส่งต่อ ควรเก็บ HEIC ต้นฉบับไว้เสมอ",
    faq: [...commonFaq,
      { question: "รองรับหลายไฟล์พร้อมกันหรือไม่?", answer: "รองรับสูงสุด 10 ไฟล์ต่อครั้ง ไฟล์ละไม่เกิน 20 MB และรวมไม่เกิน 60 MB โดยดาวน์โหลดหลายผลลัพธ์เป็น ZIP ได้" },
      { question: "รูปถูกส่งขึ้น Server หรือไม่?", answer: "ไม่ ไฟล์ถูกถอดรหัสด้วย WebAssembly และสร้าง JPG ภายใน Browser ของอุปกรณ์คุณ" },
      { question: "EXIF และพิกัด GPS ยังอยู่หรือไม่?", answer: "ไม่ เครื่องมือสร้าง JPG ใหม่จากข้อมูลพิกเซล จึงไม่คัดลอก EXIF, GPS หรือ metadata เดิม ช่วยลดข้อมูลส่วนตัวแต่ควรเก็บต้นฉบับหากยังต้องใช้ข้อมูลเหล่านั้น" },
      { question: "รองรับ Live Photo และ Burst หรือไม่?", answer: "เครื่องมือใช้ภาพหลักเพียงภาพเดียว ไม่รวมวิดีโอ เสียง ภาพเสริม depth map หรือภาพอื่นใน Burst" },
      { question: "ทำไมการแปลงไฟล์แรกอาจใช้เวลานาน?", answer: "Browser ต้องโหลดตัวถอดรหัส WebAssembly ประมาณ 1 MB เมื่อกดแปลงครั้งแรก จากนั้นจึงถอดรหัสภาพทีละไฟล์เพื่อลดการใช้หน่วยความจำ" },
    ],
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG Converter",
    thaiName: "แปลง PNG เป็น JPG",
    shortDescription: "แปลง PNG หรือ WebP เป็น JPG พร้อมเลือกพื้นหลัง",
    description: "แปลงไฟล์ PNG หรือ WebP เป็น JPG ภายใน Browser เลือกสีแทนพื้นโปร่งใสและระดับคุณภาพก่อนดาวน์โหลดได้ โดยไม่อัปโหลดรูปขึ้น Server",
    category: "media",
    icon: "FileImage",
    keywords: ["แปลง png เป็น jpg", "png to jpg", "แปลง webp เป็น jpg", "webp to jpg", "แปลงรูปเป็น jpg", "เปลี่ยนไฟล์รูป"],
    isPopular: true,
    isNew: true,
    relatedTools: ["image-compressor", "jpg-to-pdf", "qr-code-generator"],
    howTo: ["เลือกไฟล์ PNG หรือ WebP ขนาดไม่เกิน 10 MB", "เลือกสีพื้นหลังสำหรับส่วนที่โปร่งใสและกำหนดคุณภาพ JPG", "กดแปลง ตรวจภาพตัวอย่าง แล้วดาวน์โหลดไฟล์"],
    example: "product-transparent.png → product-transparent-converted.jpg",
    caution: "JPG ไม่รองรับพื้นโปร่งใส พื้นที่โปร่งใสจะถูกแทนด้วยสีที่เลือก และการแปลงผ่าน Canvas มักไม่เก็บ metadata เดิม",
    faq: [...commonFaq, { question: "ทำไมพื้นโปร่งใสจึงกลายเป็นสีขาว?", answer: "JPG ไม่มีช่องความโปร่งใส เครื่องมือจึงเติมสีพื้นหลังที่เลือกไว้ก่อนสร้างไฟล์ JPG" }],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor & Resizer",
    thaiName: "ลดขนาดและบีบอัดรูป",
    shortDescription: "ย่อความละเอียดและลดขนาดไฟล์ JPG, PNG, WebP",
    description: "ลดขนาดรูปด้วยการจำกัดความกว้างและความสูงโดยรักษาสัดส่วน พร้อมแปลงเป็น WebP, JPG หรือ PNG และปรับคุณภาพได้ภายใน Browser",
    category: "media",
    icon: "Images",
    keywords: ["ลดขนาดรูป", "บีบอัดรูป", "image compressor", "image resizer", "ย่อรูป", "ลดขนาดไฟล์รูป", "แปลงรูป webp"],
    isPopular: true,
    isNew: true,
    relatedTools: ["png-to-jpg", "jpg-to-pdf", "qr-code-generator"],
    howTo: ["เลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 10 MB", "กำหนดขนาดสูงสุด รูปแบบผลลัพธ์ และระดับคุณภาพ", "กดบีบอัด เปรียบเทียบขนาด แล้วดาวน์โหลดไฟล์"],
    example: "4000 × 3000 px · 4.8 MB → WebP 1920 × 1440 px",
    caution: "ขนาดไฟล์ขึ้นกับรายละเอียดของรูปและรูปแบบผลลัพธ์ บางกรณี PNG หรือรูปที่บีบอัดมาแล้วอาจมีขนาดเพิ่มขึ้น ควรตรวจภาพก่อนใช้งานจริง",
    faq: [...commonFaq, { question: "เครื่องมือยืดหรือบีบสัดส่วนภาพหรือไม่?", answer: "ไม่ เครื่องมือรักษาอัตราส่วนเดิมและลดให้พอดีกับทั้งความกว้างและความสูงที่กำหนด โดยไม่ขยายเกินต้นฉบับ" }],
  },
  {
    slug: "background-remover",
    name: "AI Background Remover",
    thaiName: "ลบพื้นหลังรูปออนไลน์",
    shortDescription: "ลบพื้นหลัง JPG, PNG หรือ WebP ด้วย AI ในอุปกรณ์",
    description: "ลบพื้นหลังรูปสินค้า บุคคล สัตว์ หรือวัตถุเป็น PNG โปร่งใสด้วย AI ที่ทำงานภายใน Browser รูปไม่ถูกอัปโหลดขึ้น Server และไม่มีลายน้ำ",
    category: "media",
    icon: "ImageOff",
    keywords: ["ลบพื้นหลัง", "ลบพื้นหลังรูป", "ลบพื้นหลังออนไลน์", "background remover", "remove background", "รูปพื้นหลังโปร่งใส", "ตัดพื้นหลัง", "png โปร่งใส"],
    isPopular: true,
    isNew: true,
    relatedTools: ["image-compressor", "png-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 10 MB และ 16 ล้านพิกเซล", "กดลบพื้นหลังและรอ AI ประมวลผลในอุปกรณ์", "ตรวจขอบตัวแบบบนพื้นสีต่าง ๆ แล้วดาวน์โหลด PNG โปร่งใส"],
    example: "product.jpg → product-no-background.png",
    caution: "ครั้งแรกต้องดาวน์โหลด AI Runtime และโมเดลประมาณ 15–20 MB ผลลัพธ์อาจคลาดเคลื่อนกับพื้นหลังซับซ้อน กระจก เงา เส้นผมละเอียด หรือหลายวัตถุ ควรตรวจภาพก่อนใช้งานจริง",
    faq: [
      ...commonFaq,
      { question: "ทำไมครั้งแรกจึงใช้เวลานาน?", answer: "Browser ต้องดาวน์โหลด ONNX Runtime และโมเดล U-2-Netp ก่อน เมื่อดาวน์โหลดสำเร็จ Browser จะเก็บไฟล์ไว้ใน cache เพื่อให้ครั้งถัดไปเร็วขึ้น" },
      { question: "รูปถูกส่งไปให้ AI ภายนอกหรือไม่?", answer: "ไม่ โมเดลถูกดาวน์โหลดมาให้ Browser ประมวลผลรูปในอุปกรณ์ของคุณ ไม่มี API ของ Meaw Tools รับหรือบันทึกไฟล์รูป" },
      { question: "ลบพื้นหลังได้แม่นทุกภาพหรือไม่?", answer: "ไม่ โมเดลขนาดเล็กเหมาะกับตัวแบบเด่นชัดบนพื้นหลังที่แยกง่าย ขอบผม ขน วัตถุโปร่งใส และฉากซับซ้อนอาจต้องแก้ต่อในโปรแกรมแต่งภาพ" },
    ],
  },
  {
    slug: "color-picker",
    name: "Color Picker & Contrast Checker",
    thaiName: "เลือกสีและตรวจ Contrast",
    shortDescription: "แปลง HEX, RGB, HSL พร้อมตรวจ WCAG Contrast",
    description: "เลือกและแปลงค่าสีระหว่าง HEX, RGB และ HSL สร้างเฉดสีอัตโนมัติ พร้อมตรวจอัตราส่วน Contrast ตามเกณฑ์ WCAG AA และ AAA",
    category: "developer",
    icon: "Palette",
    keywords: ["color picker", "เลือกสี", "รหัสสี", "แปลง hex rgb", "contrast checker", "wcag contrast", "color palette"],
    isPopular: true,
    isNew: true,
    relatedTools: ["image-compressor", "qr-code-generator", "percentage-calculator"],
    howTo: ["เลือกหรือกรอกรหัสสีข้อความและสีพื้นหลัง", "ดู Preview, ค่าสี HEX/RGB/HSL และอัตราส่วน Contrast", "คัดลอกค่าสี CSS หรือเฉดสีที่สร้างให้อัตโนมัติ"],
    example: "Foreground #0F9F8F · Background #FFFFFF · Contrast 3.29:1",
    caution: "Contrast ที่ผ่านเกณฑ์เป็นเพียงส่วนหนึ่งของ Accessibility ควรตรวจขนาดตัวอักษร สถานะ focus และการใช้งานจริงร่วมด้วย",
    faq: [...commonFaq, { question: "WCAG AA ต้องมี Contrast เท่าใด?", answer: "ข้อความขนาดปกติต้องมีอย่างน้อย 4.5:1 ส่วนข้อความขนาดใหญ่และองค์ประกอบ UI ใช้เกณฑ์อย่างน้อย 3:1" }],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    thaiName: "สร้างรหัสผ่านสุ่ม",
    shortDescription: "สร้างรหัสผ่านแข็งแรงด้วย Web Crypto",
    description: "สร้างรหัสผ่านสุ่ม 1–20 รายการ เลือกความยาว ตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก ตัวเลข สัญลักษณ์ และตัดตัวอักษรที่มองคล้ายกันได้",
    category: "security",
    icon: "ShieldEllipsis",
    keywords: ["password generator", "สร้างรหัสผ่าน", "สุ่มรหัสผ่าน", "strong password", "random password", "รหัสผ่าน 16 ตัว"],
    isPopular: true,
    isNew: true,
    relatedTools: ["hash-generator", "uuid-generator", "jwt-decoder"],
    howTo: ["กำหนดความยาวและจำนวนรหัสผ่าน", "เลือกชุดตัวอักษรและเปิดการตัดตัวที่มองคล้ายกัน", "กดสร้างแล้วคัดลอกรหัสผ่านที่ต้องการ"],
    example: "16 ตัวอักษร · A–Z · a–z · 0–9 · สัญลักษณ์ · ตัด i I l L 1 o O 0",
    caution: "อย่าใช้รหัสผ่านเดียวกันหลายบริการ ควรจัดเก็บด้วย Password Manager และเปิด MFA เมื่อบริการรองรับ",
    faq: [...commonFaq, { question: "รหัสผ่านถูกส่งไปที่ Server หรือไม่?", answer: "ไม่ รหัสผ่านสร้างด้วย Web Crypto ภายใน Browser และไม่ถูกบันทึกโดย Meaw Tools" }],
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    thaiName: "สุ่มตัวเลข",
    shortDescription: "สุ่มจำนวนเต็มแบบซ้ำหรือไม่ซ้ำด้วย Web Crypto",
    description: "สุ่มจำนวนเต็มตามช่วงที่กำหนดได้สูงสุด 1,000 รายการ เลือกไม่ให้ซ้ำ เรียงผลลัพธ์ และใช้ตัวเลือกด่วนสำหรับลูกเต๋า หัวก้อย หรือจับฉลาก",
    category: "calculator",
    icon: "Dices",
    keywords: ["random number generator", "สุ่มตัวเลข", "โปรแกรมสุ่มเลข", "จับฉลาก", "ลูกเต๋าออนไลน์", "random picker"],
    isPopular: true,
    isNew: true,
    relatedTools: ["random-wheel", "percentage-calculator", "uuid-generator"],
    howTo: ["กำหนดค่าต่ำสุด ค่าสูงสุด และจำนวนผลลัพธ์", "เลือกว่าจะห้ามซ้ำและเรียงตัวเลขหรือไม่", "กดสุ่มแล้วคัดลอกหรือดาวน์โหลดผลลัพธ์"],
    example: "ช่วง 1–100 · 5 รายการ · ไม่ซ้ำ · เรียงจากน้อยไปมาก",
    caution: "เหมาะกับเกม ตัวอย่าง และการจับฉลากทั่วไป ไม่ใช่ระบบรับรองผลสำหรับการพนัน การเงิน หรือรางวัลมูลค่าสูง",
    faq: [...commonFaq, { question: "สุ่มด้วย Math.random หรือไม่?", answer: "ไม่ เครื่องมือใช้ Web Crypto และลด modulo bias เพื่อให้แต่ละค่าในช่วงมีโอกาสใกล้เคียงกัน" }],
  },
  {
    slug: "random-wheel",
    name: "Random Wheel",
    thaiName: "วงล้อสุ่มชื่อ",
    shortDescription: "หมุนวงล้อสุ่มชื่อ ตัวเลือก หรือของรางวัลด้วย Web Crypto",
    description: "สร้างวงล้อสุ่มจากรายชื่อ 2–100 รายการ ตัดชื่อซ้ำ นำผู้ชนะออกหลังสุ่ม และดูประวัติผลลัพธ์ เหมาะกับห้องเรียน กิจกรรม และการจับฉลากทั่วไป",
    category: "calculator",
    icon: "RefreshCw",
    keywords: ["วงล้อสุ่ม", "สุ่มชื่อ", "วงล้อสุ่มชื่อ", "wheel of names", "random wheel", "จับฉลากออนไลน์", "สุ่มรายชื่อ", "วงล้อจับฉลาก"],
    isPopular: true,
    isNew: true,
    relatedTools: ["random-number-generator", "password-generator", "percentage-calculator"],
    howTo: ["กรอกชื่อหรือตัวเลือกหนึ่งรายการต่อหนึ่งบรรทัด", "เลือกว่าจะตัดรายการซ้ำและนำผู้ชนะออกหลังสุ่มหรือไม่", "กดหมุนวงล้อ แล้วดูผลและประวัติการสุ่ม"],
    example: "มะลิ · สมชาย · น้ำฝน · ต้นกล้า → หมุนเพื่อเลือก 1 รายการ",
    caution: "เหมาะกับกิจกรรมทั่วไป ไม่ใช่ระบบรับรองผลสำหรับการพนัน การเงิน หรือรางวัลมูลค่าสูง",
    faq: [...commonFaq, { question: "ผลการหมุนสุ่มอย่างไร?", answer: "เครื่องมือใช้ Web Crypto เลือกลำดับผู้ชนะและคำนวณมุมที่วงล้อต้องหมุน โดยไม่ส่งรายชื่อออกจาก Browser" }],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG Converter",
    thaiName: "แปลง PDF เป็น JPG",
    shortDescription: "แปลงหน้า PDF เป็นภาพ JPG พร้อมเลือกหน้าและคุณภาพ",
    description: "แปลงหน้า PDF เป็นภาพ JPG ความละเอียดสูงภายใน Browser เลือกเฉพาะหน้า กำหนดคุณภาพ และดาวน์โหลดหลายหน้าเป็น ZIP ได้โดยไม่อัปโหลดเอกสาร",
    category: "media",
    icon: "FileDown",
    keywords: ["pdf to jpg", "แปลง pdf เป็น jpg", "pdf เป็นรูป", "pdf to image", "แปลง pdf เป็นภาพ", "pdf เป็น jpeg"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-pdf", "merge-pdf", "split-pdf"],
    howTo: ["เลือก PDF ขนาดไม่เกิน 30 MB", "ระบุหน้าที่ต้องการ เช่น 1,3-5 แล้วเลือกความละเอียดและคุณภาพ", "กดแปลงเพื่อดาวน์โหลด JPG หรือ ZIP"],
    example: "catalog.pdf หน้า 1-3 → catalog-page-1.jpg + ZIP",
    caution: "รองรับสูงสุด 20 หน้าต่อครั้ง ภาพผลลัพธ์ไม่มีข้อความที่เลือกได้ ลิงก์ หรือ metadata ของ PDF เดิม",
    faq: [...commonFaq, { question: "ทำไมหลายหน้าจึงได้ไฟล์ ZIP?", answer: "เพื่อให้ดาวน์โหลดภาพทุกหน้าได้ในครั้งเดียว ระบบจะรวม JPG หลายไฟล์เป็น ZIP ภายใน Browser" }],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    thaiName: "รวม PDF ออนไลน์",
    shortDescription: "เรียงและรวม PDF หลายไฟล์เป็นเอกสารเดียว",
    description: "รวม PDF ได้สูงสุด 10 ไฟล์ จัดลำดับก่อนสร้างเอกสารใหม่ และดาวน์โหลดได้ทันทีโดยไฟล์ไม่ออกจาก Browser",
    category: "media",
    icon: "Files",
    keywords: ["merge pdf", "รวม pdf", "รวมไฟล์ pdf", "ต่อ pdf", "combine pdf", "รวมเอกสาร"],
    isPopular: true,
    isNew: true,
    relatedTools: ["split-pdf", "pdf-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือก PDF อย่างน้อย 2 ไฟล์", "ใช้ปุ่มขึ้นลงเพื่อจัดลำดับ", "กดรวมและดาวน์โหลด PDF ใหม่"],
    example: "invoice.pdf + receipt.pdf → meaw-merged.pdf",
    caution: "ฟอร์ม ลิงก์ bookmark และโครงสร้างพิเศษบางชนิดอาจทำงานต่างจากต้นฉบับ ควรตรวจไฟล์ใหม่ก่อนใช้งานจริง",
    faq: [...commonFaq, { question: "รวมได้กี่ไฟล์?", answer: "สูงสุด 10 ไฟล์ ไฟล์ละไม่เกิน 30 MB และขนาดรวมไม่เกิน 60 MB ต่อครั้ง" }],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    thaiName: "แยกหน้า PDF",
    shortDescription: "แยกช่วงหน้า PDF เป็นไฟล์ใหม่หลายชุด",
    description: "แยก PDF ตามช่วงหน้า เช่น 1-3,4-6,8 โดยแต่ละช่วงสร้างเป็นไฟล์ใหม่และดาวน์โหลดหลายไฟล์รวมเป็น ZIP ภายใน Browser",
    category: "media",
    icon: "Scissors",
    keywords: ["split pdf", "แยก pdf", "แยกหน้า pdf", "ตัด pdf", "extract pdf pages", "แบ่ง pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["merge-pdf", "pdf-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือก PDF ขนาดไม่เกิน 30 MB", "ระบุช่วงหน้าโดยใช้ comma คั่นแต่ละไฟล์ เช่น 1-3,4-6,8", "กดแยกเพื่อดาวน์โหลด PDF หรือ ZIP"],
    example: "report.pdf · 1-3,4-6,8 → PDF 3 ไฟล์",
    caution: "ไม่รองรับ PDF ที่ล็อกด้วยรหัสผ่าน และการระบุหน้าต้องไม่เกินจำนวนหน้าจริงของเอกสาร",
    faq: [...commonFaq, { question: "จะสร้าง PDF แยกทีละหน้าได้อย่างไร?", answer: "กรอกหมายเลขหน้าแยกด้วย comma เช่น 1,2,3,4 แต่ละหมายเลขจะเป็น PDF คนละไฟล์" }],
  },
  {
    slug: "pdf-organizer",
    name: "PDF Organizer",
    thaiName: "ลบ หมุน และเรียงหน้า PDF",
    shortDescription: "จัดหน้า PDF ด้วยภาพตัวอย่างแบบลากเรียงโดยไม่อัปโหลดไฟล์",
    description: "ดูตัวอย่างทุกหน้าแล้วลบ หมุน และเรียงหน้า PDF ใหม่ด้วยการลากหรือปุ่มที่รองรับมือถือ ประมวลผลและสร้างไฟล์ใหม่ภายใน Browser โดยไม่ส่งเอกสารไป Server",
    category: "media",
    icon: "ListFilter",
    keywords: ["ลบหน้า pdf", "หมุน pdf", "เรียงหน้า pdf", "จัดหน้า pdf", "จัดระเบียบ pdf", "pdf organizer", "delete pdf pages", "rotate pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["sign-pdf", "merge-pdf", "split-pdf"],
    howTo: ["เลือก PDF ไม่เกิน 30 MB และรอระบบสร้างภาพตัวอย่าง", "ลากหน้า หรือใช้ปุ่มลูกศร หมุน และลบใต้การ์ดแต่ละหน้า", "กดจัดหน้าและดาวน์โหลด PDF แล้วเปิดตรวจไฟล์ใหม่ก่อนส่งงาน"],
    example: "PDF 5 หน้า · หมุนหน้า 1 · ลบหน้า 2 · เรียงหน้าใหม่",
    caution: "การแก้ไขอาจทำให้ลายเซ็นดิจิทัลเดิมไม่ผ่านการตรวจสอบ และฟอร์ม bookmark หรือลิงก์บางชนิดอาจเปลี่ยนแปลง ไม่รองรับ PDF ที่มีรหัสผ่านและจำกัด 100 หน้า",
    faq: [...commonFaq,
      { question: "ไฟล์ PDF ถูกอัปโหลดหรือไม่?", answer: "ไม่ การอ่านภาพตัวอย่าง การจัดหน้า และการสร้างไฟล์ใหม่เกิดใน Browser ของอุปกรณ์คุณ" },
      { question: "รองรับ PDF ที่มีลายเซ็นดิจิทัลหรือไม่?", answer: "เปิดและจัดหน้าได้ในบางกรณี แต่การเปลี่ยนแปลงเอกสารอาจทำให้ลายเซ็นเดิมไม่ผ่านการตรวจสอบ จึงไม่ควรใช้กับเอกสารที่ต้องรักษาสถานะลายเซ็น" },
      { question: "ทำไมจำกัด 100 หน้า?", answer: "เครื่องมือต้องสร้างภาพตัวอย่างทุกหน้าในหน่วยความจำของ Browser ขีดจำกัดนี้ช่วยลดโอกาสที่แท็บจะค้างบนมือถือหรือเครื่องที่มี RAM น้อย" },
    ],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    thaiName: "เซ็น PDF ออนไลน์",
    shortDescription: "วาดหรืออัปโหลดลายเซ็นแล้ววางบน PDF โดยไม่ส่งเอกสารขึ้น Server",
    description: "เซ็น PDF ด้วยลายเซ็นที่วาดหรือรูป PNG, JPG และ WebP ลากตำแหน่ง ย่อขยาย ปรับความทึบ และวางได้หลายหน้า โดยอ่านและสร้างไฟล์ใหม่ภายใน Browser ของอุปกรณ์คุณ",
    category: "media",
    icon: "FilePenLine",
    keywords: ["เซ็น pdf", "ใส่ลายเซ็น pdf", "ลงลายเซ็น pdf", "เซ็นเอกสารออนไลน์", "ลายเซ็นอิเล็กทรอนิกส์", "sign pdf", "add signature to pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["pdf-organizer", "merge-pdf", "split-pdf"],
    howTo: ["เลือก PDF ไม่เกิน 30 MB แล้ววาดหรืออัปโหลดรูปลายเซ็น", "เลือกหน้าและกดวางลายเซ็น จากนั้นลาก ย่อขยาย หรือปรับความทึบ", "กดเซ็นและดาวน์โหลด PDF แล้วเปิดตรวจทุกตำแหน่งก่อนส่งเอกสาร"],
    example: "agreement.pdf · ลายเซ็น 2 ตำแหน่งในหน้า 1 และ 2 → agreement-signed.pdf",
    caution: "ลายเซ็นที่วางเป็นรูปภาพ ไม่ใช่ลายเซ็นดิจิทัลแบบ certificate และไม่ยืนยันตัวตน เวลา หรือความยินยอม การแก้ไขอาจทำให้ลายเซ็นดิจิทัลเดิมไม่ผ่านการตรวจสอบ ไม่รองรับ PDF ที่มีรหัสผ่านและจำกัด 100 หน้า",
    faq: [...commonFaq,
      { question: "ไฟล์ PDF และรูปลายเซ็นถูกอัปโหลดหรือไม่?", answer: "ไม่ การอ่านเอกสาร ประมวลผลรูป และสร้าง PDF ใหม่เกิดใน Browser ของอุปกรณ์คุณ" },
      { question: "วาดลายเซ็นหรือใช้รูปที่มีอยู่ได้หรือไม่?", answer: "ได้ คุณวาดด้วยเมาส์ ปากกา หรือหน้าจอสัมผัส หรืออัปโหลด PNG, JPG และ WebP พร้อมเลือกตัดพื้นขาวอัตโนมัติได้" },
      { question: "นี่คือลายเซ็นดิจิทัลที่ตรวจสอบ certificate ได้หรือไม่?", answer: "ไม่ เครื่องมือวางรูปภาพลายเซ็นลงใน PDF เท่านั้น จึงไม่มี certificate การยืนยันตัวตน timestamp หรือหลักฐานความยินยอม" },
      { question: "รองรับหน้า PDF ที่หมุนอยู่หรือไม่?", answer: "รองรับหน้า 0, 90, 180 และ 270 องศา โดยเครื่องมือแปลงตำแหน่งจากภาพตัวอย่างไปยังพิกัด PDF ตามมุมของแต่ละหน้า" },
    ],
  },
];

export const toolMap = new Map(tools.map((tool) => [tool.slug, tool]));
export const categoryMap = new Map(categoryConfigs.map((category) => [category.value, category]));

export function getTool(slug: string): ToolConfig | undefined {
  return toolMap.get(slug);
}

export function getCategory(value: string): ToolCategoryConfig | undefined {
  return categoryMap.get(value as ToolCategory);
}

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return tools.filter((tool) => tool.category === category);
}

export function searchTools(query: string, category: ToolCategory | "all" = "all") {
  const normalized = query.trim().toLocaleLowerCase("th");
  return tools.filter((tool) => {
    const matchesCategory = category === "all" || tool.category === category;
    const haystack = [tool.name, tool.thaiName, tool.shortDescription, ...tool.keywords]
      .join(" ")
      .toLocaleLowerCase("th");
    return matchesCategory && (!normalized || haystack.includes(normalized));
  });
}
