import type { ToolCategory, ToolCategoryConfig, ToolConfig } from "@/types/tool";

export const categoryConfigs: ToolCategoryConfig[] = [
  { value: "data", label: "ข้อมูล", description: "จัดรูป ตรวจสอบ และแปลงข้อมูลที่ใช้ในการพัฒนาและวิเคราะห์ระบบ", icon: "Database" },
  { value: "encoding", label: "เข้ารหัส", description: "เข้ารหัสและถอดรหัสข้อมูลสำหรับ URL, Base64 และงานแลกเปลี่ยนข้อมูล", icon: "Binary" },
  { value: "security", label: "ความปลอดภัย", description: "ตรวจสอบ token และสร้าง hash โดยประมวลผลข้อมูลภายใน Browser", icon: "ShieldCheck" },
  { value: "text", label: "ข้อความ", description: "ค้นหา เปรียบเทียบ และจัดการข้อความสำหรับงานเขียนและงานเทคนิค", icon: "TextCursorInput" },
  { value: "date-time", label: "วันที่และเวลา", description: "แปลงและทำความเข้าใจวันที่ เวลา Timestamp และเขตเวลา", icon: "Clock3" },
  { value: "developer", label: "เครื่องมือนักพัฒนา", description: "เครื่องมือประจำวันสำหรับเขียนโค้ด ทดสอบ และดูแลระบบ", icon: "Code2" },
  { value: "productivity", label: "งานเอกสาร", description: "ลดงานซ้ำจากข้อความ เอกสาร และข้อมูลที่ใช้ในการทำงานทั่วไป", icon: "BriefcaseBusiness" },
  { value: "business", label: "ธุรกิจและการเงิน", description: "สร้างเอกสารธุรกิจ คำนวณกำไร อัตราส่วน และประมาณการทางการเงินด้วยสูตรที่ตรวจสอบได้", icon: "CircleDollarSign" },
  { value: "calculator", label: "เครื่องคำนวณ", description: "คำนวณตัวเลข อายุ วันที่ และหน่วยด้วยสูตรที่อ่านและตรวจสอบได้", icon: "Calculator" },
  { value: "media", label: "รูปภาพและ PDF", description: "สร้างและแปลงรูปภาพ QR Code และเอกสาร PDF ภายในอุปกรณ์", icon: "Images" },
];

export const toolCategories: Array<{ value: ToolCategory | "all"; label: string }> = [
  { value: "all", label: "ทั้งหมด" },
  ...categoryConfigs.map(({ value, label }) => ({ value, label })),
];

const commonFaq = [
  {
    question: "ข้อมูลถูกส่งขึ้น Server หรือไม่?",
    answer:
      "ไม่ ข้อมูลที่กรอกถูกประมวลผลภายใน Browser และ Meaw Tools ไม่บันทึกเนื้อหาเครื่องมือ",
  },
  {
    question: "ใช้งานฟรีหรือไม่?",
    answer: "ใช้งานฟรี ไม่ต้องสมัครสมาชิก และไม่มีข้อจำกัดจากบัญชีผู้ใช้",
  },
];

export const tools: ToolConfig[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    thaiName: "จัดรูป JSON ออนไลน์",
    shortDescription: "จัดรูป ย่อ และตรวจสอบ JSON ให้อ่านง่าย",
    description:
      "จัดรูป JSON ด้วย indent 2 หรือ 4 ช่อง ตรวจสอบ syntax คัดลอก และดาวน์โหลดผลลัพธ์ได้ทันที",
    category: "data",
    icon: "Braces",
    keywords: ["json formatter", "json", "formatter", "จัดรูป json", "minify", "pretty print"],
    isPopular: true,
    isNew: false,
    relatedTools: ["json-validator", "base64", "diff-checker"],
    howTo: ["วาง JSON ในช่องข้อมูล", "เลือก indent แล้วกดจัดรูปหรือย่อ", "คัดลอกหรือดาวน์โหลดผลลัพธ์"],
    example: '{"name":"Benz","skills":["PHP","Next.js","SQL"]}',
    caution: "ข้อมูลขนาดใหญ่มากอาจใช้หน่วยความจำของ Browser สูง",
    faq: commonFaq,
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    thaiName: "ตรวจสอบ JSON ออนไลน์",
    shortDescription: "ตรวจ syntax พร้อมตำแหน่งบรรทัดและสถิติ",
    description: "ตรวจสอบความถูกต้องของ JSON พร้อมบรรทัด คอลัมน์ และจำนวน object, array และ key",
    category: "data",
    icon: "BadgeCheck",
    keywords: ["json validator", "validator", "ตรวจ json", "json syntax checker", "validate json online", "syntax"],
    isPopular: false,
    isNew: false,
    relatedTools: ["json-formatter", "diff-checker", "base64"],
    howTo: ["วาง JSON ที่ต้องการตรวจ", "กดตรวจสอบ", "แก้ไขตามตำแหน่ง error ที่แสดง"],
    example: '{"valid":true,"items":[1,2,3]}',
    caution: "เครื่องมือตรวจ syntax เท่านั้น ไม่ตรวจ business schema",
    faq: commonFaq,
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    thaiName: "จัดรูป SQL ออนไลน์",
    shortDescription: "จัดรูป SQL หลาย dialect โดยไม่ execute query",
    description: "จัดรูป SQL Server, MySQL, PostgreSQL, MariaDB, SQLite และ Standard SQL ภายใน Browser",
    category: "data",
    icon: "Database",
    keywords: ["sql", "formatter", "mysql", "postgresql", "sql server", "จัดรูป sql"],
    isPopular: true,
    isNew: false,
    relatedTools: ["json-formatter", "diff-checker", "regex-tester"],
    howTo: ["วาง SQL", "เลือก dialect และรูปแบบ keyword", "กดจัดรูปและคัดลอกผลลัพธ์"],
    example: "select u.id,u.name from users u where u.active=1 order by u.name;",
    caution: "เครื่องมือนี้ไม่เชื่อมต่อฐานข้อมูลและไม่ execute SQL",
    faq: commonFaq,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    thaiName: "อ่าน JWT ออนไลน์",
    shortDescription: "ถอด Header และ Payload โดยไม่ verify signature",
    description: "อ่านส่วนประกอบ JWT พร้อมเวลาออก token และวันหมดอายุ โดยไม่ส่ง token ออกจาก Browser",
    category: "security",
    icon: "KeyRound",
    keywords: ["jwt", "decoder", "token", "decode jwt", "อ่าน jwt"],
    isPopular: true,
    isNew: false,
    relatedTools: ["base64", "timestamp-converter", "json-formatter"],
    howTo: ["วาง JWT ที่มี 3 ส่วน", "กด Decode", "ตรวจ Header, Payload และสถานะหมดอายุ"],
    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJuYW1lIjoiRGV2VGhhaSIsImlhdCI6MTcwNDA2NzIwMH0.signature",
    caution: "อย่าวาง token ที่ยังใช้งานได้บนเครื่องสาธารณะ และผล Decode ไม่ได้ยืนยันลายเซ็น",
    faq: commonFaq,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    thaiName: "สร้าง UUID v4",
    shortDescription: "สร้าง UUID v4 ครั้งละ 1–100 รายการ",
    description: "สร้าง UUID v4 ด้วย Browser Crypto API เลือกตัวพิมพ์และเครื่องหมายขีดได้",
    category: "developer",
    icon: "Fingerprint",
    keywords: ["uuid generator", "uuid", "guid", "uuid v4", "สร้าง uuid", "random uuid"],
    isPopular: true,
    isNew: false,
    relatedTools: ["hash-generator", "timestamp-converter", "json-formatter"],
    howTo: ["กำหนดจำนวน 1–100", "เลือกรูปแบบ", "กดสร้างแล้วคัดลอกหรือดาวน์โหลด"],
    example: "จำนวน 5 รายการ แบบ lowercase พร้อม hyphen",
    caution: "UUID ใช้เป็น identifier ได้ แต่ไม่ควรใช้แทน secret",
    faq: commonFaq,
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    thaiName: "แปลง Timestamp",
    shortDescription: "แปลง Unix, ISO, UTC, เวลาท้องถิ่น และ พ.ศ.",
    description: "แปลง Unix seconds หรือ milliseconds และวันเวลาเป็นรูปแบบที่นักพัฒนาใช้บ่อย",
    category: "date-time",
    icon: "Clock3",
    keywords: ["timestamp", "unix", "เวลา", "utc", "iso 8601", "พ.ศ."],
    isPopular: true,
    isNew: false,
    relatedTools: ["buddhist-year-converter", "cron-generator", "jwt-decoder"],
    howTo: ["กรอก timestamp หรือเลือกวันที่", "เลือกหน่วย", "ดูและคัดลอกผลลัพธ์หลายรูปแบบ"],
    example: "1704067200",
    caution: "เวลาท้องถิ่นขึ้นกับ timezone ของอุปกรณ์ที่ใช้งาน",
    faq: commonFaq,
  },
  {
    slug: "buddhist-year-converter",
    name: "Buddhist Year Converter",
    thaiName: "แปลงปี พ.ศ. ค.ศ.",
    shortDescription: "แปลงปี พ.ศ. และ ค.ศ. ทีละปีหรือหลายรายการ",
    description: "แปลงปีพุทธศักราชและคริสต์ศักราชได้สูงสุด 100 รายการ พร้อมสลับทิศทาง คัดลอกผลลัพธ์ และสูตรสำหรับ Excel หรือ Google Sheets",
    category: "date-time",
    icon: "CalendarDays",
    keywords: ["พ.ศ. ค.ศ.", "แปลง พ.ศ. เป็น ค.ศ.", "แปลง ค.ศ. เป็น พ.ศ.", "ปีนี้ ค.ศ. อะไร", "พศ คศ", "buddhist year converter", "excel พ.ศ. ค.ศ."],
    isPopular: true,
    isNew: true,
    relatedTools: ["timestamp-converter", "date-calculator", "age-calculator"],
    howTo: ["เลือกทิศทาง พ.ศ. → ค.ศ. หรือ ค.ศ. → พ.ศ.", "กรอกปีหนึ่งรายการหรือหลายรายการ โดยคั่นด้วยบรรทัด เว้นวรรค หรือ comma", "กดแปลงปี แล้วคัดลอกผลลัพธ์หรือสูตร Excel"],
    example: "พ.ศ. 2569 → ค.ศ. 2026",
    caution: "ใช้หลักบวกหรือลบ 543 สำหรับเลขปีทั่วไป วันที่ทางประวัติศาสตร์ก่อน พ.ศ. 2484 อาจต้องพิจารณาวันขึ้นปีใหม่ของไทยในขณะนั้นเพิ่มเติม",
    faq: [...commonFaq, { question: "ทำไม พ.ศ. กับ ค.ศ. ต่างกัน 543 ปี?", answer: "การแปลงเลขปีที่ใช้ทั่วไปในไทยใช้ พ.ศ. = ค.ศ. + 543 หรือ ค.ศ. = พ.ศ. - 543 เครื่องมือนี้จึงใช้สูตรดังกล่าวกับทุกรายการ" }],
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    thaiName: "เข้ารหัสและถอด Base64",
    shortDescription: "แปลงข้อความ UTF-8 และไฟล์เป็น Base64",
    description: "เข้ารหัสและถอด Base64 รองรับภาษาไทย พร้อมตรวจรูปแบบและจำกัดขนาดไฟล์",
    category: "encoding",
    icon: "Binary",
    keywords: ["base64", "encode", "decode", "เข้ารหัส", "ถอดรหัส"],
    isPopular: false,
    isNew: false,
    relatedTools: ["url-encoder", "jwt-decoder", "hash-generator"],
    howTo: ["เลือกโหมดเข้ารหัสหรือถอดรหัส", "วางข้อความหรือเลือกไฟล์", "กดประมวลผลแล้วคัดลอก"],
    example: "สวัสดี Meaw",
    caution: "Base64 ไม่ใช่การเข้ารหัสเพื่อความปลอดภัย และไฟล์จำกัด 5 MB",
    faq: commonFaq,
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    thaiName: "เข้ารหัสและถอด URL",
    shortDescription: "Encode หรือ Decode URI และ URI Component",
    description: "แปลง URL และ query parameter อย่างถูกต้องด้วยมาตรฐาน Browser",
    category: "encoding",
    icon: "Link2",
    keywords: ["url", "uri", "encodeURIComponent", "decode url", "เปอร์เซ็นต์"],
    isPopular: false,
    isNew: false,
    relatedTools: ["base64", "regex-tester", "json-formatter"],
    howTo: ["เลือก URI หรือ URI Component", "เลือก Encode หรือ Decode", "วางข้อความแล้วประมวลผล"],
    example: "https://example.com/search?q=ภาษาไทย&sort=new",
    caution: "ใช้ URI Component สำหรับค่ารายตัวใน query string",
    faq: commonFaq,
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    thaiName: "ทดสอบ Regular Expression",
    shortDescription: "ค้นหา match, group และทดลอง replace",
    description: "ทดสอบ Regular Expression พร้อม flags, match index, capture group และ replace preview",
    category: "text",
    icon: "Regex",
    keywords: ["regex tester", "regex", "regexp", "regular expression", "ทดสอบ regex", "regex online"],
    isPopular: true,
    isNew: false,
    relatedTools: ["diff-checker", "json-validator", "url-encoder"],
    howTo: ["กรอก pattern และ flags", "วางข้อความทดสอบ", "กดทดสอบและดู match หรือ replace preview"],
    example: "Pattern: \\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b",
    caution: "ระบบจำกัดขนาดและปฏิเสธ pattern เสี่ยงสูงเพื่อลด ReDoS ใน Browser",
    faq: commonFaq,
  },
  {
    slug: "diff-checker",
    name: "Text Diff Checker",
    thaiName: "เปรียบเทียบข้อความ",
    shortDescription: "ดูข้อความที่เพิ่ม ลบ และเปลี่ยนแปลง",
    description: "เปรียบเทียบข้อความแบบ inline หรือ side-by-side พร้อมตัวเลือก ignore case และ whitespace",
    category: "text",
    icon: "GitCompareArrows",
    keywords: ["text diff checker", "diff", "compare", "text", "เปรียบเทียบข้อความ", "compare text online"],
    isPopular: false,
    isNew: false,
    relatedTools: ["regex-tester", "json-formatter", "sql-formatter"],
    howTo: ["วางข้อความต้นฉบับและข้อความใหม่", "เลือกตัวเลือกที่ต้องการละเว้น", "กดเปรียบเทียบ"],
    example: "เดิม: Meaw Tools\nใหม่: Meaw Tools ใช้งานฟรี",
    caution: "ข้อความแต่ละฝั่งจำกัด 1 MB เพื่อป้องกัน Browser ค้าง",
    faq: commonFaq,
  },
  {
    slug: "cron-generator",
    name: "Cron Generator",
    thaiName: "สร้าง Cron Expression",
    shortDescription: "สร้าง Cron 5 ช่อง พร้อมคำอธิบายและรอบถัดไป",
    description: "สร้าง Cron จากแบบฟอร์ม อธิบายภาษาไทย และแสดงเวลาทำงานถัดไป",
    category: "developer",
    icon: "CalendarClock",
    keywords: ["cron", "crontab", "scheduler", "สร้าง cron", "ตั้งเวลา"],
    isPopular: false,
    isNew: false,
    relatedTools: ["timestamp-converter", "uuid-generator", "regex-tester"],
    howTo: ["กำหนดนาที ชั่วโมง วัน เดือน และวันในสัปดาห์", "ตรวจ expression", "คัดลอกไปใช้กับ platform ของคุณ"],
    example: "0 8 * * 1-5",
    caution: "Cron syntax และ timezone อาจแตกต่างกันตาม Linux, GitHub Actions, Vercel หรือ cloud provider",
    faq: commonFaq,
  },
  {
    slug: "markdown-table-generator",
    name: "Markdown Table Generator",
    thaiName: "สร้างตาราง Markdown ออนไลน์",
    shortDescription: "สร้าง แก้ไข จัดแนว และแปลงข้อมูล Excel, CSV หรือ TSV เป็นตาราง Markdown",
    description: "สร้างตาราง Markdown ออนไลน์ฟรีด้วย visual editor วางข้อมูลจาก Excel, Google Sheets, CSV หรือ TSV ได้ ตรวจตัวคั่นอัตโนมัติ จัดแนวแต่ละคอลัมน์ escape เครื่องหมาย Pipe และดู Preview ก่อนคัดลอกหรือดาวน์โหลด GitHub Flavored Markdown",
    category: "developer",
    icon: "Table2",
    keywords: ["markdown table generator", "markdown table generator online", "markdown table formatter", "markdown table editor", "create table markdown", "สร้างตาราง markdown", "markdown table from excel", "markdown table from csv", "แปลง csv เป็น markdown", "จัดตาราง markdown", "github markdown table", "gfm table generator"],
    isPopular: true,
    isNew: true,
    relatedTools: ["html-table-generator", "csv-to-excel", "csv-cleaner"],
    howTo: ["พิมพ์ในตารางโดยตรง หรือวางข้อมูลจาก Excel, Google Sheets, CSV หรือ TSV แล้วเลือกว่าจะใช้แถวแรกเป็นหัวตารางหรือไม่", "แก้ไขหัวตารางและเซลล์ เพิ่มหรือลบแถว/คอลัมน์ แล้วเลือกการจัดแนวซ้าย กลาง หรือขวาของแต่ละคอลัมน์", "ตรวจ Preview และ Markdown ที่สร้างแบบทันที จากนั้นคัดลอกหรือดาวน์โหลดไฟล์ .md"],
    example: "สินค้า, ราคา, สถานะ → ตาราง GFM 3 คอลัมน์ โดยราคาอยู่ขวา สถานะอยู่กลาง และค่า ครัวซองต์ | เนยสด ถูก escape เป็น ครัวซองต์ \\| เนยสด",
    caution: "GitHub Flavored Markdown ไม่รองรับ merged cells, colspan หรือ rowspan และ Markdown renderer บางตัวอาจไม่รองรับตารางหรือ HTML <br> เหมือน GitHub เครื่องมือนี้จำกัด 100 แถว, 20 คอลัมน์ และ 1,000 ตัวอักษรต่อเซลล์เพื่อรักษาความลื่นของ Browser",
    faq: [...commonFaq,
      { question: "สร้างตาราง Markdown ต้องใช้ Pipe และ Hyphen อย่างไร?", answer: "แถวแรกคือหัวตาราง แถวถัดไปเป็น delimiter ที่ใช้ Hyphen อย่างน้อย 3 ตัวต่อคอลัมน์ และแต่ละคอลัมน์คั่นด้วย Pipe เครื่องมือสร้างทั้งสองแถวและจัดระยะให้อัตโนมัติ" },
      { question: "วางข้อมูลจาก Excel หรือ Google Sheets ได้หรือไม่?", answer: "ได้ ให้คัดลอกช่วงเซลล์แล้ววางในช่องนำเข้า ข้อมูลจะเป็น Tab-separated โดยทั่วไป เครื่องมือตรวจ Tab, Comma, Semicolon หรือ Pipe อัตโนมัติและรองรับ quoted CSV" },
      { question: "ถ้าในเซลล์มีเครื่องหมาย | จะทำอย่างไร?", answer: "เครื่องมือ escape Pipe เป็น \\| ตามรูปแบบ GitHub Flavored Markdown เพื่อไม่ให้ถูกตีความเป็นจุดแบ่งคอลัมน์ ส่วน Backslash เดิมจะถูก escape ก่อนเพื่อรักษาข้อความ" },
      { question: "จัดข้อความซ้าย กลาง หรือขวาได้อย่างไร?", answer: "เลือกการจัดแนวใต้หัวคอลัมน์ เครื่องมือจะใส่ Colon ใน delimiter row: Colon ด้านซ้ายสำหรับชิดซ้าย สองด้านสำหรับกึ่งกลาง และด้านขวาสำหรับชิดขวา" },
      { question: "รองรับข้อความหลายบรรทัดในเซลล์หรือไม่?", answer: "รองรับโดยแปลง line break เป็นแท็ก <br> ซึ่งใช้ได้บน GitHub แต่ Markdown renderer ที่ปิด raw HTML อาจไม่แสดงการขึ้นบรรทัดแบบเดียวกัน" },
      { question: "รวมเซลล์ด้วย colspan หรือ rowspan ได้หรือไม่?", answer: "ไม่ได้ ตาราง GFM ไม่มี syntax สำหรับ merged cells, colspan หรือ rowspan หากจำเป็นต้องรวมเซลล์ควรใช้ HTML table ในระบบที่อนุญาต raw HTML" },
      { question: "ข้อมูลตารางถูกอัปโหลดหรือบันทึกหรือไม่?", answer: "ไม่ การ parse, แก้ไข, Preview, คัดลอก และสร้างไฟล์ .md ทำใน Browser ไม่มี API ของ Meaw Tools รับหรือบันทึกข้อมูล" },
    ],
  },
  {
    slug: "html-table-generator",
    name: "HTML Table Generator",
    thaiName: "สร้างตาราง HTML ออนไลน์",
    shortDescription: "สร้างตาราง HTML จาก Excel, CSV หรือ TSV พร้อม colspan, rowspan, CSS และ Preview",
    description: "สร้างตาราง HTML ออนไลน์ฟรีด้วย visual editor วางข้อมูลจาก Excel, Google Sheets, CSV หรือ TSV ได้ รวมและแยกเซลล์ด้วย colspan/rowspan เลือก CSS, inline CSS หรือ semantic HTML พร้อม caption, thead, tbody, scope และ responsive Preview ก่อนคัดลอกหรือดาวน์โหลดไฟล์ .html",
    category: "developer",
    icon: "Table2",
    keywords: ["html table generator", "html table generator online", "html table generator with colspan and rowspan", "html table generator with css", "html table generator inline css", "html table generator from excel", "html table code generator", "html table editor", "สร้างตาราง html", "สร้างตาราง html ออนไลน์", "สร้างตาราง html colspan rowspan", "สร้างโค้ดตาราง html", "แปลง excel เป็น html table", "ตาราง html responsive"],
    isPopular: true,
    isNew: true,
    relatedTools: ["markdown-table-generator", "csv-to-excel", "excel-to-csv"],
    howTo: ["วางข้อมูลจาก Excel, Google Sheets, CSV หรือ TSV แล้วกดนำเข้า หรือแก้ไขเซลล์ในตารางโดยตรง", "เลือกเซลล์เพื่อกำหนด colspan และ rowspan จากนั้นตั้ง caption, หัวตาราง, หัวแถว, responsive wrapper และรูปแบบ CSS", "ตรวจ semantic Preview และโค้ด HTML แล้วคัดลอก snippet หรือดาวน์โหลดหน้า .html ที่เปิดใช้งานได้ทันที"],
    example: "สินค้า, ราคา, สถานะ → <table> ที่มี <caption>, <thead>, <tbody>, <th scope=\"col\"> และ CSS แบบ Striped พร้อม wrapper เลื่อนแนวนอนบนมือถือ",
    caution: "ควรใช้ table สำหรับข้อมูลที่มีความสัมพันธ์เป็นแถวและคอลัมน์ ไม่ควรใช้จัด Layout หน้าเว็บ หัวตารางใน thead จะไม่อนุญาต rowspan ข้ามไป tbody และควรทดสอบกับ Screen reader เมื่อเป็นข้อมูลสำคัญ เครื่องมือจำกัด 100 แถว, 20 คอลัมน์ และ 1,000 ตัวอักษรต่อเซลล์เพื่อรักษาความลื่นของ Browser",
    faq: [...commonFaq,
      { question: "สร้างตาราง HTML จาก Excel หรือ Google Sheets ได้อย่างไร?", answer: "คัดลอกช่วงเซลล์จาก Excel หรือ Google Sheets แล้ววางในช่องนำเข้า ข้อมูลแบบ Tab-separated จะถูกตรวจอัตโนมัติ เช่นเดียวกับ CSV ที่ใช้ comma, semicolon หรือ pipe และ quoted CSV" },
      { question: "รวมเซลล์ด้วย colspan และ rowspan ได้หรือไม่?", answer: "ได้ เลือกเซลล์หลัก กำหนดจำนวนคอลัมน์และแถวที่ต้องการ แล้วกดใช้ colspan/rowspan เครื่องมือจะตรวจไม่ให้ช่วงรวมทับกันหรือเกินขอบตาราง และแยกเซลล์กลับได้" },
      { question: "ทำไม rowspan ของหัวตารางแถวแรกจึงตั้งเกิน 1 ไม่ได้?", answer: "เมื่อเปิดแถวแรกเป็นหัวตาราง แถวนั้นอยู่ใน thead การใช้ rowspan ข้ามลง tbody ทำให้โครงสร้างกลุ่มแถวไม่ชัดเจน เครื่องมือจึงป้องกันไว้ แต่ยังรวมหลายคอลัมน์ด้วย colspan และ scope=colgroup ได้" },
      { question: "เลือก CSS, Inline CSS หรือ Semantic HTML ต่างกันอย่างไร?", answer: "CSS + class สร้าง style block และ class ที่แก้ธีมต่อได้ง่าย Inline CSS ใส่ style ในแต่ละ element เหมาะกับระบบที่แยก CSS ไม่ได้ ส่วน Semantic HTML ไม่มี CSS และ responsive wrapper เพื่อให้คุณจัดรูปแบบเอง" },
      { question: "ตารางที่สร้างรองรับมือถือหรือไม่?", answer: "โหมด CSS และ Inline CSS เปิด responsive wrapper ได้ ตารางกว้างจะเลื่อนแนวนอนภายในกรอบโดยหน้าเว็บหลักไม่ล้น ส่วน Semantic HTML ปล่อยให้ผู้ใช้กำหนด responsive CSS เอง" },
      { question: "เครื่องมือสร้าง HTML ที่ช่วยเรื่อง Accessibility อย่างไร?", answer: "เมื่อเปิดตัวเลือกหัวตารางหรือหัวแถว เครื่องมือสร้าง th พร้อม scope=col, row, colgroup หรือ rowgroup ตาม span และรองรับ caption เพื่อบอกชื่อตารางตามแนวทาง W3C" },
      { question: "ข้อความ HTML หรือ Script ในเซลล์จะทำงานหรือไม่?", answer: "ไม่ เครื่องมือ escape เครื่องหมาย &, < และ > ก่อนสร้างโค้ด ค่าที่วางอย่าง <script> จึงแสดงเป็นข้อความในเซลล์ ไม่ถูกนำไป execute ใน Preview" },
      { question: "ดาวน์โหลดเป็นไฟล์ HTML ที่เปิดได้เลยหรือไม่?", answer: "ได้ ปุ่มดาวน์โหลดสร้างเอกสาร HTML5 ที่มี doctype, charset UTF-8, viewport, title และตารางตามตัวเลือก เปิดใน Browser หรือนำไปแก้ต่อได้ทันที" },
    ],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    thaiName: "สร้าง Hash ออนไลน์",
    shortDescription: "สร้าง SHA-1, SHA-256, SHA-384 และ SHA-512",
    description: "คำนวณ hash ของข้อความหรือไฟล์ด้วย Web Crypto API และเปรียบเทียบค่าได้",
    category: "security",
    icon: "Hash",
    keywords: ["hash", "sha256", "sha512", "checksum", "สร้าง hash"],
    isPopular: false,
    isNew: false,
    relatedTools: ["base64", "uuid-generator", "jwt-decoder"],
    howTo: ["เลือก algorithm", "กรอกข้อความหรือเลือกไฟล์", "กดสร้างและเปรียบเทียบ hash หากต้องการ"],
    example: "Meaw Tools",
    caution: "Hash ไม่ใช่ encryption และ SHA ธรรมดาไม่เหมาะสำหรับเก็บรหัสผ่าน",
    faq: commonFaq,
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    thaiName: "นับคำและตัวอักษร",
    shortDescription: "นับคำไทย ตัวอักษร ประโยค บรรทัด และเวลาอ่าน",
    description: "วิเคราะห์ข้อความภาษาไทยและภาษาอังกฤษแบบทันที พร้อมจำนวนคำ ตัวอักษร ประโยค ย่อหน้า และเวลาอ่านโดยประมาณ",
    category: "productivity",
    icon: "TextCursorInput",
    keywords: ["นับคำ", "นับตัวอักษร", "word count", "นักเขียน", "คอนเทนต์", "seo"],
    isPopular: true,
    isNew: true,
    relatedTools: ["text-cleaner", "diff-checker", "regex-tester"],
    howTo: ["พิมพ์หรือวางข้อความในช่อง", "ดูสถิติที่อัปเดตทันที", "คัดลอกหรือล้างข้อความเมื่อต้องการ"],
    example: "Meaw Tools ช่วยนับคำภาษาไทยได้โดยไม่ต้องส่งข้อมูลออกจาก Browser",
    caution: "จำนวนคำใช้กฎการแบ่งคำของ Browser ซึ่งอาจต่างจากข้อกำหนดเฉพาะของสำนักพิมพ์บางแห่ง",
    faq: commonFaq,
  },
  {
    slug: "text-cleaner",
    name: "Text Cleaner",
    thaiName: "จัดระเบียบข้อความ",
    shortDescription: "ล้างช่องว่าง บรรทัดว่าง และรายการซ้ำ",
    description: "จัดข้อความและจัดระเบียบเนื้อหาจากเอกสาร แชต หรือสเปรดชีต ด้วยตัวเลือกตัดช่องว่าง ยุบช่องว่าง ลบบรรทัดว่าง และลบบรรทัดซ้ำ",
    category: "productivity",
    icon: "ListFilter",
    keywords: ["จัดข้อความ", "ลบช่องว่าง", "ลบบรรทัดซ้ำ", "clean text", "งานเอกสาร"],
    isPopular: false,
    isNew: true,
    relatedTools: ["csv-cleaner", "word-counter", "diff-checker"],
    howTo: ["วางข้อความต้นฉบับ", "เลือกกฎการจัดระเบียบ", "กดจัดระเบียบแล้วคัดลอกผลลัพธ์"],
    example: "  สินค้า A   100 บาท  \n\nสินค้า A   100 บาท",
    caution: "การลบบรรทัดซ้ำจะเก็บเฉพาะบรรทัดแรก และพิจารณาตัวพิมพ์เล็ก-ใหญ่ตามจริง",
    faq: commonFaq,
  },
  {
    slug: "csv-to-excel",
    name: "CSV to Excel Converter",
    thaiName: "แปลง CSV เป็น Excel ออนไลน์",
    shortDescription: "ตรวจคอลัมน์และแปลง CSV, TSV หรือ TXT เป็นไฟล์ Excel .xlsx",
    description: "แปลง CSV เป็น Excel ออนไลน์ฟรี รองรับ comma, tab, semicolon, pipe, UTF-8 และ Windows-874 ดูตัวอย่างคอลัมน์ก่อนดาวน์โหลด .xlsx พร้อมเก็บเลขศูนย์นำหน้าและป้องกัน Formula Injection โดยประมวลผลใน Web Worker ของ Browser",
    category: "productivity",
    icon: "FileSpreadsheet",
    keywords: ["csv to excel", "csv to excel converter", "csv to excel online", "csv to excel converter online", "convert csv to excel", "convert csv to excel online free", "แปลง csv เป็น excel", "แปลง csv", "csv เป็น xlsx", "csv columns", "tsv to excel", "เปิด csv ภาษาไทย"],
    isPopular: true,
    isNew: true,
    relatedTools: ["csv-cleaner", "text-cleaner", "json-formatter"],
    howTo: ["เลือกไฟล์ CSV, TSV หรือ TXT หรือวางข้อความ แล้วเลือก Encoding และตัวคั่นคอลัมน์", "กดตรวจและดูตัวอย่าง ตรวจจำนวนแถว คอลัมน์ แถวว่าง และแถวที่โครงสร้างไม่เท่ากัน", "ตั้งชื่อ Worksheet เลือกหัวตารางและการตรวจตัวเลข แล้วดาวน์โหลดไฟล์ Excel .xlsx"],
    example: "00123,ชาเขียว,55 → Excel 3 คอลัมน์ โดย 00123 ยังคงเลขศูนย์นำหน้าและ 55 ใช้คำนวณต่อได้",
    caution: "ควรตรวจ Preview และจำนวนคอลัมน์ก่อนใช้งานจริง โดยเฉพาะไฟล์ที่ตัวคั่นไม่สม่ำเสมอ เครื่องมือไม่เดาแก้หรือลบแถวให้เอง และจำกัด 10 MB, 50,000 แถว, 200 คอลัมน์ หรือ 500,000 เซลล์เพื่อรักษาความลื่นของ Browser",
    faq: [...commonFaq,
      { question: "CSV และ Excel .xlsx ต่างกันอย่างไร?", answer: "CSV เป็นข้อความตารางที่ใช้ตัวคั่นและไม่มีรูปแบบเซลล์ ส่วน .xlsx เป็น Workbook ที่รองรับชนิดข้อมูล หัวตาราง Filter ความกว้างคอลัมน์ และหลาย Worksheet เครื่องมือนี้นำข้อมูล CSV ไปสร้างเป็น .xlsx หนึ่ง Worksheet" },
      { question: "รองรับตัวคั่นอะไรบ้าง?", answer: "รองรับ comma, tab, semicolon และ pipe โดยเลือกตรวจอัตโนมัติหรือระบุเองได้ รวมถึงข้อความที่ครอบด้วย quote, quote ซ้อน และข้อความหลายบรรทัด" },
      { question: "ถ้าภาษาไทยเป็นตัวอักษรเพี้ยนต้องทำอย่างไร?", answer: "ลองสลับ Encoding จาก UTF-8 เป็น Windows-874 ซึ่งพบในไฟล์ภาษาไทยจากโปรแกรมรุ่นเก่า แล้วกดตรวจ Preview ใหม่ก่อนดาวน์โหลด" },
      { question: "เลขรหัสที่ขึ้นต้นด้วย 0 จะหายหรือไม่?", answer: "ไม่หาย ค่าอย่าง 00123 จะถูกเก็บเป็นข้อความ แม้เปิดการตรวจตัวเลขอัตโนมัติ ส่วนตัวเลขทั่วไปอย่าง 55 หรือ -12.5 จะถูกสร้างเป็นเซลล์ตัวเลขเพื่อคำนวณต่อได้" },
      { question: "ป้องกัน CSV หรือ Formula Injection อย่างไร?", answer: "เครื่องมือไม่สร้างสูตรจากข้อมูล CSV ค่าเช่น =SUM(...), +CMD, -CMD หรือ @ จะถูกเขียนเป็นข้อความแบบ inline string ใน .xlsx ขณะที่จำนวนลบที่เป็นตัวเลขล้วนยังเป็นตัวเลขได้" },
      { question: "ทำไมบางแถวมีจำนวนคอลัมน์ไม่เท่ากัน?", answer: "สาเหตุอาจมาจากตัวคั่นผิด, quote ปิดไม่ครบ หรือข้อมูลต้นทางมีช่องไม่เท่ากัน เครื่องมือจะแจ้งจำนวนแถวผิดรูปและเก็บค่าตามต้นฉบับเพื่อให้ผู้ใช้ตัดสินใจเอง" },
      { question: "รองรับไฟล์ขนาดใหญ่เท่าไร?", answer: "รองรับสูงสุด 10 MB, 50,000 แถว, 200 คอลัมน์ และ 500,000 เซลล์ต่อครั้ง งานถูกทำใน Web Worker เพื่อลดการค้างของหน้าเว็บ แต่ไฟล์ใหญ่กว่านี้ควรใช้การนำเข้าข้อมูลของ Excel โดยตรง" },
    ],
  },
  {
    slug: "excel-to-csv",
    name: "Excel to CSV Converter",
    thaiName: "แปลง Excel เป็น CSV ออนไลน์",
    shortDescription: "เลือก Worksheet และแปลงไฟล์ Excel .xlsx เป็น CSV UTF-8 หรือ ZIP",
    description: "แปลง Excel เป็น CSV ออนไลน์ฟรีจากไฟล์ .xlsx เลือก Worksheet, comma, semicolon, tab หรือ pipe ได้ รองรับ UTF-8 BOM สำหรับภาษาไทย ดู Preview และส่งออกทุกชีตเป็น ZIP โดยประมวลผลใน Web Worker ของ Browser",
    category: "productivity",
    icon: "FileDown",
    keywords: ["excel to csv", "excel to csv converter", "excel to csv converter online", "convert excel to csv", "xlsx to csv", "xlsx to csv converter", "แปลง excel เป็น csv", "แปลง xlsx เป็น csv", "excel เป็น csv ออนไลน์", "csv utf-8 bom", "export excel sheet to csv", "แยก worksheet เป็น csv"],
    isPopular: true,
    isNew: true,
    relatedTools: ["csv-to-excel", "csv-cleaner", "markdown-table-generator"],
    howTo: ["เลือกหรือลากไฟล์ Excel .xlsx เข้ามา เครื่องมือจะอ่านรายชื่อ Worksheet และสร้าง Preview ภายใน Browser", "เลือก Worksheet หรือตัวเลือกทุก Worksheet แล้วกำหนดตัวคั่น รูปแบบขึ้นบรรทัด UTF-8 BOM และการป้องกัน Formula Injection", "ตรวจจำนวนแถว คอลัมน์ และ Preview จากนั้นดาวน์โหลด CSV หนึ่งไฟล์ หรือ ZIP ที่แยก CSV ตาม Worksheet"],
    example: "Workbook ยอดขาย.xlsx มีชีต มกราคม และ กุมภาพันธ์ → เลือกทุก Worksheet → ได้ยอดขาย-มกราคม.csv และยอดขาย-กุมภาพันธ์.csv ในไฟล์ ZIP",
    caution: "รองรับเฉพาะ .xlsx ไม่รองรับ .xls หรือ macro และ CSV เก็บเฉพาะค่าของเซลล์ ไม่เก็บสี ฟอนต์ สูตร รูปภาพ Chart หรือ merged cell ควรตรวจ Preview ก่อนดาวน์โหลด โดยจำกัด 10 MB, 50 Worksheet, 50,000 แถวต่อชีต, 200 คอลัมน์ หรือ 500,000 เซลล์รวมเพื่อรักษาความลื่นของ Browser",
    faq: [...commonFaq,
      { question: "Excel และ CSV ต่างกันอย่างไร?", answer: "Excel .xlsx เป็น Workbook ที่เก็บหลาย Worksheet ชนิดข้อมูล สูตร และรูปแบบเซลล์ ส่วน CSV เป็นข้อความตารางหนึ่งชุดต่อไฟล์ เครื่องมือนี้จึงให้เลือกชีตเดียวหรือสร้าง ZIP ที่มี CSV แยกตามชีต" },
      { question: "ทำไมควรเปิด UTF-8 BOM เมื่อมีภาษาไทย?", answer: "Microsoft ระบุว่า Excel เปิด CSV แบบ UTF-8 ได้ตามปกติเมื่อไฟล์มี BOM จึงเปิดเป็นค่าเริ่มต้นเพื่อลดปัญหาภาษาไทยเพี้ยน แต่คุณปิดได้เมื่อระบบนำเข้าปลายทางไม่ต้องการ BOM" },
      { question: "รองรับไฟล์ Excel .xls รุ่นเก่าหรือไม่?", answer: "ไม่รองรับ ให้เปิดไฟล์ .xls ใน Excel, LibreOffice หรือ Google Sheets แล้วบันทึกใหม่เป็น .xlsx ก่อน เพื่อให้การอ่านไฟล์ใน Browser มีขอบเขตที่ชัดเจนและปลอดภัยกว่า" },
      { question: "ส่งออกทุก Worksheet พร้อมกันได้หรือไม่?", answer: "ได้ หาก Workbook มีมากกว่าหนึ่ง Worksheet ให้เลือกทุก Worksheet เครื่องมือจะสร้าง CSV แยกหนึ่งไฟล์ต่อชีตและรวมเป็น ZIP พร้อมจัดชื่อไฟล์ที่ซ้ำหรือมีอักขระต้องห้ามให้อัตโนมัติ" },
      { question: "สูตรและรูปแบบเลขศูนย์นำหน้าจะเป็นอย่างไร?", answer: "CSV เก็บค่าที่อ่านได้ ไม่เก็บสูตรหรือรูปแบบแสดงผล หาก 00123 ถูกเก็บเป็น Text จะรักษาเลขศูนย์ได้ แต่ถ้าเป็นตัวเลขพร้อม custom format อาจเหลือ 123 จึงควรตรวจ Preview ก่อนส่งออก" },
      { question: "ป้องกัน CSV Formula Injection อย่างไร?", answer: "ค่าเริ่มต้นจะเติม Tab หน้าข้อความที่ขึ้นต้นด้วย =, +, - หรือ @ เพื่อไม่ให้ Spreadsheet ตีความเป็นสูตรเมื่อเปิดไฟล์ จำนวนลบที่เป็นตัวเลขจริงยังส่งออกเป็นตัวเลขตามเดิม" },
      { question: "ไฟล์ถูกอัปโหลดไปที่ Server หรือไม่?", answer: "ไม่ ไฟล์ .xlsx ถูกอ่านและแปลงใน Web Worker ของ Browser เท่านั้น Meaw Tools ไม่มี API รับหรือบันทึก Workbook และการดาวน์โหลดถูกสร้างภายในอุปกรณ์" },
      { question: "รองรับ Workbook ใหญ่เท่าไร?", answer: "รองรับสูงสุด 10 MB, 50 Worksheet, 50,000 แถวต่อชีต, 200 คอลัมน์ต่อชีต และ 500,000 เซลล์รวม งานหนักทำใน Web Worker เพื่อลดการค้างของหน้าเว็บ" },
    ],
  },
  {
    slug: "csv-cleaner",
    name: "CSV Cleaner & Duplicate Finder",
    thaiName: "ล้างข้อมูลซ้ำใน CSV ออนไลน์",
    shortDescription: "ตัดช่องว่าง ลบแถวว่าง และตรวจหาข้อมูลซ้ำตามคอลัมน์ที่เลือก",
    description: "ล้างข้อมูล CSV ออนไลน์ฟรีด้วยการตัดช่องว่าง ลบแถวว่าง และค้นหาหรือลบข้อมูลซ้ำตาม ID, Email, SKU หรือหลายคอลัมน์ รองรับ CSV, TSV, UTF-8 และ Windows-874 พร้อมป้องกัน Formula Injection และประมวลผลใน Web Worker ของ Browser",
    category: "productivity",
    icon: "ListFilter",
    keywords: ["csv cleaner", "csv cleaner online", "csv duplicate remover", "remove duplicate rows online", "data cleaner", "clean csv file", "ลบข้อมูลซ้ำ csv", "ลบแถวซ้ำ", "ตรวจข้อมูลซ้ำ", "ล้างข้อมูล csv", "duplicate finder", "csv formula injection"],
    isPopular: true,
    isNew: true,
    relatedTools: ["csv-to-excel", "text-cleaner", "json-formatter"],
    howTo: ["เลือกไฟล์ CSV, TSV หรือ TXT หรือวางข้อความ แล้วเลือก Encoding, ตัวคั่น และระบุว่าแถวแรกเป็นหัวตารางหรือไม่", "กดวิเคราะห์ เลือกคอลัมน์สำหรับเทียบข้อมูลซ้ำ เช่น Email หรือ SKU แล้วตั้งค่าตัดช่องว่าง ลบแถวว่าง แยกตัวพิมพ์เล็ก-ใหญ่ และเก็บแถวแรกหรือแถวสุดท้าย", "กดทำความสะอาด ตรวจจำนวนแถวที่พบและลบ Preview และเซลล์ที่ป้องกัน Formula Injection แล้วดาวน์โหลด UTF-8 CSV"],
    example: "002,SOMCHAI@example.com, สมชาย  + 002,somchai@example.com,สมชาย → เลือก Email และไม่แยกตัวพิมพ์เล็ก-ใหญ่ → เก็บ 1 แถว",
    caution: "การลบข้อมูลซ้ำอาจทำให้ข้อมูลสูญหายหากเลือกคอลัมน์ไม่ครบ ควรตรวจจำนวนแถวและ Preview ก่อนดาวน์โหลด การป้องกัน Formula Injection จะเติม Tab หน้าเซลล์เสี่ยง ซึ่งเหมาะกับไฟล์ที่เปิดใน Spreadsheet แต่อาจกระทบระบบนำเข้าข้อมูลอัตโนมัติ",
    faq: [...commonFaq,
      { question: "เครื่องมือตัดสินอย่างไรว่าแถวซ้ำกัน?", answer: "เครื่องมือสร้างคีย์จากคอลัมน์ที่คุณเลือก หากค่าของทุกคอลัมน์ในคีย์เท่ากันจะถือว่าเป็นกลุ่มซ้ำ ค่าเริ่มต้นเลือกทุกคอลัมน์เพื่อป้องกันการลบแถวที่ต่างกันโดยไม่ตั้งใจ" },
      { question: "ตรวจซ้ำเฉพาะ Email, ID หรือ SKU ได้หรือไม่?", answer: "ได้ หลังวิเคราะห์ไฟล์ให้เลือกเฉพาะคอลัมน์ที่ต้องการเทียบ คุณเลือกได้หลายคอลัมน์และกำหนดว่าจะเก็บแถวแรกหรือแถวสุดท้ายของแต่ละกลุ่ม" },
      { question: "แถวที่ Email หรือ ID ว่างจะถูกลบรวมกันหรือไม่?", answer: "ค่าเริ่มต้นไม่ลบรวม เครื่องมือข้ามแถวที่ทุกคอลัมน์ของคีย์ว่าง เพื่อป้องกันข้อมูลหลายรายการที่ยังไม่มี Email หรือ ID ถูกมองว่าเป็นรายการเดียว" },
      { question: "รองรับภาษาไทยและไฟล์จาก Excel รุ่นเก่าหรือไม่?", answer: "รองรับ UTF-8 และ Windows-874 สำหรับไฟล์ภาษาไทยเดิม พร้อม comma, tab, semicolon, pipe, quoted field, quote ซ้อน และข้อความหลายบรรทัด" },
      { question: "CSV Formula Injection คืออะไร?", answer: "โปรแกรม Spreadsheet อาจตีความเซลล์ที่ขึ้นต้นด้วย =, +, - หรือ @ เป็นสูตร เครื่องมือเปิดการป้องกันตามแนวทาง OWASP เป็นค่าเริ่มต้นและรายงานจำนวนเซลล์ที่ถูกเติม Tab หน้าเนื้อหา" },
      { question: "ทำไมต้องตรวจ Preview ก่อนดาวน์โหลด?", answer: "การเลือกคอลัมน์หรือเงื่อนไขตัวพิมพ์เล็ก-ใหญ่อาจเปลี่ยนจำนวนแถวที่ถือว่าซ้ำ Preview และสรุปจำนวนช่วยยืนยันว่ากฎตรงกับข้อมูลจริงก่อนนำไฟล์ไปใช้ต่อ" },
      { question: "ไฟล์ผลลัพธ์ใช้กับระบบนำเข้าข้อมูลอัตโนมัติได้หรือไม่?", answer: "ได้ในหลายระบบเพราะเป็น UTF-8 CSV และ quote ทุกเซลล์ แต่หากระบบปลายทางต้องรักษาค่าเดิมแบบ byte-for-byte ให้ตรวจผลของการตัดช่องว่างและปิด Formula protection โดยยอมรับความเสี่ยงตาม workflow ของคุณ" },
      { question: "รองรับไฟล์ใหญ่เท่าไร?", answer: "รองรับสูงสุด 10 MB, 50,000 แถว, 200 คอลัมน์ และ 500,000 เซลล์ต่อครั้ง งานหนักทำใน Web Worker เพื่อลดการค้างของหน้าเว็บ" },
    ],
  },
  {
    slug: "typing-test",
    name: "Typing Test",
    thaiName: "ทดสอบความเร็วพิมพ์ ไทย/อังกฤษ",
    shortDescription: "วัด WPM, CPM และความแม่นยำ พร้อมข้อความฝึกภาษาไทยและอังกฤษ",
    description: "ทดสอบความเร็วพิมพ์ออนไลน์ฟรีทั้งภาษาไทยและอังกฤษ เลือกเวลาและข้อความฝึกได้ แสดง WPM, CPM, ความแม่นยำ ตัวอักษรถูก-ผิด และความคืบหน้าแบบทันที",
    category: "productivity",
    icon: "Keyboard",
    keywords: ["typing test", "ฝึกพิมพ์ดีด", "พิมพ์ดีด", "ฝึกพิมพ์", "ทดสอบความเร็วพิมพ์", "typing speed test", "wpm test", "ฝึกพิมพ์ภาษาไทย"],
    isPopular: true,
    isNew: true,
    relatedTools: ["word-counter", "text-cleaner", "random-wheel"],
    howTo: ["เลือกภาษา ระยะเวลา และข้อความที่ต้องการฝึก", "เริ่มพิมพ์ตามข้อความด้านบน ระบบจะเริ่มจับเวลาอัตโนมัติ", "ตรวจ WPM, CPM, ความแม่นยำ และจำนวนตัวอักษรถูก-ผิด แล้วเริ่มรอบใหม่"],
    example: "ข้อความถูก 250 ตัว ใน 60 วินาที → 50 WPM · 250 CPM · ความแม่นยำ 98%",
    caution: "WPM ใช้มาตรฐานอักขระที่ถูกต้อง 5 ตัวเท่ากับ 1 คำ ภาษาไทยจึงเป็นค่าประมาณสำหรับเปรียบเทียบพัฒนาการของแต่ละรอบ ไม่ใช่มาตรฐานรับรองวิชาชีพ",
    faq: [...commonFaq,
      { question: "WPM คำนวณอย่างไร?", answer: "นำจำนวนอักขระที่พิมพ์ถูกต้องหาร 5 แล้วหารด้วยเวลาที่ใช้เป็นนาที ระบบใช้ความเร็วสุทธิจึงไม่นับตัวอักษรที่ผิดตำแหน่ง" },
      { question: "ใช้ทดสอบภาษาไทยได้แม่นยำหรือไม่?", answer: "ระบบแบ่งข้อความเป็น grapheme เพื่อรวมสระและวรรณยุกต์ที่เป็นอักขระผสม แต่ WPM ภาษาไทยยังเป็นค่าประมาณ เพราะภาษาไทยไม่ได้เว้นวรรคทุกคำเหมือนภาษาอังกฤษ" },
      { question: "แก้คำผิดด้วย Backspace ได้หรือไม่?", answer: "ได้ ความแม่นยำและจำนวนผิดจะแสดงจากข้อความปัจจุบันหลังแก้ไข จึงเหมาะกับการฝึกทั้งความเร็วและความถูกต้อง" },
      { question: "สามารถวางข้อความเพื่อให้ได้คะแนนเร็วขึ้นหรือไม่?", answer: "ไม่ได้ เครื่องมือปิดการ Paste และ Drop ในช่องทดสอบ เพื่อให้ผลสะท้อนการพิมพ์จริง" },
      { question: "ข้อความที่พิมพ์ถูกส่งหรือบันทึกหรือไม่?", answer: "ไม่ การเปรียบเทียบและคำนวณทั้งหมดเกิดใน Browser ข้อความและผลทดสอบจะหายเมื่อรีเฟรชหน้า" },
    ],
  },
  {
    slug: "special-characters",
    name: "Special Characters & Fancy Text",
    thaiName: "อักษรพิเศษ คัดลอกและแต่งชื่อ",
    shortDescription: "สร้างข้อความ Unicode แต่งชื่อ และคัดลอกสัญลักษณ์พิเศษตามหมวด",
    description: "รวมตัวอักษรพิเศษ อักษรพิเศษ สัญลักษณ์ และข้อความ Unicode สำหรับแต่งชื่อเกม Bio และ Caption ค้นหาหัวใจ ดาว ปีก ลูกศร เลขโรมัน และคัดลอกได้ทันทีโดยไม่ต้องสมัครสมาชิก",
    category: "text",
    icon: "Sparkles",
    keywords: ["ตัวอักษรพิเศษ", "อักษรพิเศษ", "สัญลักษณ์พิเศษ", "ฟอนต์พิเศษ", "แต่งชื่อเกม", "อักษรพิเศษปีก", "เลขโรมัน", "emoji copy", "special characters", "fancy text"],
    isPopular: true,
    isNew: true,
    relatedTools: ["text-cleaner", "word-counter", "typing-test"],
    howTo: ["กรอกชื่อหรือข้อความเพื่อสร้างรูปแบบ Unicode และกรอบตกแต่ง", "กดคัดลอกผลลัพธ์ หรือค้นหาและเลือกหมวดสัญลักษณ์ที่ต้องการ", "นำข้อความไปวางในแอปหรือเกม แล้วตรวจว่าระบบปลายทางรองรับอักษรนั้น"],
    example: "Meaw → 𝐌𝐞𝐚𝐰 · Ⓜⓔⓐⓦ · 『Meaw』\nหัวใจ → ♡ ♥ ❥ · เลขโรมัน → Ⅰ Ⅱ Ⅲ",
    caution: "อักษรแบบพิเศษคือ Unicode ไม่ใช่ไฟล์ Font รูปลักษณ์และการรองรับอาจต่างกันตามอุปกรณ์ เกม หรือแอป และไม่ควรใช้แทนข้อความปกติในข้อมูลสำคัญหรือเนื้อหาที่ต้องเข้าถึงด้วย Screen Reader",
    faq: [...commonFaq,
      { question: "อักษรพิเศษใช้งานกับภาษาไทยได้หรือไม่?", answer: "กรอบตกแต่งและสัญลักษณ์ใช้กับภาษาไทยได้ ส่วนสไตล์ตัวหนา ตัวเอียง โมโนสเปซ และตัววงกลมเปลี่ยนเฉพาะตัวอักษรอังกฤษ A–Z, a–z และตัวเลขที่ Unicode รองรับ" },
      { question: "ทำไมบางตัวแสดงเป็นสี่เหลี่ยมหรือวางในเกมไม่ได้?", answer: "อุปกรณ์และเกมแต่ละระบบรองรับชุด Unicode ไม่เท่ากัน หากเห็นสี่เหลี่ยมหรือระบบไม่รับชื่อ ให้ลองรูปแบบที่เรียบง่ายขึ้นหรือใช้ตัวอักษรปกติ" },
      { question: "นี่คือการเปลี่ยน Font จริงหรือไม่?", answer: "ไม่ ผลลัพธ์เป็นอักขระ Unicode คนละรหัสที่มีรูปร่างคล้าย Font จึงคัดลอกไปใช้ได้โดยไม่ต้องติดตั้งไฟล์ Font" },
      { question: "ค้นหาสัญลักษณ์ภาษาไทยได้อย่างไร?", answer: "ค้นด้วยคำอย่าง หัวใจ ดาว ปีก นางฟ้า คิตตี้ ลูกศร เลขโรมัน คณิตศาสตร์ หรือเลือกหมวดเพื่อดูรายการทั้งหมด" },
      { question: "ระบบเก็บข้อความหรือรายการที่คัดลอกหรือไม่?", answer: "ไม่ ข้อความและรายการล่าสุดอยู่ในหน้านี้ชั่วคราวเท่านั้น ไม่ถูกอัปโหลดหรือบันทึก และจะหายเมื่อรีเฟรช" },
    ],
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech Reader",
    thaiName: "อ่านข้อความเป็นเสียง",
    shortDescription: "ฟังข้อความภาษาไทยและอังกฤษด้วยเสียงจาก Browser หรือระบบ",
    description: "อ่านข้อความเป็นเสียงออนไลน์ฟรีด้วย Web Speech API เลือกภาษา เสียง ความเร็ว โทนเสียง และความดัง พร้อมพัก อ่านต่อ และหยุดได้โดยไม่ต้องสมัครหรือใช้ API Key",
    category: "text",
    icon: "AudioLines",
    keywords: ["อ่านข้อความ", "แปลงข้อความเป็นเสียง", "อ่านข้อความเป็นเสียง", "อ่านออกเสียงข้อความ", "text to speech", "tts ไทย", "เสียงอ่านข้อความ", "อ่านภาษาไทย"],
    isPopular: true,
    isNew: true,
    relatedTools: ["word-counter", "text-cleaner", "typing-test"],
    howTo: ["วางข้อความหรือกดโหลดตัวอย่าง", "เลือกภาษาและเสียงที่อุปกรณ์มี แล้วปรับความเร็ว โทนเสียง หรือความดัง", "กดเริ่มอ่าน และใช้ปุ่มพัก อ่านต่อ หรือหยุดตามต้องการ"],
    example: "สวัสดีค่ะ ยินดีต้อนรับสู่ Meaw Tools → Browser อ่านข้อความด้วยเสียงภาษาไทยที่มีในอุปกรณ์",
    caution: "Meaw Tools ไม่ส่งข้อความไปยัง Server ของเรา แต่เสียงออนไลน์บางรายการอาจส่งข้อความไปประมวลผลกับผู้ให้บริการของ Browser หรือระบบปฏิบัติการ ไม่ควรใส่ข้อมูลลับ และเครื่องมือนี้ไม่สร้างไฟล์ MP3",
    faq: [...commonFaq,
      { question: "ข้อความถูกส่งไปที่ Server หรือไม่?", answer: "Meaw Tools ไม่รับหรือบันทึกข้อความ แต่เสียงที่ Browser ระบุว่าออนไลน์อาจประมวลผลผ่านผู้ให้บริการของ Browser หรือระบบปฏิบัติการ ควรเลือกเสียงในเครื่องและหลีกเลี่ยงข้อมูลลับ" },
      { question: "ดาวน์โหลดเป็น MP3 ได้หรือไม่?", answer: "ไม่ได้ Web Speech API ให้ Browser อ่านออกเสียง แต่ไม่ส่งข้อมูลเสียงกลับมาเป็นไฟล์ เครื่องมือนี้จึงไม่แสดงปุ่มดาวน์โหลดที่ใช้งานไม่ได้จริง" },
      { question: "ทำไมเสียงในแต่ละเครื่องไม่เหมือนกัน?", answer: "รายชื่อ ภาษา และคุณภาพเสียงมาจาก Browser และระบบปฏิบัติการของอุปกรณ์นั้น บางเครื่องมีเสียงไทยหลายเสียง ขณะที่บางเครื่องอาจมีเฉพาะเสียงเริ่มต้น" },
      { question: "รองรับข้อความยาวเท่าไร?", answer: "รองรับสูงสุด 20,000 ตัวอักษร และแบ่งข้อความเป็นช่วงสั้นอัตโนมัติเพื่อช่วยให้ Browser อ่านต่อเนื่อง แต่บทความยาวมากยังขึ้นกับข้อจำกัดของอุปกรณ์" },
    ],
  },
  {
    slug: "grade-calculator",
    name: "Grade Calculator",
    thaiName: "คำนวณเกรดเฉลี่ย GPA และ GPAX",
    shortDescription: "คำนวณ GPA จากรายวิชาและประมาณ GPAX หลายเทอมแบบถ่วงหน่วยกิต",
    description: "คำนวณเกรดเฉลี่ย GPA และ GPAX ออนไลน์ฟรี รองรับเกรด A, B+, B, C+, C, D+, D, F และไม่นับ W/S/U คำนวณจากรายวิชาหรือถ่วงน้ำหนักหลายเทอม พร้อมแสดงทั้งค่าปัดและค่าตัดทศนิยมภายใน Browser",
    category: "calculator",
    icon: "GraduationCap",
    keywords: ["คำนวณเกรด", "คำนวณเกรดเฉลี่ย", "คำนวณเกรดเฉลี่ยสะสม", "คำนวณเกรดมหาลัย", "คำนวณเกรด 4 เทอม", "คำนวณเกรด 5 เทอม", "คำนวณเกรด 6 เทอม", "คำนวณ gpa", "คำนวณ gpax", "grade calculator", "gpa calculator", "gpax calculator"],
    isPopular: true,
    isNew: true,
    relatedTools: ["percentage-calculator", "date-calculator", "age-calculator"],
    howTo: ["เลือกคำนวณจากรายวิชาหรือ GPA หลายภาคเรียน", "กรอกหน่วยกิตและเกรดของแต่ละรายการ แล้วเพิ่มหรือลบแถวตามจริง", "กดคำนวณ ตรวจสูตร คะแนนถ่วงน้ำหนัก และเทียบค่าปัดกับค่าตัดทศนิยม"],
    example: "45 คะแนน ÷ 19 หน่วยกิต = GPA 2.3684 → ปัด 2.37 / ตัด 2.36",
    caution: "ผลลัพธ์เป็นเครื่องมือช่วยตรวจและวางแผน เกณฑ์เกรด การปัดเศษ วิชาเรียนซ้ำ วิชาโอน และสถานะที่ไม่นับอาจต่างกันตามสถาบัน ควรยึด GPA/GPAX จากฝ่ายทะเบียนสำหรับการสมัครเรียน ทุน หรือเอกสารทางการ",
    faq: [...commonFaq,
      { question: "GPA และ GPAX ต่างกันอย่างไร?", answer: "GPA คือเกรดเฉลี่ยของช่วงหรือภาคเรียนหนึ่ง ส่วน GPAX คือเกรดเฉลี่ยสะสมหลายภาคเรียน โดยทั้งสองต้องถ่วงตามหน่วยกิตที่นำมาคำนวณ" },
      { question: "คำนวณจากรายวิชาอย่างไร?", answer: "นำหน่วยกิตคูณแต้มเกรดของแต่ละวิชา รวมคะแนนทั้งหมด แล้วหารด้วยหน่วยกิตของวิชาที่นับ เช่น A = 4.00, B+ = 3.50 และ F = 0.00" },
      { question: "W, S และ U ถูกนำมาคำนวณหรือไม่?", answer: "เครื่องมือนี้ตั้งค่า W, S และ U เป็นไม่นับ GPA ตามตัวอย่างคู่มือมหาวิทยาลัยแม่ฟ้าหลวง แต่ควรตรวจระเบียบของสถาบันตนเองอีกครั้ง" },
      { question: "ทำไมแสดงทั้งค่าปัดและค่าตัดทศนิยม?", answer: "สถาบันอาจมีวิธีแสดงผลทศนิยมต่างกัน เครื่องมือจึงแสดงค่าคำนวณละเอียด พร้อมค่าปัดและค่าตัดสองตำแหน่งให้เทียบ โดยไม่เลือกนโยบายแทนฝ่ายทะเบียน" },
      { question: "ทำไม GPAX หลายเทอมเป็นค่าประมาณ?", answer: "GPA รายเทอมที่ผู้ใช้กรอกอาจถูกปัดหรือตัดทศนิยมมาแล้ว การถ่วงจากค่าที่แสดงจึงอาจต่างเล็กน้อยจากฝ่ายทะเบียนซึ่งใช้คะแนนสะสมที่ละเอียดกว่า" },
      { question: "นำผลลัพธ์ไปสมัครมหาวิทยาลัยหรือทุนได้หรือไม่?", answer: "ใช้ตรวจและวางแผนได้ แต่เอกสารสมัครควรใช้ GPA/GPAX จากระเบียนผลการศึกษาหรือฝ่ายทะเบียนเท่านั้น" },
    ],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    thaiName: "คำนวณเปอร์เซ็นต์",
    shortDescription: "หาเปอร์เซ็นต์ สัดส่วน และอัตราการเปลี่ยนแปลง",
    description: "คำนวณ X% ของจำนวน เปลี่ยนจำนวนเป็นเปอร์เซ็นต์ และหาเปอร์เซ็นต์เพิ่มหรือลด เหมาะกับงานขาย บัญชี และการวิเคราะห์ทั่วไป",
    category: "calculator",
    icon: "Percent",
    keywords: ["เปอร์เซ็นต์", "ส่วนลด", "percentage", "ยอดขาย", "เพิ่มขึ้น", "ลดลง"],
    isPopular: true,
    isNew: true,
    relatedTools: ["vat-calculator", "unit-converter", "date-calculator"],
    howTo: ["เลือกรูปแบบการคำนวณ", "กรอกตัวเลขสองช่อง", "กดคำนวณและตรวจสูตรใต้ผลลัพธ์"],
    example: "15% ของ 200 = 30",
    caution: "ผลลัพธ์อัตราเปลี่ยนแปลงใช้ค่าสัมบูรณ์ของค่าเริ่มต้นเป็นฐาน และไม่รองรับค่าเริ่มต้นเป็นศูนย์",
    faq: commonFaq,
  },
  {
    slug: "vat-calculator",
    name: "VAT Calculator Thailand",
    thaiName: "คำนวณ VAT 7% และถอด VAT",
    shortDescription: "บวกหรือถอด VAT จากราคารวม พร้อม Service Charge และหัก ณ ที่จ่าย",
    description: "คำนวณ VAT ออนไลน์สำหรับประเทศไทย บวก VAT จากราคาก่อนภาษีหรือถอด VAT จากราคารวมด้วยสูตร 7/107 รองรับ Service Charge อัตราแก้ไขได้ และประมาณภาษีหัก ณ ที่จ่ายแยกต่างหาก พร้อมอ้างอิงอัตราปัจจุบันจากกรมสรรพากร",
    category: "calculator",
    icon: "Percent",
    keywords: ["คำนวณ vat", "คำนวณ vat 7", "vat calculator thailand", "คำนวณ vat ย้อนกลับ", "ถอด vat 7", "สูตร vat 7/107", "ราคาก่อน vat", "ราคารวม vat", "คำนวณ service charge vat", "vat 7 ออนไลน์", "คำนวณภาษีมูลค่าเพิ่ม", "คำนวณภาษีหัก ณ ที่จ่าย 3"],
    isPopular: true,
    isNew: true,
    relatedTools: ["quotation-generator", "profit-margin-calculator", "percentage-calculator"],
    howTo: ["เลือกบวก VAT หากราคายังไม่รวมภาษี หรือเลือกถอด VAT หากยอดที่มีรวม VAT แล้ว", "กรอกยอดและตรวจอัตรา VAT โดยสามารถเพิ่ม Service Charge ก่อน VAT และเปิดประมาณภาษีหัก ณ ที่จ่ายได้", "กดคำนวณ ตรวจฐานก่อน VAT สูตร ยอดภาษี ยอดรวม และยอดจ่ายสุทธิก่อนคัดลอกสรุป"],
    example: "ราคา 1,000 บาท + Service Charge 10% = ฐาน VAT 1,100 บาท + VAT 7% 77 บาท = 1,177 บาท; ถ้าหัก ณ ที่จ่าย 3% ของฐานก่อน VAT จะจ่ายสุทธิ 1,144 บาท",
    caution: "VAT และภาษีหัก ณ ที่จ่ายเป็นคนละภาษี อัตรา 3% ไม่ได้ใช้กับทุกกรณี และสินค้า บริการ หรือกิจการบางประเภทอาจยกเว้นหรือใช้อัตราอื่น ผลลัพธ์ปัดแต่ละองค์ประกอบเป็น 2 ตำแหน่งและเป็นเพียงตัวช่วยตรวจ ไม่ใช่คำแนะนำภาษีหรือใบกำกับภาษี",
    faq: [...commonFaq,
      { question: "บวก VAT กับถอด VAT ต่างกันอย่างไร?", answer: "บวก VAT ใช้เมื่อราคายังไม่รวมภาษี โดย VAT = ฐานก่อน VAT × อัตรา/100 ส่วนถอด VAT ใช้เมื่อยอดรวมภาษีแล้ว โดย VAT = ราคารวม × อัตรา/(100 + อัตรา)" },
      { question: "ถอด VAT 7% จากราคารวมใช้สูตรอะไร?", answer: "ใช้ VAT = ราคารวม × 7/107 แล้วนำ VAT ไปลบจากราคารวมเพื่อหาฐานก่อน VAT เช่น 1,070 × 7/107 = VAT 70 บาท และราคาก่อน VAT 1,000 บาท" },
      { question: "VAT ไทยยังเป็น 7% ถึงเมื่อไร?", answer: "กรมสรรพากรยืนยันเมื่อ 2 สิงหาคม 2569 ว่า VAT สำหรับการขายสินค้าและบริการทั่วไปยัง 7% และการขยายปัจจุบันถึง 30 กันยายน 2570 เครื่องมือแสดงวันที่ตรวจสอบและให้อัตราแก้ไขได้เพราะกฎหมายอาจเปลี่ยน" },
      { question: "Service Charge คิดก่อนหรือหลัง VAT?", answer: "เครื่องมือนี้ใช้ลำดับราคาตั้งต้น + Service Charge แล้วคำนวณ VAT จากยอดดังกล่าว แต่บิลหรือข้อตกลงจริงอาจมีเงื่อนไขต่างกัน จึงควรตรวจฐานภาษีในเอกสารจริง" },
      { question: "VAT 7% กับหัก ณ ที่จ่าย 3% เหมือนกันหรือไม่?", answer: "ไม่เหมือนกัน VAT เป็นภาษีมูลค่าเพิ่ม ส่วนภาษีหัก ณ ที่จ่ายเป็นการนำส่งภาษีเงินได้ล่วงหน้า อัตราหักจริงขึ้นกับประเภทเงินได้ ผู้จ่าย และผู้รับ จึงปิดเป็นค่าเริ่มต้นและไม่เลือกอัตราแทนผู้ใช้" },
      { question: "ทำไมยอดอาจต่างจากใบกำกับภาษีเล็กน้อย?", answer: "เอกสารจริงอาจคำนวณและปัดเศษ VAT รายบรรทัดก่อนรวม ขณะที่เครื่องมือนี้คำนวณจากยอดฐานรวมและปัดแต่ละองค์ประกอบเป็น 2 ตำแหน่ง ส่วนลดและรายการยกเว้นก็ทำให้ฐานต่างกันได้" },
      { question: "เครื่องมือนี้สร้างใบกำกับภาษีได้หรือไม่?", answer: "ไม่ได้ เครื่องมือนี้ช่วยคำนวณและอธิบายสูตรเท่านั้น หากต้องออกเอกสารควรใช้ระบบบัญชีและตรวจองค์ประกอบใบกำกับภาษีตามข้อกำหนดของกิจการ" },
      { question: "ยอดเงินถูกส่งไปที่ Server หรือไม่?", answer: "ไม่ การคำนวณทำใน Browser ของคุณ ไม่มี API ของ Meaw Tools รับหรือบันทึกยอดที่กรอก" },
    ],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    thaiName: "แปลงหน่วย",
    shortDescription: "แปลงความยาว น้ำหนัก อุณหภูมิ พื้นที่ และข้อมูล",
    description: "แปลงหน่วยที่ใช้ในชีวิตประจำวันและการทำงาน รวมหน่วยพื้นที่ไทยอย่างไร่ งาน และตารางวา พร้อมหน่วยดิจิทัลฐาน 10 และฐาน 2",
    category: "calculator",
    icon: "Ruler",
    keywords: ["แปลงหน่วย", "ไร่", "ตารางวา", "กิโลกรัม", "เมตร", "unit converter"],
    isPopular: true,
    isNew: true,
    relatedTools: ["percentage-calculator", "date-calculator", "timestamp-converter"],
    howTo: ["เลือกประเภทหน่วย", "กรอกค่าและเลือกหน่วยต้นทาง", "เลือกหน่วยปลายทางเพื่อดูผลลัพธ์ทันที"],
    example: "10 เมตร = 32.8083989501 ฟุต",
    caution: "ค่าที่แสดงถูกปัดเพื่อให้อ่านง่าย ไม่ควรใช้แทนเครื่องมือสอบเทียบในงานที่ต้องการความเที่ยงตรงสูง",
    faq: commonFaq,
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    thaiName: "คำนวณวันและระยะเวลา",
    shortDescription: "หาระยะห่าง บวกหรือลบวัน และนับวันทำงาน",
    description: "คำนวณจำนวนวันระหว่างสองวันที่ หรือบวกและลบวันจากวันที่ตั้งต้น พร้อมตัวเลือกนับเฉพาะวันจันทร์ถึงศุกร์",
    category: "calculator",
    icon: "CalendarDays",
    keywords: ["คำนวณวัน", "วันทำงาน", "date calculator", "ระยะเวลา", "กำหนดส่ง", "hr"],
    isPopular: true,
    isNew: true,
    relatedTools: ["timestamp-converter", "percentage-calculator", "unit-converter"],
    howTo: ["เลือกหาระยะห่างหรือบวก/ลบวัน", "กรอกวันที่และจำนวนวันที่เกี่ยวข้อง", "อ่านผลลัพธ์และหมายเหตุการนับวันทำงาน"],
    example: "2026-08-02 + 30 วัน = 2026-09-01",
    caution: "โหมดวันทำงานไม่นับเสาร์-อาทิตย์ แต่ยังไม่หักวันหยุดนักขัตฤกษ์ของแต่ละประเทศหรือองค์กร",
    faq: commonFaq,
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF Converter",
    thaiName: "แปลง JPG เป็น PDF",
    shortDescription: "รวมรูป JPG และ PNG หลายไฟล์เป็น PDF",
    description: "เรียงและรวมรูป JPG หรือ PNG เป็นไฟล์ PDF พร้อมเลือกขนาดหน้าและระยะขอบ โดยไฟล์ไม่ถูกอัปโหลดออกจากอุปกรณ์",
    category: "media",
    icon: "FileImage",
    keywords: ["แปลง jpg เป็น pdf", "jpg to pdf", "รูปเป็น pdf", "รวมรูป pdf", "png to pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["pdf-to-jpg", "merge-pdf", "image-compressor"],
    howTo: ["เลือกรูป JPG หรือ PNG ได้สูงสุด 20 ไฟล์", "จัดลำดับรูปและเลือกรูปแบบหน้ากระดาษ", "กดสร้าง PDF แล้วดาวน์โหลดไฟล์"],
    example: "photo-01.jpg + photo-02.png → meaw-images.pdf",
    caution: "รองรับไฟล์ละไม่เกิน 10 MB และรวมไม่เกิน 50 MB ควรตรวจทิศทางรูปจากกล้องก่อนสร้าง PDF",
    faq: commonFaq,
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    thaiName: "สร้าง QR Code ฟรี",
    shortDescription: "สร้าง QR Code จากลิงก์หรือข้อความพร้อมดาวน์โหลด",
    description: "สร้าง QR Code จาก URL หรือข้อความ เลือกขนาด สี และระดับการแก้ไขข้อผิดพลาด พร้อมดาวน์โหลด PNG หรือ SVG",
    category: "media",
    icon: "QrCode",
    keywords: ["สร้าง qr code", "qr code generator", "คิวอาร์โค้ด", "qr ฟรี", "ดาวน์โหลด qr"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-pdf", "image-compressor", "url-encoder"],
    howTo: ["วางลิงก์หรือข้อความที่ต้องการ", "เลือกขนาด สี และระดับการแก้ไขข้อผิดพลาด", "กดสร้างแล้วดาวน์โหลดเป็น PNG หรือ SVG"],
    example: "https://meaw-tools.vercel.app",
    caution: "ควรสแกนทดสอบก่อนนำไปพิมพ์จริง และใช้สีพื้นกับสีจุดที่มีความต่างกันชัดเจน",
    faq: commonFaq,
  },
  {
    slug: "qr-code-scanner",
    name: "QR Code Scanner",
    thaiName: "สแกน QR Code จากรูปและกล้อง",
    shortDescription: "อ่าน QR Code จากรูปหรือกล้องโดยไม่อัปโหลดข้อมูล",
    description: "อ่าน QR Code จากไฟล์ PNG, JPG, WebP หรือกล้อง แยกประเภทข้อความและแสดงโดเมนให้ตรวจสอบก่อนเปิดลิงก์ โดยประมวลผลภายใน Browser",
    category: "media",
    icon: "ScanLine",
    keywords: ["สแกน qr code", "อ่าน qr code", "สแกน qr code จากรูป", "qr code scanner", "qr code reader", "scan qr code online"],
    isPopular: true,
    isNew: true,
    relatedTools: ["qr-code-generator", "image-compressor", "png-to-jpg"],
    howTo: ["อัปโหลดรูป QR Code หรือเลือกใช้กล้อง", "จัด QR Code ให้เห็นครบทั้งสี่มุมและรอผลการอ่าน", "ตรวจประเภทข้อมูลและชื่อโดเมนก่อนคัดลอกหรือเปิดลิงก์"],
    example: "QR Code ที่มี https://meaw-tools.vercel.app → ลิงก์เว็บไซต์ meaw-tools.vercel.app",
    caution: "เครื่องมือไม่เปิดลิงก์อัตโนมัติและไม่ได้รับรองว่าปลายทางปลอดภัย ควรตรวจชื่อโดเมนก่อนเปิดทุกครั้ง และอนุญาตกล้องเฉพาะเมื่อใช้งาน",
    faq: [...commonFaq, { question: "สแกนแล้วระบบจะเปิดลิงก์ทันทีหรือไม่?", answer: "ไม่ ระบบจะแสดงข้อความและชื่อโดเมนก่อน ผู้ใช้ต้องกดเปิดลิงก์เองเพื่อลดความเสี่ยงจาก QR Code ที่ไม่รู้แหล่งที่มา" }],
  },
  {
    slug: "image-to-text",
    name: "Image to Text OCR",
    thaiName: "แปลงรูปเป็นข้อความด้วย OCR",
    shortDescription: "อ่านข้อความภาษาไทยและอังกฤษจากรูปโดยไม่อัปโหลด",
    description: "แปลง PNG, JPG หรือ WebP เป็นข้อความภาษาไทยและอังกฤษด้วย OCR ภายใน Browser พร้อมแก้ไข คัดลอก และดาวน์โหลด TXT",
    category: "media",
    icon: "ScanText",
    keywords: ["แปลงรูปเป็นข้อความ", "อ่านข้อความจากรูป", "คัดลอกข้อความจากรูป", "image to text", "ocr ไทย", "ocr online", "photo to text"],
    isPopular: true,
    isNew: true,
    relatedTools: ["qr-code-scanner", "image-compressor", "png-to-jpg"],
    howTo: ["เลือกรูป PNG, JPG หรือ WebP ที่เห็นข้อความชัดเจน", "เลือกภาษาและรูปแบบข้อความ แล้วกดอ่านข้อความจากรูป", "เทียบผลกับต้นฉบับ แก้ไข แล้วคัดลอกหรือดาวน์โหลด TXT"],
    example: "รูปป้ายหรือเอกสารที่มี “MEAW TOOLS · แปลงรูปเป็นข้อความ” → ข้อความที่แก้ไขและคัดลอกได้",
    caution: "OCR อาจอ่านผิดเมื่อรูปเบลอ เอียง แสงไม่สม่ำเสมอ ลายมือ ฟอนต์ตกแต่ง หรือตารางซับซ้อน ควรตรวจตัวเลข ชื่อ ยอดเงิน และข้อมูลสำคัญกับรูปต้นฉบับทุกครั้ง",
    faq: [...commonFaq,
      { question: "รองรับภาษาอะไร?", answer: "รองรับภาษาไทย ภาษาอังกฤษ หรือเลือกอ่านทั้งสองภาษาพร้อมกัน โดยโหลดโมเดลเมื่อเริ่มใช้งาน" },
      { question: "OCR รับรองว่าข้อความถูกต้องหรือไม่?", answer: "ไม่ ค่า Confidence เป็นเพียงสัญญาณจากระบบ ควรตรวจและแก้ผลลัพธ์กับรูปต้นฉบับก่อนนำไปใช้เสมอ" },
    ],
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    thaiName: "สร้างบาร์โค้ดออนไลน์",
    shortDescription: "สร้างบาร์โค้ดสินค้าและสต็อกหลายรายการเป็น PNG หรือ SVG",
    description: "สร้างบาร์โค้ดออนไลน์ฟรีจากรหัสสินค้า SKU หรือเลข GTIN รองรับ Code 128, EAN-13, EAN-8, UPC-A, ITF-14 และ Code 39 วางหลายรายการจาก Excel แล้วดาวน์โหลด PNG, SVG หรือ ZIP โดยประมวลผลภายใน Browser",
    category: "business",
    icon: "Barcode",
    keywords: ["สร้างบาร์โค้ด", "สร้างบาร์โค้ดฟรี", "สร้างบาร์โค้ด 13 หลัก", "สร้างบาร์โค้ดสินค้า", "barcode generator", "barcode generator free", "ean 13 barcode generator", "code 128", "itf 14", "barcode svg", "สร้างบาร์โค้ด excel"],
    isPopular: true,
    isNew: true,
    relatedTools: ["qr-code-generator", "quotation-generator", "image-compressor"],
    howTo: ["วางรหัสหนึ่งรายการต่อบรรทัด หรือคัดลอกหนึ่งคอลัมน์จาก Excel ได้สูงสุด 50 รายการ", "เลือกรูปแบบ ความกว้าง ความสูง และการแสดงตัวเลขใต้บาร์โค้ด", "กดสร้าง ตรวจตัวอย่าง แล้วดาวน์โหลด PNG, SVG หรือรวมหลายไฟล์เป็น ZIP"],
    example: "3 SKU → Code 128 PNG/SVG + ZIP",
    caution: "การสร้างภาพ EAN/UPC ไม่ได้จดทะเบียนหรือรับรองเลข GTIN สำหรับสินค้าจริง เลขหมายควรมาจาก GS1 Thailand และต้องสแกนทดสอบบนขนาด วัสดุ และเครื่องพิมพ์จริงก่อนผลิตจำนวนมาก",
    faq: [...commonFaq,
      { question: "รองรับบาร์โค้ดรูปแบบใดบ้าง?", answer: "รองรับ Code 128 สำหรับ SKU และงานทั่วไป, EAN-13/EAN-8/UPC-A สำหรับสินค้าปลีก, ITF-14 สำหรับกล่องขนส่ง และ Code 39 สำหรับรหัสทรัพย์สินหรืองานภายใน" },
      { question: "ระบบเติม Check Digit ให้หรือไม่?", answer: "เติมให้เมื่อกรอก EAN-13 จำนวน 12 หลัก, EAN-8 จำนวน 7 หลัก, UPC-A จำนวน 11 หลัก หรือ ITF-14 จำนวน 13 หลัก หากกรอกครบทุกหลัก ระบบจะตรวจ Check Digit และแจ้งเมื่อไม่ถูกต้อง" },
      { question: "นำเลขที่สร้างไปใช้ขายสินค้าได้ทันทีหรือไม่?", answer: "ภาพอาจสแกนได้แต่ไม่ได้ทำให้เลขเป็น GTIN ที่จดทะเบียน สินค้าที่ใช้ในระบบค้าปลีกควรใช้เลขหมายที่ได้รับและจัดการตามข้อกำหนดของ GS1 Thailand" },
      { question: "สร้างหลายรายการจาก Excel ได้อย่างไร?", answer: "คัดลอกคอลัมน์ที่มีรหัสจาก Excel แล้ววางในช่องข้อมูล ระบบอ่านหนึ่งบรรทัดเป็นหนึ่งบาร์โค้ด สูงสุด 50 รายการต่อครั้ง" },
      { question: "ควรดาวน์โหลด PNG หรือ SVG?", answer: "PNG เหมาะกับเอกสารและโปรแกรมทั่วไป ส่วน SVG เป็นเวกเตอร์ที่ขยายได้คมชัดกว่า เหมาะกับงานออกแบบและงานพิมพ์ แต่ทั้งสองแบบควรถูกสแกนทดสอบก่อนใช้งานจริง" },
    ],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    thaiName: "คำนวณอายุ",
    shortDescription: "คำนวณอายุเป็นปี เดือน วัน และวันเกิดครั้งถัดไป",
    description: "คำนวณอายุจากวันเกิดถึงวันที่กำหนด แสดงปี เดือน วัน จำนวนวันทั้งหมด และระยะเวลาถึงวันเกิดครั้งถัดไป",
    category: "calculator",
    icon: "CakeSlice",
    keywords: ["คำนวณอายุ", "age calculator", "อายุกี่ปี", "วันเกิด", "นับอายุ"],
    isPopular: true,
    isNew: true,
    relatedTools: ["date-calculator", "timestamp-converter", "percentage-calculator"],
    howTo: ["เลือกวันเดือนปีเกิด", "เลือกวันที่ที่ต้องการใช้อ้างอิงหรือกดวันนี้", "กดคำนวณเพื่อดูอายุและวันเกิดครั้งถัดไป"],
    example: "เกิด 15 มกราคม 2000 — คำนวณ ณ 2 สิงหาคม 2026",
    caution: "ผลลัพธ์ใช้วันที่ปฏิทินบนอุปกรณ์และคำนวณเพื่อข้อมูลทั่วไป ไม่ใช่การรับรองอายุตามข้อกฎหมาย",
    faq: commonFaq,
  },
  {
    slug: "utm-builder",
    name: "UTM Link Builder",
    thaiName: "สร้างลิงก์ UTM ออนไลน์",
    shortDescription: "สร้าง Campaign URL สำหรับติดตาม Source, Medium และ Campaign ใน GA4",
    description: "UTM Builder สำหรับสร้างลิงก์ UTM ออนไลน์ฟรีให้ Google Analytics 4 และแคมเปญการตลาด รองรับ utm_source, utm_medium, utm_campaign, utm_id, source platform, term และ content พร้อมรักษา query/hash เดิมและจัดชื่อให้สม่ำเสมอภายใน Browser",
    category: "business",
    icon: "Link2",
    keywords: ["utm builder", "utm builder google", "utm builder free", "utm link builder", "utm link builder google", "utm link builder free", "campaign url builder", "ga4 utm builder", "utm generator", "สร้างลิงก์ utm", "ติดตามแคมเปญ", "utm parameters"],
    isPopular: true,
    isNew: true,
    relatedTools: ["url-encoder", "qr-code-generator", "quotation-generator"],
    howTo: ["กรอก Website URL แล้วเลือก preset ช่องทางหรือกรอก Campaign Source, Medium และ Name", "เปิดตัวเลือกเพิ่มเติมเมื่อมี Campaign ID, Source Platform, Keyword หรือ Content ที่ต้องแยก", "กดสร้าง ตรวจ URL และรายการพารามิเตอร์ แล้วคัดลอกไปทดสอบก่อนเผยแพร่"],
    example: "https://example.com/sale?utm_source=facebook&utm_medium=paid_social&utm_campaign=august_sale",
    caution: "ค่าพารามิเตอร์ UTM แยกตัวพิมพ์เล็ก-ใหญ่ในรายงาน ควรใช้ naming convention เดียวกันทั้งทีม และควรตรวจ Google Ads auto-tagging ก่อนใส่ UTM ร่วมกับ GCLID เพราะอาจทำให้ attribution คลาดเคลื่อน",
    faq: [...commonFaq,
      { question: "UTM คืออะไร?", answer: "UTM เป็นพารามิเตอร์ใน URL ที่ช่วยให้ Google Analytics แยกแหล่งที่มา ช่องทาง แคมเปญ keyword และ creative ของ traffic ที่เข้ามาได้" },
      { question: "ช่องใดควรกรอกทุกครั้ง?", answer: "ควรกรอก utm_source, utm_medium และ utm_campaign ให้ครบ เพื่อป้องกันค่า (not set) และทำให้รายงานเทียบแคมเปญได้สม่ำเสมอ" },
      { question: "ทำไมเครื่องมือใช้ตัวพิมพ์เล็กเป็นค่าเริ่มต้น?", answer: "Google Analytics แยกค่าตามตัวพิมพ์เล็ก-ใหญ่ เช่น Facebook และ facebook อาจกลายเป็นคนละแถว การใช้ lowercase ช่วยลดข้อมูลแตกกระจาย" },
      { question: "URL ที่มี query หรือ #fragment เดิมจะหายหรือไม่?", answer: "ไม่ เครื่องมือเก็บพารามิเตอร์อื่นและ fragment เดิมไว้ แล้วแทนเฉพาะ UTM ที่เครื่องมือรองรับเพื่อไม่ให้เกิดค่าซ้ำ" },
      { question: "นำลิงก์ UTM เดิมกลับมาแก้ได้หรือไม่?", answer: "ได้ วาง URL ที่มี UTM แล้วกดอ่าน UTM จาก URL เครื่องมือจะแยก base URL และค่าพารามิเตอร์กลับมาให้แก้ไข" },
      { question: "ควรใส่ UTM ใน Google Ads ทุกลิงก์หรือไม่?", answer: "ไม่เสมอไป Google Ads มี auto-tagging และ GCLID การใส่ manual UTM ร่วมกันโดยไม่มีแผนอาจกระทบ attribution ควรตรวจการเชื่อม Google Ads กับ Analytics และทดสอบรายงานก่อน" },
      { question: "เครื่องมือเก็บหรือติดตามลิงก์ที่สร้างหรือไม่?", answer: "ไม่ การตรวจและประกอบ URL ทำภายใน Browser ไม่มี API ของ Meaw Tools รับหรือบันทึก URL แต่ปลายทางที่คุณเปิดอาจมีระบบติดตามของเว็บไซต์นั้นเอง" },
    ],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    thaiName: "คำนวณดอกเบี้ยเงินกู้",
    shortDescription: "ประมาณค่างวด ดอกเบี้ยรวม และตารางลดต้นลดดอก",
    description: "คำนวณค่างวดเงินกู้แบบลดต้นลดดอกด้วยอัตราคงที่ แสดงดอกเบี้ยรวม ยอดชำระรวม และรายละเอียดเงินต้นกับดอกเบี้ยแต่ละงวด",
    category: "business",
    icon: "Landmark",
    keywords: ["คำนวณดอกเบี้ย", "คำนวณเงินกู้", "loan calculator", "ค่างวด", "ลดต้นลดดอก", "ผ่อนบ้าน"],
    isPopular: true,
    isNew: true,
    relatedTools: ["profit-margin-calculator", "percentage-calculator", "unit-converter"],
    howTo: ["กรอกวงเงินกู้และอัตราดอกเบี้ยต่อปี", "กำหนดระยะเวลาผ่อนเป็นปีหรือเดือน", "กดคำนวณเพื่อดูค่างวดและตารางลดต้นลดดอก"],
    example: "วงเงิน 1,000,000 บาท · ดอกเบี้ย 6% ต่อปี · 20 ปี",
    caution: "ผลลัพธ์เป็นประมาณการจากอัตราคงที่และการชำระตรงเวลาทุกงวด ไม่รวมค่าธรรมเนียม ประกัน ภาษี หรืออัตราที่เปลี่ยนแปลงตามสัญญาจริง",
    faq: [...commonFaq, { question: "ใช้สูตรแบบใด?", answer: "ใช้หลักลดต้นลดดอกแบบชำระเท่ากันทุกเดือน โดยดอกเบี้ยแต่ละงวดคิดจากเงินต้นคงเหลือ" }],
  },
  {
    slug: "thai-income-tax-calculator",
    name: "Thai Income Tax Calculator",
    thaiName: "คำนวณภาษีเงินได้บุคคลธรรมดา",
    shortDescription: "ประมาณภาษีแบบขั้นบันไดจากเงินเดือนหรือเงินได้สุทธิ",
    description: "ประมาณภาษีเงินได้บุคคลธรรมดาไทยจากเงินเดือน หรือกรอกเงินได้สุทธิโดยตรง พร้อมแจกแจงค่าใช้จ่าย ค่าลดหย่อน ภาษีแต่ละขั้น และยอดเทียบภาษีหัก ณ ที่จ่าย",
    category: "business",
    icon: "BadgeDollarSign",
    keywords: ["คำนวณภาษี", "คำนวณภาษีเงินได้บุคคลธรรมดา", "คำนวณภาษีเงินเดือน", "ภาษี 2569", "ภงด 90", "ภงด 91", "tax calculator thailand"],
    isPopular: true,
    isNew: true,
    relatedTools: ["salary-calculator", "loan-calculator", "profit-margin-calculator"],
    howTo: ["เลือกคำนวณจากเงินเดือน หรือกรอกเงินได้สุทธิที่คำนวณมาแล้ว", "กรอกรายได้ ค่าลดหย่อนที่ใช้สิทธิได้ และภาษีหัก ณ ที่จ่าย", "กดคำนวณ แล้วตรวจที่มาของเงินได้สุทธิ ภาษีแต่ละขั้น และยอดคงเหลือ"],
    example: "เงินเดือน 50,000/เดือน · ประกันสังคม 9,000/ปี",
    caution: "เป็นการประมาณการเบื้องต้นสำหรับการวางแผน ไม่ใช่คำแนะนำทางภาษีหรือผลยื่นแบบจริง ไม่ครอบคลุมเงินได้และสิทธิทุกประเภท และผู้ใช้ต้องตรวจสอบกฎหมายกับหลักฐานของปีภาษีจริง",
    faq: [...commonFaq,
      { question: "คิดภาษีแบบขั้นบันไดอย่างไร?", answer: "เงินได้สุทธิแต่ละส่วนถูกคิดตามอัตราของช่วงนั้น ไม่ได้นำเงินได้ทั้งหมดคูณด้วยอัตราสูงสุดที่เข้าเกณฑ์" },
      { question: "ทำไมไม่ใส่ประกันสังคมให้อัตโนมัติ?", answer: "จำนวนที่ใช้สิทธิขึ้นกับยอดที่จ่ายจริงและกติกาของปีภาษี เครื่องมือจึงให้กรอกตามหลักฐานเพื่อลดความเสี่ยงจากข้อมูลที่เปลี่ยนแปลง" },
    ],
  },
  {
    slug: "salary-calculator",
    name: "Salary & Payslip Calculator",
    thaiName: "คำนวณเงินเดือนสุทธิและตรวจสลิป",
    shortDescription: "รวมรายรับ รายการหัก และตรวจยอดรับสุทธิรายเดือน",
    description: "คำนวณเงินเดือนสุทธิจากเงินเดือน OT รายได้อื่น ประกันสังคม กองทุน ภาษี และรายการหัก พร้อม breakdown สำหรับเทียบสลิปจริง โดยไม่สร้างเอกสารรับรองรายได้",
    category: "business",
    icon: "CircleDollarSign",
    keywords: ["คำนวณเงินเดือน", "คำนวณเงินเดือนสุทธิ", "ตรวจสลิปเงินเดือน", "อ่านสลิปเงินเดือน", "คำนวณประกันสังคม", "เงินเดือนสุทธิ", "salary calculator thailand", "net pay calculator"],
    isPopular: true,
    isNew: true,
    relatedTools: ["thai-income-tax-calculator", "loan-calculator", "profit-margin-calculator"],
    howTo: ["กรอกเงินเดือน OT ค่าตำแหน่ง โบนัส หรือรายรับที่จ่ายในเดือนเดียวกัน", "เลือกคำนวณประกันสังคมอัตโนมัติ หรือกรอกยอดหักจริงจากสลิป", "กรอกกองทุน ภาษี และรายการหักอื่น แล้วตรวจรายรับรวม รายการหักรวม และยอดสุทธิ"],
    example: "เงินเดือน 30,000 · OT 2,000 · รายได้อื่น 1,500 · รับสุทธิ 30,925 บาท",
    caution: "ผลลัพธ์ใช้ช่วยตรวจยอดรายเดือน ไม่ใช่สลิปเงินเดือน หนังสือรับรองรายได้ หรือคำวินิจฉัยสิทธิ ประกันสังคมอัตโนมัติอ้างอิงมาตรา 33 ปี 2569–2571 และควรใช้ยอดจริงจากสลิปเมื่อมีความแตกต่าง",
    faq: [...commonFaq,
      { question: "เครื่องมือนี้สร้างสลิปเงินเดือนได้หรือไม่?", answer: "ไม่ เครื่องมือแสดง breakdown สำหรับตรวจยอดเท่านั้น และไม่สร้างเอกสารที่อาจถูกเข้าใจว่าออกโดยนายจ้าง" },
      { question: "ภาษีหัก ณ ที่จ่ายคำนวณให้อัตโนมัติหรือไม่?", answer: "ไม่ เพราะภาษีรายเดือนขึ้นกับรายได้และสิทธิทั้งปี ควรกรอกยอดจากสลิป หรือใช้เครื่องมือภาษีเงินได้บุคคลธรรมดาเพื่อประมาณทั้งปี" },
    ],
  },
  {
    slug: "social-security-pension-calculator",
    name: "Social Security Pension Calculator",
    thaiName: "คำนวณบำนาญประกันสังคม",
    shortDescription: "ประมาณบำนาญ ม.33/ม.39 และตรวจเงื่อนไขเกิดสิทธิ",
    description: "คำนวณประมาณบำนาญชราภาพประกันสังคม มาตรา 33 และมาตรา 39 ด้วยสูตร FAE ปัจจุบัน พร้อมแสดงอัตรา จำนวนเดือนที่ยังขาด และตรวจอายุหรือสถานะเบื้องต้น",
    category: "business",
    icon: "Landmark",
    keywords: ["คำนวณบำนาญ", "คำนวณบำนาญประกันสังคม", "บำนาญชราภาพ", "ประกันสังคม มาตรา 33", "ประกันสังคม มาตรา 39", "เงินชราภาพ", "pension calculator thailand"],
    isPopular: true,
    isNew: true,
    relatedTools: ["salary-calculator", "thai-income-tax-calculator", "loan-calculator"],
    howTo: ["กรอกค่าจ้างเฉลี่ย 60 เดือนสุดท้ายที่ใช้เป็นฐานส่งเงินสมทบ", "กรอกจำนวนเดือนที่ส่งเงินสมทบ อายุ และสถานะความเป็นผู้ประกันตน", "กดคำนวณเพื่อตรวจประมาณบำนาญ สูตร และเงื่อนไขเกิดสิทธิ"],
    example: "ฐานค่าจ้างเฉลี่ย 15,000 บาท · ส่ง 250 เดือน · อัตรา 27.5% · ประมาณ 4,125 บาท/เดือน",
    caution: "เป็นประมาณการสูตร FAE ปัจจุบันสำหรับ ม.33/ม.39 ไม่ใช่การรับรองสิทธิ ไม่คำนวณบำเหน็จหรือ ม.40 และยังไม่ใช้สูตร CARE ซึ่ง ณ วันที่ตรวจทาน 3 สิงหาคม 2569 ยังเป็นร่างที่รอมีผลตามกฎหมาย",
    faq: [...commonFaq,
      { question: "สูตร CARE ใช้คำนวณแล้วหรือยัง?", answer: "ยังไม่ใช้ในเครื่องมือนี้ ร่าง CARE ได้รับความเห็นชอบจาก ครม. เมื่อ 14 กรกฎาคม 2569 แต่กำหนดให้มีผลหลังประกาศในราชกิจจานุเบกษาแล้ว 180 วัน จึงยังใช้สูตร FAE ปัจจุบันตามสถานะที่ตรวจทาน 3 สิงหาคม 2569" },
      { question: "ค่าจ้างเฉลี่ย 60 เดือนคือเงินเดือนล่าสุดหรือไม่?", answer: "ไม่ใช่ ให้นำฐานค่าจ้างที่ใช้ส่งเงินสมทบ 60 เดือนสุดท้ายก่อนสิ้นสุดความเป็นผู้ประกันตนมาเฉลี่ย โดยเฉพาะผู้ที่เคยสลับระหว่างมาตรา 33 และมาตรา 39 ควรตรวจประวัติจริงกับสำนักงานประกันสังคม" },
      { question: "ส่งเงินสมทบไม่ครบ 180 เดือนจะได้อะไร?", answer: "อาจเข้าเกณฑ์เงินบำเหน็จชราภาพแทนบำนาญรายเดือน ยอดขึ้นกับเงินสมทบและผลประโยชน์ตอบแทน เครื่องมือนี้จึงไม่เดายอดบำเหน็จและแนะนำให้ตรวจสิทธิกับสำนักงานประกันสังคม" },
      { question: "ใช้กับผู้ประกันตนมาตรา 40 ได้หรือไม่?", answer: "ไม่ได้ สูตรและสิทธิของมาตรา 40 แตกต่างจากมาตรา 33 และมาตรา 39" },
    ],
  },
  {
    slug: "thai-id-validator",
    name: "Thai ID Checksum Validator",
    thaiName: "ตรวจ checksum เลขบัตรประชาชน",
    shortDescription: "ตรวจโครงสร้าง 13 หลักและเลขตรวจสอบโดยไม่ส่งข้อมูล",
    description: "เช็คเลขบัตรประชาชนจากรูปแบบ 13 หลัก ประเภทหลักแรก และ checksum ภายใน Browser โดยซ่อนค่าที่กรอกเป็นค่าเริ่มต้น ไม่บันทึกข้อมูล และไม่อ้างว่าเป็นการยืนยันตัวตนกับฐานข้อมูลรัฐ",
    category: "security",
    icon: "BadgeCheck",
    keywords: ["เช็คเลขบัตรประชาชน", "ตรวจสอบเลขบัตรประชาชน", "ตรวจเลขบัตรประชาชน", "เลขบัตรประชาชน", "checksum", "thai id validator"],
    isPopular: true,
    isNew: true,
    relatedTools: ["password-generator", "hash-generator", "jwt-decoder"],
    howTo: ["กรอกเลขประจำตัวประชาชน 13 หลัก โดยใส่ขีดหรือช่องว่างได้", "กดตรวจ checksum เพื่อดูผลรูปแบบ ประเภทหลักแรก และเลขตรวจสอบ", "หากต้องยืนยันบุคคลหรือสถานะบัตร ให้ใช้บริการทางการที่มีสิทธิ์เชื่อมฐานทะเบียน"],
    example: "X-XXXX-XXXXX-XX-X (ซ่อนค่าเริ่มต้น)",
    caution: "ผลผ่านหมายถึงตัวเลขสอดคล้องตามสูตรเท่านั้น ไม่ยืนยันว่าบุคคลมีอยู่จริง บัตรยังใช้งานได้ หรือผู้กรอกเป็นเจ้าของเลข และไม่ควรกรอกบนอุปกรณ์สาธารณะ",
    faq: [...commonFaq,
      { question: "ผลผ่าน checksum ยืนยันตัวตนได้หรือไม่?", answer: "ไม่ได้ checksum ตรวจเพียงความสอดคล้องทางคณิตศาสตร์ การยืนยันตัวตนจริงต้องตรวจข้อมูลเพิ่มเติมและเชื่อมกับระบบทางการที่ได้รับสิทธิ์" },
      { question: "Meaw Tools เก็บเลขที่กรอกไว้หรือไม่?", answer: "ไม่ เครื่องมือประมวลผลใน Browser ไม่ส่งไป Server ไม่บันทึกใน LocalStorage และไม่ใส่เลขลง URL" },
      { question: "ทำไมไม่มีปุ่มสร้างเลขตัวอย่าง?", answer: "เลขประจำตัวประชาชนเป็นข้อมูลส่วนบุคคลสำคัญ เครื่องมือนี้จึงไม่สร้างหรือแสดงเลขเต็มที่ผ่าน checksum เพื่อจำกัดการนำไปใช้ผิดวัตถุประสงค์" },
    ],
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    thaiName: "คำนวณ BMI",
    shortDescription: "คำนวณดัชนีมวลกายและช่วงน้ำหนักสำหรับผู้ใหญ่",
    description: "คำนวณ BMI จากน้ำหนักและส่วนสูง พร้อมแสดงกลุ่มตามเกณฑ์ผู้ใหญ่ขององค์การอนามัยโลกและช่วงน้ำหนักอ้างอิง",
    category: "calculator",
    icon: "Activity",
    keywords: ["คำนวณ bmi", "ค่า bmi", "bmi calculator", "ดัชนีมวลกาย", "น้ำหนักปกติ"],
    isPopular: true,
    isNew: true,
    relatedTools: ["age-calculator", "unit-converter", "date-calculator"],
    howTo: ["กรอกน้ำหนักเป็นกิโลกรัม", "กรอกส่วนสูงเป็นเซนติเมตร", "กดคำนวณและอ่านผลพร้อมข้อจำกัดของ BMI"],
    example: "น้ำหนัก 70 กก. · ส่วนสูง 175 ซม. · BMI ≈ 22.9",
    caution: "เกณฑ์นี้ใช้กับผู้ใหญ่อายุมากกว่า 20 ปีและเป็นเพียงการคัดกรอง ไม่ใช่การวินิจฉัยหรือคำแนะนำทางการแพทย์",
    faq: [...commonFaq, { question: "เด็กและวัยรุ่นใช้ผลนี้ได้หรือไม่?", answer: "ไม่ควรใช้เกณฑ์ผู้ใหญ่โดยตรง เพราะ BMI ของผู้มีอายุ 0–19 ปีต้องพิจารณาอายุและเพศด้วยกราฟการเจริญเติบโต" }],
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit & Margin Calculator",
    thaiName: "คำนวณกำไรและ Margin",
    shortDescription: "หากำไร ขาดทุน Margin และ Markup จากต้นทุน",
    description: "คำนวณยอดขาย ต้นทุน กำไรหรือขาดทุน พร้อมแยก Margin และ Markup อย่างชัดเจนสำหรับร้านค้าและเจ้าของธุรกิจ",
    category: "business",
    icon: "BadgeDollarSign",
    keywords: ["คำนวณกำไร", "margin calculator", "markup", "กำไรขั้นต้น", "ราคาขาย", "ต้นทุน"],
    isPopular: true,
    isNew: true,
    relatedTools: ["vat-calculator", "percentage-calculator", "loan-calculator"],
    howTo: ["กรอกต้นทุนและราคาขายต่อชิ้น", "กำหนดจำนวนสินค้าที่ต้องการคำนวณ", "ดูยอดขาย กำไร Margin และ Markup"],
    example: "ต้นทุน 60 บาท · ราคาขาย 100 บาท · Margin 40% · Markup 66.67%",
    caution: "ผลลัพธ์ยังไม่รวม VAT ค่าขนส่ง ค่าธรรมเนียมแพลตฟอร์ม ค่าแรง และต้นทุนแฝง เว้นแต่รวมไว้ในต้นทุนต่อชิ้นแล้ว",
    faq: [...commonFaq, { question: "Margin ต่างจาก Markup อย่างไร?", answer: "Margin เปรียบเทียบกำไรกับราคาขาย ส่วน Markup เปรียบเทียบกำไรกับต้นทุน จึงได้เปอร์เซ็นต์ต่างกัน" }],
  },
  {
    slug: "quotation-generator",
    name: "Quotation Generator",
    thaiName: "สร้างใบเสนอราคา PDF",
    shortDescription: "สร้างใบเสนอราคาภาษาไทยพร้อม VAT และดาวน์โหลด PDF ฟรี",
    description: "สร้างใบเสนอราคาสำหรับร้านค้า ฟรีแลนซ์ และธุรกิจรายย่อย พร้อมข้อมูลผู้ขาย ลูกค้า รายการสินค้า ส่วนลด VAT ยอดเป็นตัวอักษรไทย และ PDF A4 โดยประมวลผลใน Browser",
    category: "business",
    icon: "ReceiptText",
    keywords: ["ใบเสนอราคา", "ตัวอย่างใบเสนอราคา", "แบบฟอร์มใบเสนอราคา", "สร้างใบเสนอราคา", "ใบเสนอราคา pdf", "quotation generator", "quotation template", "โปรแกรมใบเสนอราคา"],
    isPopular: true,
    isNew: true,
    relatedTools: ["vat-calculator", "profit-margin-calculator", "thai-income-tax-calculator"],
    howTo: ["กรอกข้อมูลผู้เสนอราคา ลูกค้า เลขที่เอกสาร และวันที่", "เพิ่มสินค้าและบริการ กำหนดส่วนลด รูปแบบ VAT และเงื่อนไข", "ตรวจตัวอย่างแล้วกดสร้างและดาวน์โหลด PDF ภาษาไทย"],
    example: "เว็บไซต์ 25,000 บาท + ถ่ายภาพ 7,000 บาท + ดูแลระบบ 7,500 บาท - ส่วนลด 1,000 บาท + VAT 7%",
    caution: "ใบเสนอราคาไม่ใช่ใบเสร็จ ใบกำกับภาษี หลักฐานรับเงิน หรือลายเซ็นดิจิทัล ควรตรวจข้อมูลและอัตราภาษีกับผู้ทำบัญชีก่อนใช้งานจริง",
    faq: [...commonFaq,
      { question: "PDF รองรับภาษาไทยหรือไม่?", answer: "รองรับ เครื่องมือฝังฟอนต์ Sarabun ลงใน PDF และโหลดฟอนต์เฉพาะเมื่อกดสร้างไฟล์ แต่อักขระ Emoji บางชนิดอาจไม่แสดง" },
      { question: "VAT แบบรวมแล้วกับบวกเพิ่มต่างกันอย่างไร?", answer: "แบบบวกเพิ่มจะคำนวณ VAT เพิ่มจากยอดหลังส่วนลด ส่วนแบบรวมแล้วจะแยกยอด VAT ออกจากราคารวมโดยไม่เพิ่มยอดสุทธิ" },
      { question: "ใช้แทนใบกำกับภาษีได้หรือไม่?", answer: "ไม่ได้ เครื่องมือนี้สร้างเฉพาะใบเสนอราคาและไม่ได้ตรวจเงื่อนไขเอกสารภาษีตามกิจการของคุณ" },
    ],
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    thaiName: "แปลง HEIC เป็น JPG ออนไลน์",
    shortDescription: "แปลงรูป HEIC/HEIF จาก iPhone เป็น JPG หลายไฟล์ภายใน Browser",
    description: "แปลง HEIC และ HEIF เป็น JPG โดยใช้ WebAssembly ภายใน Browser เลือกคุณภาพและขนาดภาพ รองรับหลายไฟล์ พร้อมดาวน์โหลดเป็น ZIP โดยไม่อัปโหลดรูปขึ้น Server",
    category: "media",
    icon: "Images",
    keywords: ["heic to jpg", "แปลง heic เป็น jpg", "convert heic to jpg", "heic converter", "heif to jpg", "รูป iphone เป็น jpg"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-png", "png-to-jpg", "image-compressor"],
    howTo: ["เลือกไฟล์ HEIC หรือ HEIF จาก iPhone ได้สูงสุด 10 ไฟล์", "เลือกขนาดด้านยาวและคุณภาพ JPG แล้วกดแปลง", "ตรวจภาพตัวอย่างและดาวน์โหลด JPG หรือ ZIP"],
    example: "IMG_1001.HEIC · 4032 × 3024 px → IMG_1001.jpg · สูงสุด 4096 px · คุณภาพ 90%",
    caution: "JPG ใหม่ไม่เก็บ EXIF, GPS หรือ metadata เดิม และใช้เฉพาะภาพหลักของ Live Photo/Burst วิดีโอ เสียง depth map และการแก้ไขใน Photos จะไม่ถูกส่งต่อ ควรเก็บ HEIC ต้นฉบับไว้เสมอ",
    faq: [...commonFaq,
      { question: "รองรับหลายไฟล์พร้อมกันหรือไม่?", answer: "รองรับสูงสุด 10 ไฟล์ต่อครั้ง ไฟล์ละไม่เกิน 20 MB และรวมไม่เกิน 60 MB โดยดาวน์โหลดหลายผลลัพธ์เป็น ZIP ได้" },
      { question: "รูปถูกส่งขึ้น Server หรือไม่?", answer: "ไม่ ไฟล์ถูกถอดรหัสด้วย WebAssembly และสร้าง JPG ภายใน Browser ของอุปกรณ์คุณ" },
      { question: "EXIF และพิกัด GPS ยังอยู่หรือไม่?", answer: "ไม่ เครื่องมือสร้าง JPG ใหม่จากข้อมูลพิกเซล จึงไม่คัดลอก EXIF, GPS หรือ metadata เดิม ช่วยลดข้อมูลส่วนตัวแต่ควรเก็บต้นฉบับหากยังต้องใช้ข้อมูลเหล่านั้น" },
      { question: "รองรับ Live Photo และ Burst หรือไม่?", answer: "เครื่องมือใช้ภาพหลักเพียงภาพเดียว ไม่รวมวิดีโอ เสียง ภาพเสริม depth map หรือภาพอื่นใน Burst" },
      { question: "ทำไมการแปลงไฟล์แรกอาจใช้เวลานาน?", answer: "Browser ต้องโหลดตัวถอดรหัส WebAssembly ประมาณ 1 MB เมื่อกดแปลงครั้งแรก จากนั้นจึงถอดรหัสภาพทีละไฟล์เพื่อลดการใช้หน่วยความจำ" },
    ],
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG Batch Converter",
    thaiName: "แปลง JPG เป็น PNG หลายไฟล์",
    shortDescription: "แปลง JPG, PNG และ WebP หลายรูปพร้อมดาวน์โหลด ZIP",
    description: "แปลง JPG เป็น PNG ออนไลน์ฟรีครั้งละหลายไฟล์ พร้อมเลือกผลลัพธ์เป็น PNG, WebP หรือ JPG กำหนดขนาดและคุณภาพ แล้วดาวน์โหลดทั้งหมดเป็น ZIP โดยประมวลผลภายใน Browser",
    category: "media",
    icon: "Images",
    keywords: ["แปลง jpg เป็น png", "jpg to png", "แปลงรูปเป็น png", "jpg เป็น png", "image converter", "แปลงรูปหลายไฟล์", "batch image converter", "webp converter", "แปลงไฟล์รูป"],
    isPopular: true,
    isNew: true,
    relatedTools: ["png-to-jpg", "image-compressor", "heic-to-jpg"],
    howTo: ["เลือกหรือลากไฟล์ JPG, PNG หรือ WebP ได้สูงสุด 20 รูป", "เลือกรูปแบบผลลัพธ์ ขนาดด้านยาว คุณภาพ และสีพื้นหลัง JPG", "กดแปลง ตรวจรายการผลลัพธ์ แล้วดาวน์โหลดทีละรูปหรือรวมเป็น ZIP"],
    example: "2 JPG → 2 PNG + ZIP",
    caution: "ไฟล์ใหม่จาก Canvas มักไม่เก็บ EXIF, GPS หรือ metadata เดิม และ PNG อาจมีขนาดใหญ่กว่า JPG ต้นฉบับ ควรเก็บไฟล์ต้นฉบับและตรวจคุณภาพก่อนใช้งานจริง",
    faq: [...commonFaq,
      { question: "แปลงพร้อมกันได้กี่รูป?", answer: "สูงสุด 20 ไฟล์ต่อครั้ง ไฟล์ละไม่เกิน 10 MB รวมไม่เกิน 50 MB และผลลัพธ์รวมไม่เกิน 120 ล้านพิกเซล เครื่องมือประมวลผลทีละรูปเพื่อลดการใช้ RAM" },
      { question: "รูปถูกอัปโหลดขึ้น Server หรือไม่?", answer: "ไม่ Browser อ่านพิกเซล แปลงรูป และสร้าง ZIP ในอุปกรณ์ของคุณ ไม่มี API ของ Meaw Tools รับหรือบันทึกไฟล์" },
      { question: "พื้นโปร่งใสจะยังอยู่หรือไม่?", answer: "PNG และ WebP รองรับพื้นโปร่งใส ส่วน JPG ไม่รองรับ เครื่องมือจึงใช้สีพื้นหลังที่คุณเลือกแทนพื้นที่โปร่งใสเมื่อส่งออกเป็น JPG" },
      { question: "EXIF และพิกัด GPS จะยังอยู่หรือไม่?", answer: "โดยทั่วไปไม่อยู่ เพราะ Browser วาดพิกเซลลง Canvas แล้วสร้างไฟล์ใหม่ เครื่องมือนี้ไม่คัดลอก EXIF, GPS, ICC profile หรือ metadata เดิม" },
      { question: "ทำไม PNG ใหม่อาจใหญ่กว่า JPG?", answer: "PNG ใช้การบีบอัดแบบไม่สูญเสียข้อมูลและเหมาะกับกราฟิกหรือพื้นโปร่งใส ภาพถ่ายที่มาจาก JPG จึงมักได้ PNG ที่ใหญ่ขึ้น หากต้องการไฟล์เล็กให้เลือก WebP หรือ JPG" },
    ],
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG Converter",
    thaiName: "แปลง PNG เป็น JPG",
    shortDescription: "แปลง PNG หรือ WebP เป็น JPG พร้อมเลือกพื้นหลัง",
    description: "แปลงไฟล์ PNG หรือ WebP เป็น JPG ภายใน Browser เลือกสีแทนพื้นโปร่งใสและระดับคุณภาพก่อนดาวน์โหลดได้ โดยไม่อัปโหลดรูปขึ้น Server",
    category: "media",
    icon: "FileImage",
    keywords: ["แปลง png เป็น jpg", "png to jpg", "แปลง webp เป็น jpg", "webp to jpg", "แปลงรูปเป็น jpg", "เปลี่ยนไฟล์รูป"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-png", "image-compressor", "jpg-to-pdf"],
    howTo: ["เลือกไฟล์ PNG หรือ WebP ขนาดไม่เกิน 10 MB", "เลือกสีพื้นหลังสำหรับส่วนที่โปร่งใสและกำหนดคุณภาพ JPG", "กดแปลง ตรวจภาพตัวอย่าง แล้วดาวน์โหลดไฟล์"],
    example: "product-transparent.png → product-transparent-converted.jpg",
    caution: "JPG ไม่รองรับพื้นโปร่งใส พื้นที่โปร่งใสจะถูกแทนด้วยสีที่เลือก และการแปลงผ่าน Canvas มักไม่เก็บ metadata เดิม",
    faq: [...commonFaq, { question: "ทำไมพื้นโปร่งใสจึงกลายเป็นสีขาว?", answer: "JPG ไม่มีช่องความโปร่งใส เครื่องมือจึงเติมสีพื้นหลังที่เลือกไว้ก่อนสร้างไฟล์ JPG" }],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor & Resizer",
    thaiName: "ลดขนาดและบีบอัดรูป",
    shortDescription: "ย่อความละเอียดและลดขนาดไฟล์ JPG, PNG, WebP",
    description: "ลดขนาดรูปด้วยการจำกัดความกว้างและความสูงโดยรักษาสัดส่วน พร้อมแปลงเป็น WebP, JPG หรือ PNG และปรับคุณภาพได้ภายใน Browser",
    category: "media",
    icon: "Images",
    keywords: ["ลดขนาดรูป", "บีบอัดรูป", "image compressor", "image resizer", "ย่อรูป", "ลดขนาดไฟล์รูป", "แปลงรูป webp"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-png", "png-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 10 MB", "กำหนดขนาดสูงสุด รูปแบบผลลัพธ์ และระดับคุณภาพ", "กดบีบอัด เปรียบเทียบขนาด แล้วดาวน์โหลดไฟล์"],
    example: "4000 × 3000 px · 4.8 MB → WebP 1920 × 1440 px",
    caution: "ขนาดไฟล์ขึ้นกับรายละเอียดของรูปและรูปแบบผลลัพธ์ บางกรณี PNG หรือรูปที่บีบอัดมาแล้วอาจมีขนาดเพิ่มขึ้น ควรตรวจภาพก่อนใช้งานจริง",
    faq: [...commonFaq, { question: "เครื่องมือยืดหรือบีบสัดส่วนภาพหรือไม่?", answer: "ไม่ เครื่องมือรักษาอัตราส่วนเดิมและลดให้พอดีกับทั้งความกว้างและความสูงที่กำหนด โดยไม่ขยายเกินต้นฉบับ" }],
  },
  {
    slug: "image-cropper",
    name: "Image Cropper Online",
    thaiName: "ครอปรูปออนไลน์",
    shortDescription: "ตัดรูปตามสัดส่วน วงกลม หรือขนาดพิกเซลที่ต้องการ",
    description: "ครอปรูปออนไลน์ฟรีแบบไม่อัปโหลด รองรับกรอบอิสระ วงกลม 1:1, 4:3, 3:2, 16:9 และ 9:16 พร้อมหมุน พลิก กำหนดขนาดพิกเซล และส่งออก PNG, JPG หรือ WebP ภายใน Browser",
    category: "media",
    icon: "Crop",
    keywords: ["image cropper", "image cropper online", "crop image online", "ครอปรูป", "ครอปรูป ออนไลน์", "ตัดรูป ออนไลน์", "ครอปรูป วงกลม", "circle image cropper", "ตัดขอบรูป", "crop image by pixel", "ครอปรูป 1:1", "ครอปรูป 16:9"],
    isPopular: true,
    isNew: true,
    relatedTools: ["image-compressor", "jpg-to-png", "background-remover"],
    howTo: ["เลือก ลาก หรือวางรูป JPG, PNG หรือ WebP", "ลากกรอบ เลือกสัดส่วน วงกลม หมุน หรือกรอกตำแหน่งพิกเซล", "เลือกความละเอียด รูปแบบ และคุณภาพ แล้วกดครอปเพื่อดาวน์โหลด"],
    example: "1600 × 1024 px → วงกลม PNG 820 × 820 px",
    caution: "เครื่องมือสร้างไฟล์ใหม่จากพิกเซลและไม่คัดลอก metadata เดิม การขยายเกินพื้นที่ต้นฉบับอาจทำให้ภาพไม่คม และ JPG ไม่รองรับพื้นโปร่งใส ควรตรวจไฟล์ก่อนนำไปพิมพ์หรือส่งงาน",
    faq: [
      ...commonFaq,
      { question: "ครอปรูปเป็นวงกลมและพื้นโปร่งใสได้หรือไม่?", answer: "ได้ เลือกครอปเป็นวงกลมแล้วส่งออก PNG หรือ WebP พื้นนอกวงกลมจะโปร่งใส หากเลือก JPG พื้นนอกวงกลมจะใช้สีที่กำหนดเพราะ JPG ไม่รองรับความโปร่งใส" },
      { question: "กำหนดขนาดรูปเป็นพิกเซลได้หรือไม่?", answer: "ได้ เลือกความละเอียดแบบกำหนดเองแล้วกรอกความกว้างหรือความสูง เครื่องมือจะล็อกสัดส่วนของพื้นที่ครอปให้อัตโนมัติ จำกัดด้านยาว 8,000 พิกเซลและรวมไม่เกิน 24 ล้านพิกเซล" },
      { question: "ใช้คีย์บอร์ดครอปรูปได้หรือไม่?", answer: "ได้ โฟกัสกรอบครอปแล้วใช้ปุ่มลูกศรเพื่อเลื่อนทีละ 1% หรือกด Shift พร้อมลูกศรเพื่อเลื่อนทีละ 5% และใช้ช่อง X, Y, W, H เพื่อกำหนดตำแหน่งกับขนาดอย่างละเอียด" },
      { question: "รูปถูกอัปโหลดหรือเก็บไว้ที่ไหน?", answer: "รูปถูกอ่าน วาด และสร้างไฟล์ใหม่ภายใน Browser ของคุณ ไม่มี API ของ Meaw Tools รับหรือบันทึกรูป รูปตัวอย่างที่มากับเว็บโหลดจากโดเมนเดียวกันเท่านั้น" },
      { question: "EXIF และพิกัด GPS จะยังอยู่หรือไม่?", answer: "ไม่ เครื่องมือวาดพิกเซลลง Canvas แล้วสร้างไฟล์ใหม่ โดยไม่คัดลอก EXIF, GPS, XMP, ICC profile หรือ metadata เดิม" },
    ],
  },
  {
    slug: "background-remover",
    name: "AI Background Remover",
    thaiName: "ลบพื้นหลังรูปออนไลน์",
    shortDescription: "ลบพื้นหลัง JPG, PNG หรือ WebP ด้วย AI ในอุปกรณ์",
    description: "ลบพื้นหลังรูปสินค้า บุคคล สัตว์ หรือวัตถุเป็น PNG โปร่งใสด้วย AI ที่ทำงานภายใน Browser รูปไม่ถูกอัปโหลดขึ้น Server และไม่มีลายน้ำ",
    category: "media",
    icon: "ImageOff",
    keywords: ["ลบพื้นหลัง", "ลบพื้นหลังรูป", "ลบพื้นหลังออนไลน์", "background remover", "remove background", "รูปพื้นหลังโปร่งใส", "ตัดพื้นหลัง", "png โปร่งใส"],
    isPopular: true,
    isNew: true,
    relatedTools: ["image-compressor", "png-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 10 MB และ 16 ล้านพิกเซล", "กดลบพื้นหลังและรอ AI ประมวลผลในอุปกรณ์", "ตรวจขอบตัวแบบบนพื้นสีต่าง ๆ แล้วดาวน์โหลด PNG โปร่งใส"],
    example: "product.jpg → product-no-background.png",
    caution: "ครั้งแรกต้องดาวน์โหลด AI Runtime และโมเดลประมาณ 15–20 MB ผลลัพธ์อาจคลาดเคลื่อนกับพื้นหลังซับซ้อน กระจก เงา เส้นผมละเอียด หรือหลายวัตถุ ควรตรวจภาพก่อนใช้งานจริง",
    faq: [
      ...commonFaq,
      { question: "ทำไมครั้งแรกจึงใช้เวลานาน?", answer: "Browser ต้องดาวน์โหลด ONNX Runtime และโมเดล U-2-Netp ก่อน เมื่อดาวน์โหลดสำเร็จ Browser จะเก็บไฟล์ไว้ใน cache เพื่อให้ครั้งถัดไปเร็วขึ้น" },
      { question: "รูปถูกส่งไปให้ AI ภายนอกหรือไม่?", answer: "ไม่ โมเดลถูกดาวน์โหลดมาให้ Browser ประมวลผลรูปในอุปกรณ์ของคุณ ไม่มี API ของ Meaw Tools รับหรือบันทึกไฟล์รูป" },
      { question: "ลบพื้นหลังได้แม่นทุกภาพหรือไม่?", answer: "ไม่ โมเดลขนาดเล็กเหมาะกับตัวแบบเด่นชัดบนพื้นหลังที่แยกง่าย ขอบผม ขน วัตถุโปร่งใส และฉากซับซ้อนอาจต้องแก้ต่อในโปรแกรมแต่งภาพ" },
    ],
  },
  {
    slug: "color-picker",
    name: "Color Picker & Contrast Checker",
    thaiName: "เลือกสีและตรวจ Contrast",
    shortDescription: "แปลง HEX, RGB, HSL พร้อมตรวจ WCAG Contrast",
    description: "เลือกและแปลงค่าสีระหว่าง HEX, RGB และ HSL สร้างเฉดสีอัตโนมัติ พร้อมตรวจอัตราส่วน Contrast ตามเกณฑ์ WCAG AA และ AAA",
    category: "developer",
    icon: "Palette",
    keywords: ["color picker", "เลือกสี", "รหัสสี", "แปลง hex rgb", "contrast checker", "wcag contrast", "color palette"],
    isPopular: true,
    isNew: true,
    relatedTools: ["image-compressor", "qr-code-generator", "percentage-calculator"],
    howTo: ["เลือกหรือกรอกรหัสสีข้อความและสีพื้นหลัง", "ดู Preview, ค่าสี HEX/RGB/HSL และอัตราส่วน Contrast", "คัดลอกค่าสี CSS หรือเฉดสีที่สร้างให้อัตโนมัติ"],
    example: "Foreground #0F9F8F · Background #FFFFFF · Contrast 3.29:1",
    caution: "Contrast ที่ผ่านเกณฑ์เป็นเพียงส่วนหนึ่งของ Accessibility ควรตรวจขนาดตัวอักษร สถานะ focus และการใช้งานจริงร่วมด้วย",
    faq: [...commonFaq, { question: "WCAG AA ต้องมี Contrast เท่าใด?", answer: "ข้อความขนาดปกติต้องมีอย่างน้อย 4.5:1 ส่วนข้อความขนาดใหญ่และองค์ประกอบ UI ใช้เกณฑ์อย่างน้อย 3:1" }],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    thaiName: "สร้างรหัสผ่านสุ่ม",
    shortDescription: "สร้างรหัสผ่านแข็งแรงด้วย Web Crypto",
    description: "สร้างรหัสผ่านสุ่ม 1–20 รายการ เลือกความยาว ตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก ตัวเลข สัญลักษณ์ และตัดตัวอักษรที่มองคล้ายกันได้",
    category: "security",
    icon: "ShieldEllipsis",
    keywords: ["password generator", "สร้างรหัสผ่าน", "สุ่มรหัสผ่าน", "strong password", "random password", "รหัสผ่าน 16 ตัว"],
    isPopular: true,
    isNew: true,
    relatedTools: ["hash-generator", "uuid-generator", "jwt-decoder"],
    howTo: ["กำหนดความยาวและจำนวนรหัสผ่าน", "เลือกชุดตัวอักษรและเปิดการตัดตัวที่มองคล้ายกัน", "กดสร้างแล้วคัดลอกรหัสผ่านที่ต้องการ"],
    example: "16 ตัวอักษร · A–Z · a–z · 0–9 · สัญลักษณ์ · ตัด i I l L 1 o O 0",
    caution: "อย่าใช้รหัสผ่านเดียวกันหลายบริการ ควรจัดเก็บด้วย Password Manager และเปิด MFA เมื่อบริการรองรับ",
    faq: [...commonFaq, { question: "รหัสผ่านถูกส่งไปที่ Server หรือไม่?", answer: "ไม่ รหัสผ่านสร้างด้วย Web Crypto ภายใน Browser และไม่ถูกบันทึกโดย Meaw Tools" }],
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    thaiName: "สุ่มตัวเลข",
    shortDescription: "สุ่มจำนวนเต็มแบบซ้ำหรือไม่ซ้ำด้วย Web Crypto",
    description: "สุ่มจำนวนเต็มตามช่วงที่กำหนดได้สูงสุด 1,000 รายการ เลือกไม่ให้ซ้ำ เรียงผลลัพธ์ และใช้ตัวเลือกด่วนสำหรับลูกเต๋า หัวก้อย หรือจับฉลาก",
    category: "calculator",
    icon: "Dices",
    keywords: ["random number generator", "สุ่มตัวเลข", "โปรแกรมสุ่มเลข", "จับฉลาก", "ลูกเต๋าออนไลน์", "random picker"],
    isPopular: true,
    isNew: true,
    relatedTools: ["random-wheel", "percentage-calculator", "uuid-generator"],
    howTo: ["กำหนดค่าต่ำสุด ค่าสูงสุด และจำนวนผลลัพธ์", "เลือกว่าจะห้ามซ้ำและเรียงตัวเลขหรือไม่", "กดสุ่มแล้วคัดลอกหรือดาวน์โหลดผลลัพธ์"],
    example: "ช่วง 1–100 · 5 รายการ · ไม่ซ้ำ · เรียงจากน้อยไปมาก",
    caution: "เหมาะกับเกม ตัวอย่าง และการจับฉลากทั่วไป ไม่ใช่ระบบรับรองผลสำหรับการพนัน การเงิน หรือรางวัลมูลค่าสูง",
    faq: [...commonFaq, { question: "สุ่มด้วย Math.random หรือไม่?", answer: "ไม่ เครื่องมือใช้ Web Crypto และลด modulo bias เพื่อให้แต่ละค่าในช่วงมีโอกาสใกล้เคียงกัน" }],
  },
  {
    slug: "random-wheel",
    name: "Random Wheel",
    thaiName: "วงล้อสุ่มชื่อ",
    shortDescription: "หมุนวงล้อสุ่มชื่อ ตัวเลือก หรือของรางวัลด้วย Web Crypto",
    description: "สร้างวงล้อสุ่มจากรายชื่อ 2–100 รายการ ตัดชื่อซ้ำ นำผู้ชนะออกหลังสุ่ม และดูประวัติผลลัพธ์ เหมาะกับห้องเรียน กิจกรรม และการจับฉลากทั่วไป",
    category: "calculator",
    icon: "RefreshCw",
    keywords: ["วงล้อสุ่ม", "สุ่มชื่อ", "วงล้อสุ่มชื่อ", "wheel of names", "random wheel", "จับฉลากออนไลน์", "สุ่มรายชื่อ", "วงล้อจับฉลาก"],
    isPopular: true,
    isNew: true,
    relatedTools: ["random-number-generator", "password-generator", "percentage-calculator"],
    howTo: ["กรอกชื่อหรือตัวเลือกหนึ่งรายการต่อหนึ่งบรรทัด", "เลือกว่าจะตัดรายการซ้ำและนำผู้ชนะออกหลังสุ่มหรือไม่", "กดหมุนวงล้อ แล้วดูผลและประวัติการสุ่ม"],
    example: "มะลิ · สมชาย · น้ำฝน · ต้นกล้า → หมุนเพื่อเลือก 1 รายการ",
    caution: "เหมาะกับกิจกรรมทั่วไป ไม่ใช่ระบบรับรองผลสำหรับการพนัน การเงิน หรือรางวัลมูลค่าสูง",
    faq: [...commonFaq, { question: "ผลการหมุนสุ่มอย่างไร?", answer: "เครื่องมือใช้ Web Crypto เลือกลำดับผู้ชนะและคำนวณมุมที่วงล้อต้องหมุน โดยไม่ส่งรายชื่อออกจาก Browser" }],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG Converter",
    thaiName: "แปลง PDF เป็น JPG",
    shortDescription: "แปลงหน้า PDF เป็นภาพ JPG พร้อมเลือกหน้าและคุณภาพ",
    description: "แปลงหน้า PDF เป็นภาพ JPG ความละเอียดสูงภายใน Browser เลือกเฉพาะหน้า กำหนดคุณภาพ และดาวน์โหลดหลายหน้าเป็น ZIP ได้โดยไม่อัปโหลดเอกสาร",
    category: "media",
    icon: "FileDown",
    keywords: ["pdf to jpg", "แปลง pdf เป็น jpg", "pdf เป็นรูป", "pdf to image", "แปลง pdf เป็นภาพ", "pdf เป็น jpeg"],
    isPopular: true,
    isNew: true,
    relatedTools: ["jpg-to-pdf", "merge-pdf", "split-pdf"],
    howTo: ["เลือก PDF ขนาดไม่เกิน 30 MB", "ระบุหน้าที่ต้องการ เช่น 1,3-5 แล้วเลือกความละเอียดและคุณภาพ", "กดแปลงเพื่อดาวน์โหลด JPG หรือ ZIP"],
    example: "catalog.pdf หน้า 1-3 → catalog-page-1.jpg + ZIP",
    caution: "รองรับสูงสุด 20 หน้าต่อครั้ง ภาพผลลัพธ์ไม่มีข้อความที่เลือกได้ ลิงก์ หรือ metadata ของ PDF เดิม",
    faq: [...commonFaq, { question: "ทำไมหลายหน้าจึงได้ไฟล์ ZIP?", answer: "เพื่อให้ดาวน์โหลดภาพทุกหน้าได้ในครั้งเดียว ระบบจะรวม JPG หลายไฟล์เป็น ZIP ภายใน Browser" }],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    thaiName: "รวม PDF ออนไลน์",
    shortDescription: "เรียงและรวม PDF หลายไฟล์เป็นเอกสารเดียว",
    description: "รวม PDF ได้สูงสุด 10 ไฟล์ จัดลำดับก่อนสร้างเอกสารใหม่ และดาวน์โหลดได้ทันทีโดยไฟล์ไม่ออกจาก Browser",
    category: "media",
    icon: "Files",
    keywords: ["merge pdf", "รวม pdf", "รวมไฟล์ pdf", "ต่อ pdf", "combine pdf", "รวมเอกสาร"],
    isPopular: true,
    isNew: true,
    relatedTools: ["split-pdf", "pdf-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือก PDF อย่างน้อย 2 ไฟล์", "ใช้ปุ่มขึ้นลงเพื่อจัดลำดับ", "กดรวมและดาวน์โหลด PDF ใหม่"],
    example: "invoice.pdf + receipt.pdf → meaw-merged.pdf",
    caution: "ฟอร์ม ลิงก์ bookmark และโครงสร้างพิเศษบางชนิดอาจทำงานต่างจากต้นฉบับ ควรตรวจไฟล์ใหม่ก่อนใช้งานจริง",
    faq: [...commonFaq, { question: "รวมได้กี่ไฟล์?", answer: "สูงสุด 10 ไฟล์ ไฟล์ละไม่เกิน 30 MB และขนาดรวมไม่เกิน 60 MB ต่อครั้ง" }],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    thaiName: "แยกหน้า PDF",
    shortDescription: "แยกช่วงหน้า PDF เป็นไฟล์ใหม่หลายชุด",
    description: "แยก PDF ตามช่วงหน้า เช่น 1-3,4-6,8 โดยแต่ละช่วงสร้างเป็นไฟล์ใหม่และดาวน์โหลดหลายไฟล์รวมเป็น ZIP ภายใน Browser",
    category: "media",
    icon: "Scissors",
    keywords: ["split pdf", "แยก pdf", "แยกหน้า pdf", "ตัด pdf", "extract pdf pages", "แบ่ง pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["merge-pdf", "pdf-to-jpg", "jpg-to-pdf"],
    howTo: ["เลือก PDF ขนาดไม่เกิน 30 MB", "ระบุช่วงหน้าโดยใช้ comma คั่นแต่ละไฟล์ เช่น 1-3,4-6,8", "กดแยกเพื่อดาวน์โหลด PDF หรือ ZIP"],
    example: "report.pdf · 1-3,4-6,8 → PDF 3 ไฟล์",
    caution: "ไม่รองรับ PDF ที่ล็อกด้วยรหัสผ่าน และการระบุหน้าต้องไม่เกินจำนวนหน้าจริงของเอกสาร",
    faq: [...commonFaq, { question: "จะสร้าง PDF แยกทีละหน้าได้อย่างไร?", answer: "กรอกหมายเลขหน้าแยกด้วย comma เช่น 1,2,3,4 แต่ละหมายเลขจะเป็น PDF คนละไฟล์" }],
  },
  {
    slug: "pdf-organizer",
    name: "PDF Organizer",
    thaiName: "ลบ หมุน และเรียงหน้า PDF",
    shortDescription: "จัดหน้า PDF ด้วยภาพตัวอย่างแบบลากเรียงโดยไม่อัปโหลดไฟล์",
    description: "ดูตัวอย่างทุกหน้าแล้วลบหน้า PDF หมุน และเรียงหน้าใหม่ด้วยการลากหรือปุ่มที่รองรับมือถือ ประมวลผลและสร้างไฟล์ใหม่ภายใน Browser โดยไม่ส่งเอกสารไป Server",
    category: "media",
    icon: "ListFilter",
    keywords: ["ลบหน้า pdf", "หมุน pdf", "เรียงหน้า pdf", "จัดหน้า pdf", "จัดระเบียบ pdf", "pdf organizer", "delete pdf pages", "rotate pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["sign-pdf", "merge-pdf", "split-pdf"],
    howTo: ["เลือก PDF ไม่เกิน 30 MB และรอระบบสร้างภาพตัวอย่าง", "ลากหน้า หรือใช้ปุ่มลูกศร หมุน และลบใต้การ์ดแต่ละหน้า", "กดจัดหน้าและดาวน์โหลด PDF แล้วเปิดตรวจไฟล์ใหม่ก่อนส่งงาน"],
    example: "PDF 5 หน้า · หมุนหน้า 1 · ลบหน้า 2 · เรียงหน้าใหม่",
    caution: "การแก้ไขอาจทำให้ลายเซ็นดิจิทัลเดิมไม่ผ่านการตรวจสอบ และฟอร์ม bookmark หรือลิงก์บางชนิดอาจเปลี่ยนแปลง ไม่รองรับ PDF ที่มีรหัสผ่านและจำกัด 100 หน้า",
    faq: [...commonFaq,
      { question: "ไฟล์ PDF ถูกอัปโหลดหรือไม่?", answer: "ไม่ การอ่านภาพตัวอย่าง การจัดหน้า และการสร้างไฟล์ใหม่เกิดใน Browser ของอุปกรณ์คุณ" },
      { question: "รองรับ PDF ที่มีลายเซ็นดิจิทัลหรือไม่?", answer: "เปิดและจัดหน้าได้ในบางกรณี แต่การเปลี่ยนแปลงเอกสารอาจทำให้ลายเซ็นเดิมไม่ผ่านการตรวจสอบ จึงไม่ควรใช้กับเอกสารที่ต้องรักษาสถานะลายเซ็น" },
      { question: "ทำไมจำกัด 100 หน้า?", answer: "เครื่องมือต้องสร้างภาพตัวอย่างทุกหน้าในหน่วยความจำของ Browser ขีดจำกัดนี้ช่วยลดโอกาสที่แท็บจะค้างบนมือถือหรือเครื่องที่มี RAM น้อย" },
    ],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    thaiName: "เซ็น PDF ออนไลน์",
    shortDescription: "วาดหรืออัปโหลดลายเซ็นแล้ววางบน PDF โดยไม่ส่งเอกสารขึ้น Server",
    description: "เซ็น PDF ด้วยลายเซ็นที่วาดหรือรูป PNG, JPG และ WebP ลากตำแหน่ง ย่อขยาย ปรับความทึบ และวางได้หลายหน้า โดยอ่านและสร้างไฟล์ใหม่ภายใน Browser ของอุปกรณ์คุณ",
    category: "media",
    icon: "FilePenLine",
    keywords: ["เซ็น pdf", "ใส่ลายเซ็น pdf", "ลงลายเซ็น pdf", "เซ็นเอกสารออนไลน์", "ลายเซ็นอิเล็กทรอนิกส์", "sign pdf", "add signature to pdf"],
    isPopular: true,
    isNew: true,
    relatedTools: ["pdf-organizer", "merge-pdf", "split-pdf"],
    howTo: ["เลือก PDF ไม่เกิน 30 MB แล้ววาดหรืออัปโหลดรูปลายเซ็น", "เลือกหน้าและกดวางลายเซ็น จากนั้นลาก ย่อขยาย หรือปรับความทึบ", "กดเซ็นและดาวน์โหลด PDF แล้วเปิดตรวจทุกตำแหน่งก่อนส่งเอกสาร"],
    example: "agreement.pdf · ลายเซ็น 2 ตำแหน่งในหน้า 1 และ 2 → agreement-signed.pdf",
    caution: "ลายเซ็นที่วางเป็นรูปภาพ ไม่ใช่ลายเซ็นดิจิทัลแบบ certificate และไม่ยืนยันตัวตน เวลา หรือความยินยอม การแก้ไขอาจทำให้ลายเซ็นดิจิทัลเดิมไม่ผ่านการตรวจสอบ ไม่รองรับ PDF ที่มีรหัสผ่านและจำกัด 100 หน้า",
    faq: [...commonFaq,
      { question: "ไฟล์ PDF และรูปลายเซ็นถูกอัปโหลดหรือไม่?", answer: "ไม่ การอ่านเอกสาร ประมวลผลรูป และสร้าง PDF ใหม่เกิดใน Browser ของอุปกรณ์คุณ" },
      { question: "วาดลายเซ็นหรือใช้รูปที่มีอยู่ได้หรือไม่?", answer: "ได้ คุณวาดด้วยเมาส์ ปากกา หรือหน้าจอสัมผัส หรืออัปโหลด PNG, JPG และ WebP พร้อมเลือกตัดพื้นขาวอัตโนมัติได้" },
      { question: "นี่คือลายเซ็นดิจิทัลที่ตรวจสอบ certificate ได้หรือไม่?", answer: "ไม่ เครื่องมือวางรูปภาพลายเซ็นลงใน PDF เท่านั้น จึงไม่มี certificate การยืนยันตัวตน timestamp หรือหลักฐานความยินยอม" },
      { question: "รองรับหน้า PDF ที่หมุนอยู่หรือไม่?", answer: "รองรับหน้า 0, 90, 180 และ 270 องศา โดยเครื่องมือแปลงตำแหน่งจากภาพตัวอย่างไปยังพิกัด PDF ตามมุมของแต่ละหน้า" },
    ],
  },
];

export const toolMap = new Map(tools.map((tool) => [tool.slug, tool]));
export const categoryMap = new Map(categoryConfigs.map((category) => [category.value, category]));

export function getTool(slug: string): ToolConfig | undefined {
  return toolMap.get(slug);
}

export function getCategory(value: string): ToolCategoryConfig | undefined {
  return categoryMap.get(value as ToolCategory);
}

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return tools.filter((tool) => tool.category === category);
}

export function searchTools(query: string, category: ToolCategory | "all" = "all") {
  const normalized = query.trim().toLocaleLowerCase("th");
  return tools.filter((tool) => {
    const matchesCategory = category === "all" || tool.category === category;
    const haystack = [tool.name, tool.thaiName, tool.shortDescription, ...tool.keywords]
      .join(" ")
      .toLocaleLowerCase("th");
    return matchesCategory && (!normalized || haystack.includes(normalized));
  });
}
